### ISSUE TITLE
Multi-level naming

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#1016]
Just an observation. Perhaps it's due to non-native English or translation or maybe it's a European thing. The different level names are a little confusing imo.

When you log in as Global Administrator the name on the portal is "Global Administration Portal" and the right side configuration panel says "Global Configuration". However, the user is still called "Operator". It would be less confusing if they were called "Global Operator" or "Global Admin" or "Super Admin" imo.

The next level down (Brand) should really be called "Reseller" or maybe "Subaccount". That level also has "Operators" which should really be called "Administrators" or maybe "Reseller Operators" or "Brand Operators".

You have a "Clients" level and then a "Users" level which can be confused as the same thing. In the current documentation, "Clients" are called "Companies". You don't seem to be using "Company" in the GUI anywhere. "Clients" should really be called "Tenants" or perhaps something else that does not confuse "Clients" with "Users" imo.

**Comment by Kaian** [comment]
This won't change for current release, but we take note for future releases.

Thanks for the input!
