### ISSUE TITLE
Problems with additional proxy in front of the system

### ISSUE THREAD

**Issue by hyperbaba** [irontec/ivozprovider#1017]
Hi there,
i tried to add additional proxy in front of the ivozprovider standalone system. The proxy in question is flexisip which i need for push notification to mobile clients. The problem is that when alice and bob are registered through that proxy to the system (the demo vpbx users) , they can't call each other because the rewritten domain of the callee. So, when bob calls alice call comes to the ivozprovider platform and then invite is send to alice but the bob's domain is 127.0.0.1 instead of the original caller domain. The domain is not changed on additional outbound proxy, but instead in the ivozprovider platform itself... Here is a simple sniplet from sngrep

INVITE sip:101@PLATFORM.IP SIP/2.0
Via: SIP/2.0/UDP ADDITIONAL_OUTBOUND_PROXY.IP;rport;branch=z9hG4bK.FH0jQ17U3jtcDHy2X37evUScZF
Via: SIP/2.0/UDP CLIENT.IP:60881;branch=z9hG4bK.ajkYomTy0;rport=60881
From: <sip:bob@PLATFORM.IP>;tag=kF3Bd4C20
To: <sip:101@1PLATFORM.IP>
CSeq: 21 INVITE
Call-ID: h3nM8Vv5H3
Max-Forwards: 69
Supported: replaces, outbound, gruu
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Contact: <sip:bob@CLIENT.IP:60881>;+sip.instance="<urn:uuid:f33b914b-0428-0002-a5f3-697e0295c733>"
User-Agent: LinphoneAndroid/4.1.1 (Xperia E5) LinphoneSDK/4.2-8-g96666b3 (release/4.2)
Proxy-Authorization: Digest realm="PLATFORM.IP", nonce="XQKeVV0CnSmuXruqv6EJO4C5RRXXXXXXX", username="bob", uri="sip:101@PLATFORM.IP", response="286e46e255ec08afb35700cf172cee3f"
Content-Length: 537
Record-Route: <sip:ADDITIONAL_OUTBOUND_PROXY.IP:5060;lr>

v=0
o=bob 2331 221 IN IP4 CLIENT.IP
s=Talk
c=IN IP4 ADDITIONAL_OUTBOUND_PROXY.IP
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
a=nortpproxy:yes
m=audio 46818 RTP/AVP 96 97 98 0 8 18 101 99 100
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 speex/16000
a=fmtp:97 vbr=on
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=fmtp:18 annexb=yes
a=rtpmap:101 telephone-event/48000
a=rtpmap:99 telephone-event/16000
a=rtpmap:100 telephone-event/8000
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr

and the call to alice looks like
INVITE sip:alice@ADDITIONAL_OUTBOUND_PROXY.IP:5060;line=0788c8acef4a8bd;CtRt42aaa94328d29d23=udp:PLATFORM.IP SIP/2.0
Record-Route: <sip:PLATFORM.IP;lr;ftag=06c7fe8b-9f4f-4411-9704-904591019d66;did=1.9eb>
Via: SIP/2.0/UDP PLATFORM.IP;branch=z9hG4bKaa7.125f6a592989d63f109c584e211dd644.0
Route: <sip:ADDITIONAL_OUTBOUND_PROXY.IP:5060;fs-proxy-id=42aaa94328d29d23;lr>
Via: SIP/2.0/UDP 127.0.0.1:6060;received=127.0.0.1;rport=6060;branch=z9hG4bKPj908fd72a-b8a8-4a93-b9a4-13e7bab40284
From: "Bob Bobson" <sip:102@127.0.0.1>;tag=06c7fe8b-9f4f-4411-9704-904591019d66
To: <sip:alice@PLATFORM.IP>
Contact: <sip:asterisk@127.0.0.1:6060>
Call-ID: 78756cef-a877-4161-a143-9673e488bbf4
CSeq: 21245 INVITE
Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, REGISTER, REFER
Supported: timer, replaces, norefersub
Session-Expires: 1800
Min-SE: 90
P-Asserted-Identity: "Bob Bobson" <sip:102@127.0.0.1>
Max-Forwards: 69
User-Agent: Irontec IvozProvider v2.10
Content-Type: application/sdp
Content-Length:   253

v=0
o=- 1593920627 1593920627 IN IP4 PLATFORM.IP
s=Asterisk
c=IN IP4 PLATFORM.IP
t=0 0
m=audio 17126 RTP/AVP 8 101
a=maxptime:150
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:17127
a=ptime:20

if you need additional logs i will provide them

**Comment by Kaian** [comment]
Hi,

I'm not sure where the actual problem is here. Is ivozprovider misbehaving in any form that breaks with the RFC? Or this is just an unsupported environment scenario?

Regards!

**Comment by hyperbaba** [comment]
To tell You the truth I'm not sure. I just observed the behavior and was
compelled to report it. I really can't find why the domain of the caller is
changed to localhost when both clients use additional sip proxy. I've
traced the change between asterisk and kamailio on the standalone server
but i did not go any further. Also I've noticed that when using PATH header
on the sip proxy in front of the system, kamailio complains with bad
extension when trying to register the client because the use-path is set to
2 by default. When i set it to 1 the registration is done but then i
encountered a problem with the domain when making intra vpbx calls. To tell
you the honestly i would be more happy that ivozprovider itself can manage
the mobile push scenario for mobile clients, something like this solution
https://medium.com/@denys.pozniak/apple-push-notification-with-kamailio-eeca2f8e08d,
. A http call to the service which does actual push is enough, the main
thing is joining the sessions in kamailio.
.

Best Regards,

**Comment by Kaian** [comment]
> To tell You the truth I'm not sure. I just observed the behavior and was
compelled to report it. I really can't find why the domain of the caller is
changed to localhost when both clients use additional sip proxy. I've
traced the change between asterisk and kamailio on the standalone server
but i did not go any further. 

Currently we don't offer support on anything but software flaws in github. If you find something that goes agains the RFC or a flaw in the logics, feel free to open an issue. Otherwise it will be considered as an enviroment problem and like [FAQ](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md) mentions it will require commercial support.

>To tell you the honestly i would be more happy that ivozprovider itself can manage
the mobile push scenario for mobile clients, something like this solution
https://medium.com/@denys.pozniak/apple-push-notification-with-kamailio-eeca2f8e08d,
. A http call to the service which does actual push is enough, the main thing is joining the sessions in kamailio.

This is also mentioned in the FAQ linked above, if you think a *new* feature will be great, don't hesitate to contact our comercial team to sponsor it. Also if you want to contribute yourself by submiting any feature as Pull Request we will valorate to include it in the product.

Thanks for your feedback!

Regards
