### ISSUE TITLE
Impossible to create Users with the API of v2.11

### ISSUE THREAD

**Issue by glacroix** [irontec/ivozprovider#1027]
Hello,

I can not create Users anymore with API (POST - Users) since v2.11. I have experienced 2 problems : 

1. When setting an email in the parameters sent, I have a message : "app.ERROR: Active users must have a password [] []". I have tried to send 'pass', 'password', 'pwd' as well but still the same message (it was not necessary to set anything in the earlier version)

2. So I tried with no email in parameters and then I have the message :
app.ERROR: Variable "callACL" is not valid around position 26 for expression `((company in [4])) and ((callACL in []) or (callACL == null)) and ((bossAssistant in []) or (bossAssistant == null)) and ((outgoingDdiRule in []) or (outgoingDdiRule == null)) and ((voicemailLocution in []) or (voicemailLocution == null)) and ((bossAssistantWhiteList in []) or (bossAssistantWhiteList == null)) and ((terminal in [9,10,11,12,13,14,15]) or (terminal == null)) and ((extension

The problem can be reproduce easily by using the Web API.

Thanks,
Guillaume

**Comment by mmadariaga** [comment]
We're already working on the fix.

Thanks for reporting :)

**Comment by glacroix** [comment]
Do not hesitate If I can be of any help (I tried to dig in the code, but too much to learn :)).
I make mys tests on a standalone installation of v2.11 (scratch from ISO), do you think I could keep and patch it (through apt upgrade maybe ?) when the patch is done ?

**Comment by Kaian** [comment]
Hi @glacroix 

The correcton for this issue has been hotfixed in artemis release, so in this case you can get the patch by adding debian apt repositories for artemis and upgrading your system.


https://irontec.github.io/ivozprovider/en/artemis/basic_concepts/installation/debian_install.html#apt-repository-configuration

Regards
