### ISSUE TITLE
Feature request: Add Voicemail access through API

### ISSUE THREAD

**Issue by glacroix** [irontec/ivozprovider#1034]
Hello,

I am testing voicemail access through the APIs. As far as I see, no API exist, so the only way to access the voicemail without dialing *93 is to directly parse the storage directory.

Problem is that if a message is read through the directory, it will be kept in the INBOX directory (so still 'new'). Or if a message is deleted, the naming convention for the message files (0001, 0002 etc...) will be messed up. Solution could be to re-create the logic of the naming when deleting or moving a message to Old/ (rather complex tho).

Last solution would be to use Real Time and store the data in DB (but I think you just want to have metadatas in the DB, not the whole message - not sure this is possible with ARA).

Is there any other logic I miss to access / read / delete the messages without dialling *93 ?

Thanks !
Guillaume

**Comment by Kaian** [comment]
Hi @glacroix 

As you mention, currently the only way to access to voicemail files is through Check Mail Service (default service code is *93). There is no Voicemail entity for business application layer (the entities that are exposed though the API), and the best approach to expose them will probably be the realtime table you also mentioned (with support for file system objects not stored in DB like other entities have).

I will rename the issue accordingly to become a feature request. Like for other new features, feel free to contact our commercial support if you need this to be scheduled into a release.

Regards!

**Comment by Kaian** [comment]
This was implenented in #1755 for 3.0 (not yet released)
