### ISSUE TITLE
After deleting residential client , imposible to create new residential/retail devices

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1038]
To reproduce:   fresh 2.11.0 install
-Create Residential client A
-Enter A client
-Create Residential device Adevice
-Remove Adevice and A client, or delete in cascade Aclient directly

After this, you cannot create more retail devices or residential devices
The problem starts when deleting a residential/retail client, nor residential/retail device

webfront
![image](https://user-images.githubusercontent.com/6016929/60328429-907c9400-998e-11e9-8882-eff45c490dd8.png)

logs:
```

Jun 28 03:07:22 ivozprovider-standalone klear[1386]: Argument 2 passed to Ivoz\Provider\Infrastructure\Persistence\Doctrine\RetailAccountDoctrineRepository::findOneByNameAndDomain() must implement interface Ivoz\Provider\Domain\Model\Domain\DomainInterface, null given, called in /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Service/ResidentialDevice/CheckUniqueness.php on line 53 (0) # /opt/irontec/ivozprovider/library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/RetailAccountDoctrineRepository.php(28)
```

I'm not sure but I think I have made this with 2.9 or 2.10 and not happened...

**Comment by Kaian** [comment]
Hi @gil-obradors

This was fixed a couple days ago and it's already available in artemis branch so you can fix it by updating your environment.

The problem was that residential clients has the same domain as the brand and client delete service was removing the domain without checking the client type. See 7f75394822c365c505897dee352d9fe08dff0480

Regards,

**Comment by gil-obradors** [comment]
I will pay attention to commits before releases.... thank you!

best sips

**Comment by Kaian** [comment]
We usually hotfix in artemis branch issues that are too important to wait for the next release.

Thanks for reporting! :)
