### ISSUE TITLE
client portal does not work properly

### ISSUE THREAD

**Issue by Infoworlds** [irontec/ivozprovider#1042]
Hello Team,

I have add client portal in IVOZ and also attach an URL to redirect the link .But it was not working if i am to open the in URL tab they continously shows the Error.

Here is the Error:-
This page isn’t working www.example.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

May I know, the reason then why it generate this Error.

Thanks in advance

**Comment by Kaian** [comment]
Is this duplicated from #1043 ?
