### ISSUE TITLE
Client portal url not working

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1043]
Hello all,

I have deployed ivoz but when i am creating client portal and configure DNS with A records

Url not working properly . check the screenshot link

http://prntscr.com/o8bbod

http://prntscr.com/o8bc2u

and nothing is not showing in error logs

can you please give me any hint to fix the concern, i have checked .htaccess and virtual host but nothing to solve the concern

please help 

thanks

**Comment by gil-obradors** [comment]
HI @rccess ?
What version have installed?
Have you edit manually any file from web-server?

From a fresh install you don't have to edit anything more than the A record ( as you say) and add the domains to Web-portals ( brand...client)
I have not tested for clients, but brand and Provider I can confirm that you can put domains without problems

Can you enter directly by Ip https://x.x.x.x ?


Good luck

**Comment by rccess** [comment]
thanks for your reply !

i have never change any file manually 

same concern facing on brand portal 

http://prntscr.com/o8hwoe

http://prntscr.com/o8hwqj

access with ip , only operator portal get open, how i can access client portal or brand portal with IP

 https://x.x.x.x 

http://prntscr.com/o8hx4z

Please advise

**Comment by gil-obradors** [comment]
Hi!
Somthing strange you have in the config: 
```
curl https://ct5.telcob.cloud/ -k
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://ct5.telcob.cloud/">here</a>.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at ct5.telcob.cloud Port 80</address>
```

I can assure with a fresh install Artemis 2.11 you must haven't got any problem.

Have you changed the SSL certificates?
What version and branch have you installed?
Why port 80 isn't redirecting to 443, as default install files do?

I think you can't entry with IP to client portals, only with domain.
https://irontec.github.io/ivozprovider/en/artemis/user_portal/index.html

Good luck!

**Comment by rccess** [comment]
hello @gil-obradors

As per your suggestion i am trying to fresh installation of ivoz but they continuosly generating the Error .
Here is the following attachments:-

![Screenshot_3](https://user-images.githubusercontent.com/32220165/60415239-3ed74200-9bf8-11e9-9879-ca0028741c5e.png)
![Screenshot_4](https://user-images.githubusercontent.com/32220165/60415249-4565b980-9bf8-11e9-830e-3da065743c71.png)
![Screenshot_5](https://user-images.githubusercontent.com/32220165/60415265-4a2a6d80-9bf8-11e9-8e74-89e799198ece.png)
![Screenshot_6](https://user-images.githubusercontent.com/32220165/60415273-4e568b00-9bf8-11e9-8e3f-9fd6281435a6.png)


they cannot started the rtpengine service and kamailio service and they also showing the mysql database error.
Please seen the above attachments and advice on this .

Thanks in advance

**Comment by gil-obradors** [comment]
Hi @rccess 
For fresh install I refer to download Artemis iso and install it. You too?
Why are you doing dpkg-reconfigure?
Can you report all changes/configs have you made to reach this point?
Or (maybe better) can you re-start from 0 and write every change/config steps to reach this fault point?

best sips

**Comment by rccess** [comment]
Hello @gil-obradors 

I am also trying to reinstall in another way without using dpkg-reconfigure but they show same  error of rtpengine ,kamailio and mysql.
![Screenshot_7](https://user-images.githubusercontent.com/32220165/60424760-a6988780-9c0e-11e9-9c8a-b950ebd6bcc8.png)
please show the above attachments .it also generating another error.
can you please help me out to resolve the following issues.

**Comment by gil-obradors** [comment]
hi @rccess 
[At default page of the project](https://github.com/irontec/ivozprovider#installation)
You can try Artemis(testing) or Oasis (stable)

I can only help you with Artemis ( if it complies your requirements)

Best sips

**Comment by Kaian** [comment]
Hey everyone,

We're mixing multiple problems here, it would be better to split each problem into an issue for better change management.

Also, we don't provide support for environment issues, just for software flaws (see [FAQ](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md)), so if we can not reproduce the problem and there is no enough information to prove a bug, the issue will close (unless someone in the community is willing to help you, like in this case).

We were unable to reproduce the portal infinite redirection bug yet. God portal usually works because is the only portal that doesn't require a valid domain: any IP address in the box works to reach this portal.

The mysql errors shown here are usually a misconfiguration during installation: mysql password is asked **twice**, once during the mysql-server package installation and one in the ivozprovider configuration menu. You must configure **both** settings with the same value. Also password can not be empty.

As @gil-obradors mentions, iso links and docummentation is available in project front page.

Regards,

**Comment by rccess** [comment]
Hello @gil-obradors 

I have installed ivoz properly but i am trying to work on platform portal in global configuration so it cannot redirect to the given link and when i am seen the error.log file it shows the following error:-

![Screenshot_8](https://user-images.githubusercontent.com/32220165/60435842-35fe6480-9c28-11e9-9489-6b0750ee2d28.png)

please seen the above attachment.

**Comment by gil-obradors** [comment]
Hi @rccess )

If you are trying to set a valid SSL certifcate, try to play with [letsencrypt](https://letsencrypt.org/)
Generate it, and then modify the values of SSLCertificate in ```/etc/apache2/sites-available/020-ivozprovider-portals.conf```

I can assure you that is compatible and runs without complications with IvozProvider Artemis 2.11

I think I can't help more


Good luck!

**Comment by rccess** [comment]
i have successfully installed ssl with letsencrypt 

but brand portal having same issue on ctn.telcob.cloud

![Screenshot_25](https://user-images.githubusercontent.com/32220165/60442835-88934d00-9c37-11e9-8d79-571fadf2fb9b.jpg)
![Screenshot_27](https://user-images.githubusercontent.com/32220165/60442851-91841e80-9c37-11e9-9860-f364a522199a.jpg)

nothing is showing in error log

**Comment by rccess** [comment]
> Hi!
> Something strange you have in the config:
> 
> ```
> curl https://ct5.telcob.cloud/ -k
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>302 Found</title>
> </head><body>
> <h1>Found</h1>
> <p>The document has moved <a href="https://ct5.telcob.cloud/">here</a>.</p>
> <hr>
> <address>Apache/2.4.25 (Debian) Server at ct5.telcob.cloud Port 80</address>
> ```
> 
> I can assure with a fresh install Artemis 2.11 you must haven't got any problem.
> 
> Have you changed the SSL certificates?
> What version and branch have you installed?
> Why port 80 isn't redirecting to 443, as default install files do?
> 
> I think you can't entry with IP to client portals, only with domain.
> https://irontec.github.io/ivozprovider/en/artemis/user_portal/index.html
> 
> Good luck!

i am having this issue with 2.11 version 

![image](https://user-images.githubusercontent.com/32220165/60492930-8e397300-9cc9-11e9-85a2-13fdb2b5438b.png)

can you please check the conf file if i am missing something there

**Comment by rccess** [comment]
@Kaian 
can you please help me out with the same , i am trying since last 5-6 days , there is no solution found anywhere , i tried alot from my side , i need your help please 


thanks

**Comment by Kaian** [comment]
Hi @rccess

I don't see anything wrong with that config. I could try installing one iso myself and check if this is a software bug but half of my coworkers are on holidays so there is no time right now.

If you need support asap, our commercial team will help you at comercial@irontec.com

Otherwise you must wait to someone of the community helps you. 

Be aware what we mentioned in my previous note: This is not a support forum. We don't offer support for environment issues. I leave this issue open because I can't confirm myself if this problem is in ivozprovider side or your environment.

Regards,

**Comment by rccess** [comment]
Hello all !

The issue has been resolved! 

let me post the solution for all !

i was using Cloudflare in DNS and Cloudflare install self ssl 

and the issue was a conflict between SSL of Cloudflare and ivoz ssl

the concern has been solved but there is another concern which is very realistic and not environment depended 

1. language of using portal 
https://ctuser.veetly.com/portal
https://ctbrand.veetly.com/
https://ctcompany.veetly.com/

2. users are not login into user portal 

i have raised separate concern for the same in #1050
