### ISSUE TITLE
User panel does not login

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1050]
Hello Everyone,

I have made a client portal with all details but when i was trying to login within given client url it shows the login error.

Here is the following attachments:-
![Screenshot_10](https://user-images.githubusercontent.com/32220165/60570927-3285ed00-9d90-11e9-9d92-7ee1c240d0aa.png)

could anyone help me to found out the error and provide the suggestion?

Thank You

**Comment by mmadariaga** [comment]
Hi there,

I just have checked that user portal is working fine in our test environment so I'll assume there are no code issues here. 

It looks like you're getting a 401 Unauthorized response code here. Please make sure that user brand and portal brand are the same one and double check that your user settings are correct (Login Info block on admin portal):
- The user must be active
- Reset the password

You can try to get a user token directly on the API (https://userdomain.net/api/client/) as well using /user_login endpoint.

**Comment by rccess** [comment]
Thank you for the information @mmadariaga.
I just want to ask you an another query that is how we can configure asterisk at using  front end or backened.

**Comment by rccess** [comment]
Hello @mmadariaga 

when i was trying to create brand portal and user portal same they show the Duplicate value found error.
please seen the following attachment:-

http://prntscr.com/o9zmh5

**Comment by rccess** [comment]
solved , thanks for your quick help !
