### ISSUE TITLE
 Calls could not be forward

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1058]
Hello All,

When I was trying to make an external call , system is not able to make outgoing calls result in logs congestion error.

here are the logs:-
http://prntscr.com/oav6bh

And while i am trying to call on my configured DDI number calls are not landing 
According to my Voip Provider 
"_For now all I can say is that under GoTrunk we are not receiving any packet from this server public IP 67.207.95.250 and we should at least receive the register packets. We need to receive registration packets firts in order to be able to send calls to PBX._  "

Here is the following output of sngrep Command:-
http://prntscr.com/oavagi

Thanks in advance

**Comment by Kaian** [comment]
Hi,

This is a environment problem. This depends on your installation and GoTrunk.

If you need support please contact comercial@irontec.com

Regards
