### ISSUE TITLE
kamtrunks not sending packet to voip provider

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1059]
Hello all,

i just configured DDI provider along with Server , but it is not sending any registration packet request to voip provider , it is working fine in chan sip but not in kamailio 

![image](https://user-images.githubusercontent.com/32220165/60753518-3ebcb500-9ff1-11e9-8a08-9767f27bf875.png)

![image](https://user-images.githubusercontent.com/32220165/60753525-6a3f9f80-9ff1-11e9-9528-e6edeae69a52.png)

![image](https://user-images.githubusercontent.com/32220165/60753723-afb19c00-9ff4-11e9-80ca-9f87ab69565d.png)

can anyone advise on that

**Comment by Kaian** [comment]
According to the last screenshot, IvozProvider is sending a REGISTER message and the endpoint is responding 501 Not Implemented.

This is a environment problem, not a software failure. If you need support please contact comercial@irontec.com

Regards

**Comment by rccess** [comment]
Hello kaian 
Can you please advise what may be the possible reason for the same 

i have checked everything which is possible from my side

![image](https://user-images.githubusercontent.com/32220165/60856738-d7d41180-a225-11e9-9e97-3f4701ba410d.png)

Please advice

Thanks

**Comment by Kaian** [comment]
I have never seen those errors before, so I can not give you any advice.

Use capture tools and debug what the error means. If you think this is a kamailio problem, try asking in their project.

Regards
