### ISSUE TITLE
Chan-SIP compatibility

### ISSUE THREAD

**Issue by TMVaquer** [irontec/ivozprovider#1062]
Can ivozprovider connect to a trunk via Chan-SIP instead of PJSIP?

We are sending a INVITE packet from Trunk to PBX but there is no single reply back or log for the incoming INVITE. From local TCPDUMP on PBX side:

15:35:17.817043 IP amn.st.ssl7.net.sip > cloud.hemant.live.sip: SIP: INVITE sip:12055430291@67.207.95.250:5060 SIP/2.0

We are thinking this is due to PBX is expecting PJSIP library only.

**Comment by rbetancor** [comment]
SIP it's SIP, no matter if Chan_SIP or PJSIP as far as it follow the SIP standars.

I Doubt that chan_sip will never be used on IVoz, due to all it limitations to a platform like this one.

Your problem seems more related to firewalling o something else, not to the channel driver used by IVoz.

**Comment by Kaian** [comment]
> Can ivozprovider connect to a trunk via Chan-SIP instead of PJSIP?
Of course, and can also connect to any SIP capable endpoint, not only asterisk :stuck_out_tongue: 

As @rbetancor mentions, this does not depend on the channel driver used by IvozProvider or the other endpoint and seems more related to a firewall issue. 

Remember that capture tools are able to see incoming packets before firewall drops them.

Regards!
