### ISSUE TITLE
RTPEngine trigger error on fresh installation 

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1063]
Hello All,

Fresh Installation bug detected debian 9 with  artemis 2.11.1

![image](https://user-images.githubusercontent.com/32220165/60824813-f1df0700-a1c7-11e9-987e-04eb0d24d651.png)

Please advice 

Thanks

**Comment by Kaian** [comment]
RTPEngine uses a kernel module to handle audio packets. Maybe that's the problem

Can you provide the output of:

 * uname -a
 * lsmod
 * cat /etc/default/rtpengine

Regards

**Comment by rccess** [comment]
![image](https://user-images.githubusercontent.com/32220165/60870940-69a44480-a24f-11e9-8fa2-627200e23de8.png)


![image](https://user-images.githubusercontent.com/32220165/60870987-82acf580-a24f-11e9-9077-1f673a156f4b.png)

![image](https://user-images.githubusercontent.com/32220165/60871013-90627b00-a24f-11e9-9f66-6bc318feb3c6.png)

**Comment by Kaian** [comment]
Did you tried rebooting your machine?

**Comment by rccess** [comment]
no, not rebooted , but tested on another machine with reboot , same issue
________________________________________________________
root@vpbxserver:/etc/apt/sources.list.d# service rtpengine start^C
root@vpbxserver:/etc/apt/sources.list.d# systemctl status rtpengine.service
● rtpengine.service - RTPEngine Mediaproxy
   Loaded: loaded (/lib/systemd/system/rtpengine.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-07-09 10:15:51 CEST; 18s ago
  Process: 21696 ExecStart=/usr/sbin/rtpengine --table=0 --interface=${AUDIO_SOCK} --listen-ng=${CONTROL_SOCK} --listen-cli=127.0.0.1:9900 --xmlrpc-format=1 -
  Process: 21695 ExecStartPre=/sbin/iptables -D INPUT -p udp -j RTPENGINE --id 0 (code=exited, status=1/FAILURE)

Jul 09 10:15:50 vpbxserver.hemant.live systemd[1]: rtpengine.service: Control process exited, code=exited status=255
Jul 09 10:15:50 vpbxserver.hemant.live systemd[1]: Failed to start RTPEngine Mediaproxy.
Jul 09 10:15:50 vpbxserver.hemant.live systemd[1]: rtpengine.service: Unit entered failed state.
Jul 09 10:15:50 vpbxserver.hemant.live systemd[1]: rtpengine.service: Failed with result 'exit-code'.
Jul 09 10:15:51 vpbxserver.hemant.live systemd[1]: rtpengine.service: Service hold-off time over, scheduling restart.
Jul 09 10:15:51 vpbxserver.hemant.live systemd[1]: Stopped RTPEngine Mediaproxy.
Jul 09 10:15:51 vpbxserver.hemant.live systemd[1]: rtpengine.service: Start request repeated too quickly.
Jul 09 10:15:51 vpbxserver.hemant.live systemd[1]: Failed to start RTPEngine Mediaproxy.
Jul 09 10:15:51 vpbxserver.hemant.live systemd[1]: rtpengine.service: Unit entered failed state.
Jul 09 10:15:51 vpbxserver.hemant.live systemd[1]: rtpengine.service: Failed with result 'exit-code'.

**Comment by Kaian** [comment]
Try rebooting, if the problem persist, provide the output of the commands again (you missed the last one)

**Comment by rccess** [comment]
after reboot output

___________________________________________________________________________
![image](https://user-images.githubusercontent.com/32220165/60871528-91e07300-a250-11e9-8b67-736ab2b08840.png)

![image](https://user-images.githubusercontent.com/32220165/60871557-a3297f80-a250-11e9-8cc5-5d797d7f51fb.png)

![image](https://user-images.githubusercontent.com/32220165/60871615-b9cfd680-a250-11e9-8a97-4c94f028b9ae.png)


![image](https://user-images.githubusercontent.com/32220165/60871645-c7855c00-a250-11e9-9708-0d803887e963.png)


![image](https://user-images.githubusercontent.com/32220165/60871675-d704a500-a250-11e9-953d-3372b9cf5791.png)

**Comment by rccess** [comment]
after reboot output

___________________________________________________________________________
![image](https://user-images.githubusercontent.com/32220165/60871528-91e07300-a250-11e9-8b67-736ab2b08840.png)

![image](https://user-images.githubusercontent.com/32220165/60871557-a3297f80-a250-11e9-8cc5-5d797d7f51fb.png)

![image](https://user-images.githubusercontent.com/32220165/60871615-b9cfd680-a250-11e9-8a97-4c94f028b9ae.png)


![image](https://user-images.githubusercontent.com/32220165/60871645-c7855c00-a250-11e9-9708-0d803887e963.png)


![image](https://user-images.githubusercontent.com/32220165/60871675-d704a500-a250-11e9-953d-3372b9cf5791.png)

**Comment by Kaian** [comment]
The kernel module is missing. Can you reinstall ivozprovider-rtpengine package and provide the output in text mode, not images?

    apt-get install --reinstall ivozprovider-rtpengine

Regards

**Comment by rccess** [comment]
same issue 

![image](https://user-images.githubusercontent.com/32220165/60871898-53978380-a251-11e9-9764-f2d4125f5609.png)

**Comment by rccess** [comment]
i have installed  linux-headers-4.9.0-6-amd64 dependencies

after reinstallation 

https://pastebin.com/ZEFT2iiu

**Comment by Kaian** [comment]
Please, do not post images of console text. It makes impossible to copy and paste nothing from the logs.

Try loading RTPENGINE module (it's automatically done after rebooting):

    modprobe xt_RTPENGINE

Regards

**Comment by rccess** [comment]
it is started , thanks for your quick help 

you are rockstar :)

**Comment by Kaian** [comment]
No problem,

This is a common problem if you're not using the latest debian kernel for your release (in this case linux-image-4.9.0-9-amd64)

If you update your kernel, be sure to reinstall ivozprovider-rtpengine package to recompile the module again.

Regards

**Comment by rccess** [comment]
ok thanks

________________________________________
one last concern please 

after starting trunk service my DDI Provider server not getting registered 

root@vpbxserver.hemant.live:~# journalctl -u kamailio@trunks -f
-- Logs begin at Tue 2019-07-09 10:35:04 CEST. --
Jul 09 10:44:12 vpbxserver.hemant.live /usr/sbin/kamailio[2364]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 09 10:44:12 vpbxserver.hemant.live /usr/sbin/kamailio[2365]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 09 10:44:12 vpbxserver.hemant.live /usr/sbin/kamailio[2330]: ERROR: <core> [core/udp_server.c:607]: udp_send(): sendto(sock,0x7fc2166fa368,426,0,109.233.115.107:5060,16): Invalid argument(22)
Jul 09 10:44:12 vpbxserver.hemant.live /usr/sbin/kamailio[2330]: CRITICAL: <core> [core/udp_server.c:612]: udp_send(): invalid sendtoparameters
                                                                 one possible reason is the server is bound to localhost and
                                                                 attempts to send to the net
Jul 09 10:44:12 vpbxserver.hemant.live /usr/sbin/kamailio[2330]: ERROR: tm [../../core/forward.h:219]: msg_send_buffer(): udp_send failed
Jul 09 10:44:12 vpbxserver.hemant.live /usr/sbin/kamailio[2330]: ERROR: uac [uac_reg.c:1032]: uac_reg_tm_callback(): got sip response 503 while registering [1562661573585]
Jul 09 10:44:13 vpbxserver.hemant.live /usr/sbin/kamailio[2345]: NOTICE: Connection with CGrates established (127.0.0.1:38938)!!
Jul 09 10:44:13 vpbxserver.hemant.live /usr/sbin/kamailio[2345]: ERROR: Connection with CGrates closed!!
Jul 09 10:44:13 vpbxserver.hemant.live /usr/sbin/kamailio[2345]: INFO: evapi [evapi_dispatch.c:376]: evapi_recv_client(): client closing connection - pos [0] addr [127.0.0.1:38938]
Jul 09 10:44:13 vpbxserver.hemant.live /usr/sbin/kamailio[2345]: NOTICE: Connection with CGrates established (127.0.0.1:38940)!!

![image](https://user-images.githubusercontent.com/32220165/60873716-6eb7c280-a254-11e9-9046-d04b4457c4e8.png)

**Comment by Kaian** [comment]
I answered to this in #1059

**Comment by rccess** [comment]
i already contacted on commercial mail id for commercial support but no one responded over there :(

let me try to capture to debug , hope you will give some hints

**Comment by Kaian** [comment]
Our sales guy is on holiday, you'll have to be patient

**Comment by damidani** [comment]
Hello,

I just want to inform you that I had the same problem and to solve it I made this line : apt-get install 4.9.0-16-amd64

Then : modprobe xt_RTPENGINE

And : apt-get install --reinstall ivozprovider-rtpengine
 Hoping to have helped you.

**Comment by Kaian** [comment]
Thanks for the hint! the install package is probably linux-headers-4.9.0-16-amd64 ?

I found myself doing also this manually. This problem is caused because the kernel used in the install iso and the kernel actually installed by te iso are no the same, so the module ends being compiled for a different kernel during standalone iso install. This was also discussed in #606

This should'nt happen if you install a base debian and ensure you're running the latest available kernel for stretch. The rtpengine package should pull linux-headers-amd64 dependency that should match the latest kernel. 

Thanks for the 2 cents!
