### ISSUE TITLE
External calls are not routing 

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1065]
Hello All ,

having issues with external calls redirections 

no external calls are working , calls are getting rejected !

![image](https://user-images.githubusercontent.com/32220165/60949480-ef3cf880-a312-11e9-87a7-f99be5932e3e.png)

![image](https://user-images.githubusercontent.com/32220165/60949788-87d37880-a313-11e9-8d87-2a9c5b2b803f.png)

here is the pastebin code

https://pastebin.com/uN8GjTr2

**Comment by Kaian** [comment]
Please read FAQ: https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md#i-have-trouble-with-my-environment


**I have trouble with my environment!**
We don't provide any kind of free support for installations. If you have trouble, you can contact our sales department at comercial@irontec.com

If by any chance you receive support in Github or #ivozprovider freenode IRC channel, it's most probably provided during developers spare time, so be thankful for the people giving part of their time.
