### ISSUE TITLE
Multi-level IVR

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1067]
Hello All,

We are  trying to implementing  Multi-level IVR anyone can help this.

Please response with suggestions and opinion on this.

Here is the structure:-
http://prntscr.com/odg8ko

Thank You

**Comment by Kaian** [comment]
Hi @rccess 

You need two IVRs to achieve that.

Add an extensions routed to the second IVR and point the first IVR Sales entry to that extension.

Regards!

**Comment by rccess** [comment]
hello @Kaian 

On press 1 option IVR option is not showing to redirect on the another IVR.

http://prntscr.com/odk6wo

**Comment by Kaian** [comment]
Create an extension routed to the other IVR

Then in the screen you have attached select RouteType: Extension y the extension of the other IVR

**Comment by rccess** [comment]
It's done. thank you @Kaian for your help.

**Comment by Kaian** [comment]
You welcome!
