### ISSUE TITLE
trunks start trigger error on fresh installation debian 9 

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1068]
Hello All & @Kaian 

new error triggered on systemctl restart kamailio@trunks.service

error showing not resolve host , but i have a proper hostname 

https://pastebin.com/cEbLXBZ3

![image](https://user-images.githubusercontent.com/32220165/61066042-7af17a80-a422-11e9-8f6f-360fe79dd0d1.png)

![Screenshot_31](https://user-images.githubusercontent.com/32220165/61066066-847ae280-a422-11e9-9cee-e18fa3921200.jpg)

**Comment by Kaian** [comment]
IvozProvider uses a local bind for DNS resolution

Provide the output of `cat /etc/resolv.conf` in text
