### ISSUE TITLE
DDI Provider registration URI issue

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1070]
Hello all & Kaian 

I am facing a different kind of problem 

my SIP provider getting registered with sip.conf 

![image](https://user-images.githubusercontent.com/32220165/61179288-3bdb4900-a61d-11e9-9213-6ea72b182724.png)

but when i am doing same configuration in ivozprovider interface 

sip registry getting timeout 

![image](https://user-images.githubusercontent.com/32220165/61179314-8c52a680-a61d-11e9-92d8-aa7eee21f5f9.png)

below the sip configuration which i am using in sip.conf and getting registered
***************************************************

[general]

;register => +911XXXXX12100:XXX56:+911XXXX2100@dxxxhi.rexxxxeims.in/91141xxxxx2100

register => +9114xxxxx100@xxxhi.relxxxims.in:1xxxxxx56:+9114xxxxx100@dxxxxhi.relixxxms.in@10.237.252.225/+911xxxxx2100

username=+91xxx4xxx00
secret=xxxxxx56
type=friend
host=dxxxxxhi.rxxxxxxms.in
dtmfmode=rfc2833
nat=no
canreinvite=no
fromuser=+911xxxxxx100
disallow=all
allow=ulaw
allow=alaw
allow=gsm
context=default
defaultexpiry = 1900

******************************************************

ivoz interface setting

![image](https://user-images.githubusercontent.com/32220165/61179339-1733a100-a61e-11e9-9598-01bdc7069be4.png)

**Comment by Kaian** [comment]
This seems an environmental issue.

We don't use asterisk for registration, but kamailio uac module. Please try to configure the same settings with kamailio uac module to check if there is a bug in our implementation.

Do not open a bug report unless you've proof there is a bug in the software.

Regards

**Comment by rccess** [comment]
thanks for your reply

i have configured with all possible options and it is always getting timeout 

is there any timeout defined in ivoz for sip trunk registry ?

**Comment by Kaian** [comment]
Nope as far as I know.

In order to use ivozprovider you require knowledge in kamailio, asterisk, SIP, capture tools and so on.

Check the REGISTER message sent by kamailio and the one sent by asterisk to discover what is misconfigured.

Regards

**Comment by rccess** [comment]
thanks for your reply 

actually i have enough experience in kamailio , asterisk , sip but concern is that i can trace the issue with with kamailio but you replace the kamailio console thats why facing such issue to trace 
no kamailio debug command working on the server with ivoz
-------------------------------------------------------------------------
root@vdserver.telcob.live:~# kamctl
Disabled by IvozProvider, use systemctl instead, please
root@vdserver.telcob.live:~#
----------------------------------------------------------------------

**Comment by Kaian** [comment]
There can be two proxies in the same machine, each one with its own socket.

If you want to query module information use `kamcmd-proxyusers` and `kamcmd-proxytrunks` commands.

You can also update kamctl script to work with trunks proxy in order to debug it.

Regards
