### ISSUE TITLE
calls dropping after one call 

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1071]
Hello all,

1st call placing successfully, after 1st , 2nd call giving the error of ERROR: [1f4bcb53] SELECT-NEXT-GW: NO next GW, send 503 No gateways

once restart trunks service , call connecting again , after place one call , same issue repeating 

![image](https://user-images.githubusercontent.com/32220165/61192548-bca84c80-a6d2-11e9-9e72-e888f7f5c241.png)

please advise 

thanks

**Comment by Kaian** [comment]
Please, dont provide logs in images.

According to the screenshot, the carrier '2' is inactive because it failed to give response to the previous request. 

Provide the log from kamailio@trunks since start including both calls.

Regards

**Comment by rccess** [comment]
thanks for your reply

https://pastebin.com/8nANBqxM

here are the logs

**Comment by Kaian** [comment]
According to the logs:


/usr/sbin/kamailio[7459]: ERROR: [b4e098ef] MANAGE-FAILURE-GW: INVITE FAILED: '408 Request Timeout' to '8207 INVITE' from 'sip:+911413812100@127.0.0.1' (127.0.0.1:6060) [udp]

Jul 15 12:56:37 vdserver.telcob.live /usr/sbin/kamailio[7459]: WARNING: [b4e098ef] MANAGE-FAILURE-GW: 408: Inactivate carrier '2' (no reply received)

Jul 15 12:56:37 vdserver.telcob.live /usr/sbin/kamailio[7459]: INFO: [b4e098ef] MANAGE-FAILURE-GW: Failure using carrier '2' to place a call (reply code: 408)


This says that the request in your carrier has no response. Check using sngrep or other capture tool and provide both logs and pcap (no screenshot) if its answering all requests.

IvozProvider disables carriers that do not answer to request or answer with unexpected errors (like internal error). Then it starts sending them OPTIONS until the carrier answers again, re-enabling them.

Regards

**Comment by Kaian** [comment]
You can zip multiple files to attach them to github issues

**Comment by rccess** [comment]
Thanks for your reply

Please find the attachment of sngrep and logs

[sngrep.xlsx](https://github.com/irontec/ivozprovider/files/3391313/sngrep.xlsx)
[trunks-logs.txt](https://github.com/irontec/ivozprovider/files/3391314/trunks-logs.txt)

**Comment by rccess** [comment]
one more thing i noticed that , sip request getting 404 not found 

--------------------------------------------------------------------------------
root@vdserver.telcob.live:~# sipsak -v -s sip:10.237.252.225
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 43.231.124.208:35995;received=10.17.118.25;rport=43112;branch=z9hG4bK.0c61b4a7;alias
To: <sip:10.237.252.225>;tag=46efd1da2206ec9e-1056315145a0b2a-cbsxz
From: <sip:sipsak@43.231.124.208:35995>;tag=61f09b7
Call-ID: 102697399@43.231.124.208
CSeq: 1 OPTIONS
Max-Forwards: 70
Contact: <sip:sipsak@43.231.124.208:35995>
User-Agent: sipsak 0.9.7pre
X-ZTE-Cause: "B200-146433-1-2"
Allow: INVITE,CANCEL,BYE,ACK,REGISTER,OPTIONS,PRACK,INFO,REFER,SUBSCRIBE,NOTIFY,MESSAGE,UPDATE,PUBLISH
Accept: text/plain
Content-Length: 0

___________________________________________________________________________

**Comment by Kaian** [comment]
The most popular format for network capture is PCAP. Sngrep is able to save to pcap by pressing _S_ keybinding on a call or call flow. You're searching for two consecutive calls, one successfull and one failing.

The kamailio logs only has a single call, so it's not valid to debug this. 
What is more, the call in the log is a bounced call (you're calling to one of the provider DDIs) so the call is not actually reaching the carrier because the destination is inside provider.

Regards

**Comment by rccess** [comment]
[myport.zip](https://github.com/irontec/ivozprovider/files/3391612/myport.zip)

here is the pcap file 

https://www.dropbox.com/s/xm11qy4my8bkh4v/myport.zip?dl=0

**Comment by Kaian** [comment]
The pcap contains an outgoing call from Bob to users kamailio (i guess that's 43.231.124.208). No failing call there. Also no proxytrunks data in the pcap file (that is the proxy you're trying to debug). Attached data does not prove any bug in the software.

According to  logs in previous notes, the implemented logic to disable a Carrier is working: If a previous request has failed, the Carrier is disabled until it responds to an OPTIONS message generated by kamailio.

Regards

**Comment by zeba121** [comment]
calls forwards are dropping with internal server error

![image](https://user-images.githubusercontent.com/46315368/61275274-3facce00-a7cb-11e9-8e74-39ebe9d2ecbf.png)

Pcap file is attaching

https://filebin.net/2wcfb78srdtsl54d

**Comment by Kaian** [comment]
Hi @zeba121 or @rccess or @Infoworlds

The zip you attached contains 393 dialogs including 86 calls. We're not debugging all that unless you've a real proof that the platform has a bug, with a minimal dataset to reproduce the problem. 

Please, avoid opening an issue for each thing that doesn't work to you, unless you're totally sure it's a software flaw and not a problem that only applies to you.

Best regards,

**Comment by rccess** [comment]
zeba pointed out the particular which is dropping in the platform side with 500 server internal error

we gave you pcap file  because you can check the call flow for forwarding and dropping issue concern

we are avoiding the open an issue until we havn't find any clue in past posted issues and not able to trace any particular log for the same

**Comment by Kaian** [comment]
This issue states the following: After the first call the following calls are being dropped. 

Most of the platforms we have installed are able to place two calls (and even more!). So, if you want to prove something is wrong you must strive to get two calls that prove the issue information. You have provided a pcap with 86 calls (and more than 250 dialogs with registrations, notifies and so on).

Unless you have a explicit minimal testcase for this, I can not consider it a serious problem as we can not reproduce it in any way.

**Comment by rccess** [comment]
@Kaian 

Thanks for your reply 

after some research , we found some conclusion that 

the problem arise due to private IPs 

i talked to my voip provider >> they guided that we are using private ip and it is behind NAT without authentication required 

i have configured NAT setting in PJSIP like this 

--------------------------------------------------------------------------------------------
[transport-udp]
type=transport
protocol=udp
bind=127.0.0.1:6060
external_media_address=10.237.252.225
external_signaling_address=10.237.252.225
local_net=43.231.124.208/24
------------------------------------------------------------------------------------------
and tried to send request with sipsak 

result was 
-----------------------------------------------------------------------------------
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 43.231.124.208:33017;received=10.17.118.25;rport=44137;branch=z9hG4bK.5be34c31;alias
To: <sip:10.237.252.225>;tag=641a9fde181fd746-6c3e2b34133d23d-cbsxz
From: <sip:sipsak@43.231.124.208:33017>;tag=171502cc
Call-ID: 387252940@43.231.124.208
CSeq: 1 OPTIONS
Max-Forwards: 70
Contact: <sip:sipsak@43.231.124.208:33017>
User-Agent: sipsak 0.9.7pre
X-ZTE-Cause: "B200-146433-1-2"
Allow: INVITE,CANCEL,BYE,ACK,REGISTER,OPTIONS,PRACK,INFO,REFER,SUBSCRIBE,NOTIFY,MESSAGE,UPDATE,PUBLISH
Accept: text/plain
Content-Length: 0
-------------------------------------------------------------------------------------

**Comment by Kaian** [comment]
You should not be behind NAT because both your kamailio proxies and rtpengine use public IPs that should be present in the box where you installed ivozprovider (without any cloud provider NAT in the middle) .

If that is not the case, most probably you will have lots of problems and IvozProvider will not work at all.

Good luck!

**Comment by rccess** [comment]
Hello @Kaian , 

i am looking for paid support , no one responded of mail which i sent to your commerical email id

please advice

thanks

**Comment by Kaian** [comment]
You should be more patient and wait for an answer.
Most people is on holidays during July.

Regards
