### ISSUE TITLE
Module Undefined Error

### ISSUE THREAD

**Issue by zeba121** [irontec/ivozprovider#1072]
Hello All,

When i am trying to access carrier in brand configuration it shows the following error:-

https://prnt.sc/of5vlt

Anyone can help me on this error.

Thanks In Advance

**Comment by Kaian** [comment]
Hi @zeba121 

Hmm, looks like a Balance field error. We should work around this to at least display the screen. There is a field in that screen that queries CGRateS to get the current Carrier balance. 

What version of IvozProvider are you using?

Regards

**Comment by zeba121** [comment]
hello @Kaian 

i am using Ivoz Provider version artemis 2.11.1

and here is the apache error logs:-
https://pastebin.com/GGi9wNPy

and here is the journalctl error logs:-
https://pastebin.com/D3u60BzE

**Comment by Kaian** [comment]
The journal logs seems incomplete.

maybe running `journalctl -b -p err` shows the error text

Regards

**Comment by zeba121** [comment]
Its Done.
Thank You for Your Quick Help @Kaian .

**Comment by Kaian** [comment]
Did you manage to solve the problem?
What was causing it?

Regards
