### ISSUE TITLE
inbound call issue in forward to extension number

### ISSUE THREAD

**Issue by zeba121** [irontec/ivozprovider#1073]
Hello @Kaian 

i have configured DDI provider successfully 

but when i am making the calls from my mobile to DDI numbers calls are forwarding to number , getting error with disconnecting call without forwarding

my call flow

**********************************************************************

_my mobile dialing <------>DDI Number <--------> IVR <------> forwarding to user extension <-----> extension number 

***********************************************************************
------------------------------------------------------------------------------------
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: INFO: [4820e5da] X-HEADERS-OTHER: 'X-Info-Record' header found, call will be recorded
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
Jul 15 18:14:03 abc.example.com /usr/sbin/kamailio[10572]: 

> ERROR: [4820e5da] X-HEADERS-OTHER: Invalid X-Info-Special value () for call without xcallid

________________________________________________________________________________

hoping the guidance to trace the same

Regards

**Comment by Kaian** [comment]
I don't see anything wrong in the attached logs.

Are you sure the platform is not placing the call to the user? Did you captured traffic with sngrep or other capture tool?.

Regards

**Comment by gil-obradors** [comment]
Hi @zeba121  !
We are testing Ivoz PBXs in my company, I can confirm IVR is working fine.

Maybe, you can enter to ast (asterisk) and see if Call arrives to asterisk or is losed before.

( I can talk for artemis 2.10-2.11)

**Comment by Kaian** [comment]
This has nothing to do with inbound call processing and IVRs.

The packets displayed shows the message: *No gateways*.
Check kamailio@trunks logs for detailed logs of why the calls can not be placed: 

 - There is no Outgoing Routing for that company and destination
 - All Carriers configured in outgoing routings has been deactived because it caused a previous error (like no response to our requests)
 
Either way, this is an enviroment issue and we don't offer support aside of our clients. Please read FAQ in the main project page for commercial support request.

Best regards

**Comment by rccess** [comment]
can we reactivate outgoing routes manually if they deactivated for previous error ?

is there any command or option for the same , since it is not defined in doc 

please advice
