### ISSUE TITLE
Catalan language support

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1074]
HI,
Only to inform to community that I'm going to translate the web admin portal ( po file) to Catalan language.

If anyone have started this job an can share all done work, would be fine :)

I'm going to follow https://github.com/irontec/ivozprovider/issues/1040#issuecomment-506787502

Thanks and best sips

**Comment by miquelinv** [comment]
If you want help with this translation I will be happy to help you.

contact me

**Comment by gil-obradors** [comment]
Hi!
I'm in 70%
I made the mistake to have referenced the translation with English file.
I think it could be better use the Spanish translation, so I think we will have to do a lot of corrections.
I will try to finish next days, and if you want We can review and test together.

Best sips

**Comment by Kaian** [comment]
2.12.0 release has all database and portal changes required to include the new strings for Catalan, so you can test the language file in the portal if you want.

web/admin directory contains a Makefile, just replace the ca_ES.po file in web/admin/application/languages directory and run `make update`. The changes should be visible in the administration portal.

Regards!

**Comment by gil-obradors** [comment]
Only to inform I have finished the work, 100% translated to ca_ES
I'm testing it now,  in few days I will send it with pull request

**Comment by Kaian** [comment]
Good news! Thanks a lot @gil-obradors :+1:

**Comment by gil-obradors** [comment]
@miquelinv I have pushed first version of CA.
Feel free to check and make changes on : 
https://github.com/gil-obradors/ivozprovider/blob/b611e5c693bfdeb3d2a788daeb927875ddf800f1/web/admin/application/languages/ca_ES/ca_ES.po

**Comment by Kaian** [comment]
Would you mind if we include current translation status in the next release and make corrections in following releases?

**Comment by gil-obradors** [comment]
Yes, tellme the last day for doing modifications , and I will push last version before

**Comment by Kaian** [comment]
Our idea is to include the translation files in 2.12.1 that we expect to close next Tuesday.

**Comment by gil-obradors** [comment]
Done in accordance  with https://www.softcatala.org/recursos/sc-glossary.html
