### ISSUE TITLE
CGrateS Service not getting up

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1075]
Hello All , 

There is one bug found in 2.11 , Cgrates are not getting up 

Already tried to restart redis server and followed by logs but no clue

![image](https://user-images.githubusercontent.com/32220165/61386586-2b9fc400-a8d2-11e9-8fab-cfb7f7f1b54b.png)

please advice

thanks

**Comment by cruzccl** [comment]
Hi @rccess,

As explained [here](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md#i-have-trouble-with-my-environment) this is not a support forum, please contact comercial@irontec.com to hire technical help.

Regards,

**Comment by rccess** [comment]
@cruzccl 

since it is reporting bugs , and it is opensource platform , i am not pointing anyone that you should come to help me ! it is open to all 

i am not forcing you to support me ! the same problem might be faced by others 

if you really don't want to help , leave the issue open , so anyone can help for the same 

for commercial support , i already dropped mail to comercial@irontec.com  before 7 days but no one came to me. no one on IRC to reply of messages 

if you will not help me at this stage , how i will move further to contribution for the project 

no one in this world come as expert by birth , people learn with time by facing the challenges

might be you spend more time on the same , but it is humanity if you can help others 

it was my last issue opened on this opensource platform, now i am exploring other similar opensource like eg: magnus billing and will spend time on other platforms and will contribute to them

thanks for closing my issue
