### ISSUE TITLE
How is BillableCalls filled

### ISSUE THREAD

**Issue by glacroix** [irontec/ivozprovider#1078]
Hello,
Trying to play with the CDR generation. It seems that BillableCalls is a kind of master tables for trunks CDRs. Yet, I was wondering  if the enpointType and endpointId columns are filled (they are not for all the in/out calls I have done) or if they are here for future use (or maybe I missed something :))

Thanks,
Guillaume

**Comment by Kaian** [comment]
Hi @glacroix 

Billable calls is a business table that is filled with the data of kam_trunks_cdrs (the CDR table for kamailio) and tp_cdrs (the CDR table for CGRateS).

This process is done by a microservice called cdr-mixer (check schedule microservice dir and [the service in charge](https://github.com/irontec/ivozprovider/blob/8cbaed8c3f3919b99e331b7d7edcb308743319db/library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromTrunksCdr.php))

The fields you mention are filled from kam_trunks_cdrs and if I remember correctly it's only implemented for Retail accounts right now.

Regards!

**Comment by Kaian** [comment]
This supports my previous statement, only RetailAccount is handled: https://github.com/irontec/ivozprovider/blob/ba69118da5ac53213ea4b1d12be3d7cc7b03b9dd/library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdr.php#L95

Regards!

**Comment by Kaian** [comment]
Feel free to reopen if you need further info ;-)
