### ISSUE TITLE
Create Google Group for Users questions

### ISSUE THREAD

**Issue by Kaian** [irontec/ivozprovider#1079]
Originally we had a mailing list for user questions, but that required some maintenance and received lots of spam, so we decided to close it on February.

We have decided to create a google groups so users can share their experiences there and leave Github issues for bug reports and project scheduling.

We don't plan to provide support there during our work hours, but anyone can provide feedback or help.
 
https://groups.google.com/forum/#!forum/ivozprovider-users

 We have to:

- [x] Edit main README contact section
- [x] Add entry in FAQ with the group link 
- [x] Add issue template to redirect user questions to the group
- [ ] Update minimal group configuration (welcome message, logo and so on)
- [ ] ...

**Comment by rccess** [comment]
Thanks for open a google group , it will really help everyone 

and even people like me with not post the issue here 🖌 

i simply move forward on the google group 

Thanks again

**Comment by Kaian** [comment]
You welcome, we'll try to redirect there all the questions not related with the software development.

There won't be much activity there since it's too new and the community is really small, but questions there can be open as long as the original poster wants.

We have to document it tho, so anyone new to the project is able to find it.

Regards

**Comment by rccess** [comment]
I have started there with opened the concern there , hope community seeing
there

**Comment by rccess** [comment]
google group still working ?
