### ISSUE TITLE
Extend Registrar Server Uri Value Limit

### ISSUE THREAD

**Issue by zeba121** [irontec/ivozprovider#1082]
Hello all,

I need To change the Character limit of registrar uri in DDIProvider Because my provider does not change the registration string.
here is my string value example:- 
+911400000000@india.aitel.com:abcdefg:+91140000000@india.aitel.com@xxx.xxx.xxx.xxx/+91140000000

i want to put this registration string value.

So i need to extend the character limit of registration uri value.

Thanks In Advance

**Comment by Kaian** [comment]
Hi @zeba121 

According to DDIProviderRegistrations table, username is 64 characters and domain is 190 characters.
We have no plans to increase that values, you can try playing with domain field or ask in the ivozprovider-users group.

Regards
