### ISSUE TITLE
asterisk 13.17.0 crashes on outbound incoming call

### ISSUE THREAD

**Issue by tchetagni** [irontec/ivozprovider#1088]
Hi,
I was able to install ivozprovider and setup successful outbound and inbound outgoing calls.
But when trying to receive outbound incoming call (pstn call), asterisk crashes and restart automatically, and call fails.
I have lost the complete stack trace, but I was able to remember the source:
stricmp() in libasteriskpj.so.2.

My asterisk version is 13.17.0 (and I presume pjsip is 2.6).
Is it possible to upgrade asterisk or pjsip in ivozprovider platform?

Do anyone encouters this issue??
Someone is able to successfully receive outbound incoming call (from pstn)?

Please help.
ESAIE

**Comment by Kaian** [comment]
Hi @tchetagni 

We have not experienced any crashes with this version of asterisk in more than two years (both oasis and artemis releases share the same asterisk), so not sure what the problem can be.

We ship asterisk 13.17.0 with some [custom patches](https://github.com/irontec/asterisk/tree/bleeding/debian/patches), so changing the version requires to adapt all of them. We don't plan to change asterisk version for artemis release yet.

The asterisk systemd unit file is configured to [generte coredumps](https://github.com/irontec/asterisk/blob/bleeding/debian/asterisk.service#L7). If you install _ivozprovider-asterisk-dbg_ package and configure your system to store coredumps in the filesystem, you can get a valid backtrace with gdb.

Regards!

**Comment by tchetagni** [comment]
Hi,
crash was due to presence of:
-(tel: instead of sip:) uri in from header
-(tel: instead of sip:) uri in to header
We fall back on artemis asterisk stable version.

**Comment by Kaian** [comment]
Good to know. Thanks for the feedback!
