### ISSUE TITLE
Control panel, sip domains not showed correctly

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1089]
### Description

Control panel -> SIP Domains  in English langage say 5
![imatge](https://user-images.githubusercontent.com/6016929/62123797-fed3af80-b2c8-11e9-9fa6-d6f2c2d6c527.png)

Control panel -> Sip Domains in Spanish Language says 125
![imatge](https://user-images.githubusercontent.com/6016929/62123760-ebc0df80-b2c8-11e9-8027-a569b543c6d1.png)

---

- IvozProvider version: 
ivozprovider-web-admin                        2.11~2.11.1~20190711.2151~8cf11ef+artemis all

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting

Entring God portal

### Additional Information

Like number five is writted by error

**Comment by mmadariaga** [comment]
Hi for reporting @gil-obradors,

It looks like it's a visual glitch that only happens when the text occupies the full column width.

**Comment by mmadariaga** [comment]
This was fixed at https://github.com/irontec/klearMatrix/commit/e0efa68ddd05fd884da296f5957ac74ae4fea9cd
