### ISSUE TITLE
Unable to read dtmf number in asterisk-certified-13.21 patched with custom patches 

### ISSUE THREAD

**Issue by tchetagni** [irontec/ivozprovider#1091]
Hi,
I have an issue in testing IVR.
I am using asterisk-certified-13.21 because artemis asterisk stable version crashes on my server when receiving an external call.
All direct calls are now working.
The issue is in IVR execution when receiving an external call. DTMF tones are not read.

I need help on this.

**Comment by Kaian** [comment]
Hi @tchetagni 

Sorry but we only provide support to bugs in the product that have been proved. Changing the version of asterisk makes this an enviroment problem (that only happens in your installation).

All the information that can I provide related to DTMFs and Ivozprovider: send them through RTCP. All endpoints in the solution are configured with dtmf_mode rfc4733.

Regards!

**Comment by tchetagni** [comment]
Hi,
I had fixed the crashing source in artemis asterisk version (it was tel: uri in from or to headers).
IVR is still not working with this stable version.
These are the shots.

![image](https://user-images.githubusercontent.com/39014342/62146900-43257680-b2ee-11e9-94f8-6c669099be72.png)
![gambar_nework_sangoma_pstn_asterisk](https://user-images.githubusercontent.com/39014342/62147387-5127c700-b2ef-11e9-81a3-df470000bd58.jpg)
![image_2019_07_30T16_18_08_883Z](https://user-images.githubusercontent.com/39014342/62147388-5127c700-b2ef-11e9-9661-208a4a5326d6.png)
![image_2019_07_30T16_19_02_657Z](https://user-images.githubusercontent.com/39014342/62147390-51c05d80-b2ef-11e9-8fb9-99cf3845b1bc.png)

**Comment by tchetagni** [comment]
![image_2019_07_30T16_20_55_288Z](https://user-images.githubusercontent.com/39014342/62147514-92b87200-b2ef-11e9-96fc-eace79b23c86.png)
