### ISSUE TITLE
Only one DDI is working in ddi list [client configuration]

### ISSUE THREAD

**Issue by tchetagni** [irontec/ivozprovider#1092]
Hi,
I have setup 2 ddi clients in ddi list [client configuration - menu].
1st ddi is attach to an IVR.
2nd ddi is attach to a User.
When I launch external call to each ddi client, call is always routed to first ddi (IVR).
I am using asterisk-certified-13.21 patched with Artemis custom patches.

Please, I need help.

**Comment by Kaian** [comment]
Hi @tchetagni ,

Please, use the issue templates format when creating new issues. Otherwise they will be closed without answer.

Please provide the asterisk CLI log of the call routed to the User. You can get them running `asterisk -rvvvvv` or `ast` alias in the shell.

Regards

**Comment by Kaian** [comment]
Closed due to not shiped asterisk version.
