### ISSUE TITLE
IVR is not accepting dtmf tones

### ISSUE THREAD

**Issue by tchetagni** [irontec/ivozprovider#1093]
### Description

Hi,
I have setup, IVR as a termination of ddi, to be able to process external incoming calls.
IVR has multiple options for navigation.
When I test this feature by an external call, IVR does not take any input DTMF.
How to get it works?
Need help please.

---

- IvozProvider version:  artemis 2.12

- Related sections: 
    - [X] SIP & Telephony
    - [X] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Additional Information

![image_2019_07_30T16_18_08_883Z](https://user-images.githubusercontent.com/39014342/62204175-921deb00-b384-11e9-82c7-24f3db02efd5.png)
![image_2019_07_30T16_19_02_657Z](https://user-images.githubusercontent.com/39014342/62204176-92b68180-b384-11e9-94ed-ffce9ba5963b.png)
![image_2019_07_30T16_20_55_288Z](https://user-images.githubusercontent.com/39014342/62204178-92b68180-b384-11e9-9fcb-88e1fdbc943a.png)

**Comment by Kaian** [comment]
Hi @tchetagni

This is not a support forum. To open an issue here you must have evidence that there's a bug in the software providing proofs.

You can try requesting help to other users in ivozprovider-user group or contact our commercial department.

As I mentioned in the other issue, be sure your ddi provider is sending dtmfs in RFC4733 , the only accepted format in ivozprovider.

Regards
