### ISSUE TITLE
Linking events to calendar doesn't work

### ISSUE THREAD

**Issue by rbetancor** [irontec/ivozprovider#1094]
### Description

When you try to add and event to a Calendar, like definig some holydays, it shows you ALL the time-definitios of all the companies, instead of only the time-definitions of the company you are working on.
Also all the locutions are shown, instead of only the locutions of the selected company.
Etheir way, no mater if you select the time-definition and locution of the selected company, the created evet never works.

---

- IvozProvider version: 2.11~2.11.0~20190625

- Related sections: 
    - [ ] SIP & Telephony
    - [X] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting

It could be reproduced easly, just create a time-definition for a vPBX, go to any other vPBX, create a calendar of events, and try to add an event, you will see on that page, that it show you all the time-defitions of any vPBX on the platform.

**Comment by Kaian** [comment]
Hi @rbetancor 

We have made a couple of fixes in the latest release, could you try updating to 2.11.2 and try again?

Thanks!

**Comment by rbetancor** [comment]
web/admin seems to work as expected on the 2.11.2 , have to finish some testing to be sure the filters works on the SIP part also.

Could you point me to the commit that fixed it?, I didn't find any commit with a comment related to this issue.

**Comment by Kaian** [comment]
Sure

729ffcdd7 - web/admin: fix locution and schedule filters for CalendarPeriods
91b9a9879 - core: trigger CalendarEvents also on startDate and endDate

**Comment by rbetancor** [comment]
Thanks, It's working now

**Comment by Kaian** [comment]
Good, thanks for the feedback
