### ISSUE TITLE
Enable missed calls on queue calls

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#1096]
Queue calls do not generate missed calls on called members' phones.

This issue aims to add a new selector in Queue configuration to change current behavior and make it as similar as possible to huntgroups' one:

- **Prevent missed calls**: Yes / No (default value, Yes).

  - Yes: current behavior, no missed calls are generated.
  - No: missed calls are generated in non-answering phones.

Only exception: when a member answers a RingAll queue call, no missed call is generated in remaining members (no matter the value of the new parameter).

**Comment by Kaian** [comment]
I think this was implemented in #1315
