### ISSUE TITLE
GL252 Move presence from AS to KamUsers

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#11]
Implies:

- Redesigning conference entry mechanism.

- Redesign call-limit (now in KamUsers).

**Comment by cruzccl** [comment]
Available in bleeding branch 4b2d5e4639ece62a27ffc9f8d408307605048d18

**Comment by Kaian** [comment]
If we move to Asterisk 14, there's also the possibility to send presence notifications to kamailio.
This can be handy for conferences/custom hints in asterisk.

https://wiki.asterisk.org/wiki/display/AST/Publishing+Extension+State
