### ISSUE TITLE
delete voice messages

### ISSUE THREAD

**Issue by miquelinv** [irontec/ivozprovider#1104]
Hi,

When voice messages are sent by mail to the user, they remain in the mailbox as new messages.

Is there a way to delete them without having to access the mailbox through a call, since you have to delete them one by one?

A good option would be to add a check in the user's voice mailbox settings to define whether messages are to be deleted once they have been sent.

Another option would be that from the panel of each user you could access a list of your voice messages.

**Comment by Kaian** [comment]
Hi,

> Is there a way to delete them without having to access the mailbox through a call, since you have to delete them one by one?

No, it's not possible right now.

> A good option would be to add a check in the user's voice mailbox settings to define whether messages are to be deleted once they have been sent.
> Another option would be that from the panel of each user you could access a list of your voice messages.

Both approaches require database persistence of Voicemail messages, currently there are plans to implement it.

Please, try to use Github Issue templates, otherwise they may end closed unanswered.

Regards!
