### ISSUE TITLE
Create DDI to retail company

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1105]
### Description

I'm trying to create a DDi to Retail account.
---

- IvozProvider version: 
ivozprovider-web-rest                         2.11~2.11.1~20190711.2151~8cf11ef+artemis all          IVOZ Provider - Rest API files

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [X] API
    - [ ] Other

### Troubleshooting

API return status code 201 on registring new DDi to retail acount. But not usable

Log:
```
Aug 17 02:00:45 ivozprovider-standalone changelog[32659]: changelog.INFO: CommandWasExecuted > API::post(["Ivoz\\Provider\\Domain\\Model\\Ddi\\Ddi","application\/json","api_ddis_post_collection",{"company":"808","ddi":"931212121","brand":2,"country":70,"ddiProvider":null}]) [] []
Aug 17 02:00:45 ivozprovider-standalone changelog[32659]: changelog.INFO: EntityWasCreated > Ivoz\Provider\Domain\Model\Ddi\Ddi#755 > {"Ddi":"931212121","DdiE164":"+34931212121","recordCalls":"none","billInboundCalls":false,"companyId":808,"brandId":2,"countryId":70,"id":755} [] []
```
All seems ok, but DDi is listed on Brand DDI view list, but not in DDI-client view.
I take a look into DB and see that for this kind of company needs routeType, and retailAccountId. 
From API unable to put this attributes

### Additional Information

 I have seen that isn't possible to route DDI like retail or residential accounts from API, only assign DDI. Is this expected or may be in the TODO?

Again, thank you!

**Comment by mmadariaga** [comment]
Hi @gil-obradors,

DDI management is splitted between brand and client APIs. You can set both routeType and retailAccount from https://you-client-portal/api/client/ddis/{id} [PUT].

About the DDI not being listed in client web portal, that's a bug that was recently fixed [here](https://github.com/irontec/ivozprovider/commit/6f85607bc3aa53c47583f31bb456a801f7f8c010).

Let us know if you have any further issues

**Comment by gil-obradors** [comment]
Ouh, yes
I have issues changing ddi resource, I'm going to report

Thanks!
