### ISSUE TITLE
List CSV Sheduler at webadmin not seeing correctly calldirection

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1129]
### Description

Inside  Brand - Calls - CSV Sheduler.  You create a sheduler but you can't see what you selected in call directions.
However this field is operative, it works fine with both and outbound. The CSV is correctly generated. Only showing the entry.

---

- IvozProvider version: 
`2.11~2.11.1~20190711.2151~8cf11ef+artemis`
and
`2.12~2.12.0~20190829.2206~e6f80a8+artemis`

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [x] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting

The problem is that BOTH set a null field into db, and when reads it, return null
I have search but I don't know how to say when it's null return 'both'
### Additional Information

May be for here:
https://github.com/irontec/ivozprovider/blob/bd6f87acdf19fca9ebd82b0d5b7e058e9a03feca/library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php#L8

https://github.com/irontec/ivozprovider/blob/bd6f87acdf19fca9ebd82b0d5b7e058e9a03feca/library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php#L361

![imatge](https://user-images.githubusercontent.com/6016929/64941696-9edc9c80-d867-11e9-9981-a101ee78f6c0.png)

**Comment by mmadariaga** [comment]
Hi @gil-obradors,

We've just fixed it [here](https://github.com/irontec/ivozprovider/commit/085026e838d41c740e20833071cb9433714bdbcc). Thanks for reporting :)
