### ISSUE TITLE
Catalan sounds and locutions

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1131]
### Description

Asterisk sounds and locutions in Catalan
---

- I'm willing to: 

 - [x] Implement this feature myself
 - [ ] Pay to priorize this new feature

### Additional Information

I have search some info:

-http://veu-ip.cat/descarregues/veus-ca/130-down-12.html : From 2011, locutions for asterisk 1.2, may be I can use some of them. But I think It's better use the same voice for all. Not mixing. However I'm trying to get contact with this group, in case they can help me.

-https://www.sinologic.net/2010-08/como-convertir-audio-con-sox-compatible-con-asterisk.html: I understand only need to create WAV files, mono is enough, min rate 8000 Hz, 8 bits. I'm going to search a [good microphone](https://www.amazon.es/dp/B06XNQVCKG/ref=sspa_dk_detail_0?psc=1&pd_rd_i=B06XNQVCKG&pd_rd_w=ARtV5&pf_rd_p=f0815c89-d195-4bd5-89fe-99dc61984993&pd_rd_wg=sX6RP&pf_rd_r=FP8YJB129H1V53MMAJGV&pd_rd_r=f154571e-e3f1-49e2-ba79-1a5ac8e0c0e3&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzSVNVNk42STJCQk1MJmVuY3J5cHRlZElkPUEwNjAwMzE1MU9HSlcxVjI4MVhLWSZlbmNyeXB0ZWRBZElkPUEwNjYyMDQ0MUlZQkxSMUZEVkExNiZ3aWRnZXROYW1lPXNwX2RldGFpbCZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=l) or external recorder...

-I have done some test with Audacity, it has de possibility to apply noise reduction , so it reduces a lot the noise, I think that is what marks the most quality ( no noise)

-I've seen in /var/lib/sound/en there is 354 alaw files,   and in ../es/ 1307 files.
There's a folder inside that name's ivozprovider. 
What should I transalte?  I imagine taking the Spanish would be more complete, and sub-folder too.

The idea would be to write down all the sentences in a list for then record it continuously  to have the same intonation. And then edit them with Audacity

suggestions, ideas, recommendations are welcome !

best sips

**Comment by Kaian** [comment]
Hi @gil-obradors 

> I understand only need to create WAV files, mono is enough, min rate 8000 Hz, 8 bits.

We currently ship sounds in alaw and g729. Those are the most common used codecs in our environments, so we avoid the encoding process by providing the sound already encoded. To create specific sounds for each codec we use `file convert` asterisk CLI command, available in res_convert module.

```
# asterisk -rx 'module load res_convert.so'
# asterisk -rx 'file convert /tmp/orig_file.wav /tmp/encoded_file.alaw'
# asterisk -rx 'file convert /tmp/orig_file.wav /tmp/encoded_file.g729'
```

For g729 sounds, you also need to load _codec_g729_ module. We don't ship that module, but you can get it from [here](http://asterisk.hosting.lv/) for all asterisk versions.
We usually do some scripting for encoding this way :)

>-I've seen in /var/lib/sound/en there is 354 alaw files, and in ../es/ 1307 files.

English sounds are the ones provided by asterisk (aterisk-core-sounds), while spanish ones contains core sounds and lots of extra sounds. According to https://github.com/irontec/asterisk-sounds/commit/a1a8ba0197b0ba43ec9ca713516e77f53fcdde6e those sounds were taken from [voipnotavos](https://www.sinologic.net/proyectos/vocesbak/).

> What should I transalte? I imagine taking the Spanish would be more complete, and sub-folder too.

We don't actually know exactly what sounds are used (not all of them, for sure). Based on asterisk's applications in use, I would say voicemail and queue notifications and base digits.

> There's a folder inside that name's ivozprovider.

Those are our custom project louctions. Features, like Routing Locks or recording instructions sounds are placed there and are used somewhere in the logic.

---

That said, some of our clients have catalan sounds recorded in studio, and we're trying to convince them to allow us to publish them as part of the project, but that's their decission.

**Comment by gil-obradors** [comment]
If you think it's okay, I will try to do some recordings ( digits and something else).
For me, I'm only worried about background noise. But I have friends who are dedicated to the world of music recording, let's try.


I would publish them so that we value their quality. If the community says ok, I go ahead with the rest.

If it doesn't meet minimums, the attempt will have been fun :)

**Comment by Kaian** [comment]
Any news on this?

Thanks!

**Comment by gil-obradors** [comment]
overloaded, but  before my dead I will do something related ;)

**Comment by gil-obradors** [comment]
ah...Azure cognitive services to a text-to-speach voices ( with catalan) that seems pseudo-perfect!!
