### ISSUE TITLE
Artemis Distributed Installation Issues

### ISSUE THREAD

**Issue by rkm7232** [irontec/ivozprovider#1180]
Recently I have installed ivozprovider distributed packages. Here are some issues I encountered:

### Data Profile:
**1.** redis protected mode is on, so every packet from other locations (except 127.0.0.1) are blocked and CGRates cannot start. This is CGRates output:
```
CGRateS <cc83db6> [1448]: Could not configure dataDb: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside. exiting!
```

### Proxy Profile:
**2.** After disabling Redis protected mode, when I started CGRates I get the following error:
```
CGRateS <88c9874> [1779]: Could not configure dataDb: dial tcp 127.0.0.1:6379: getsockopt: connection refused exiting!
```
And here is cgrates.json, data db section:
```
 "data_db": {
                "db_type": "redis",
                "db_host": "data.ivozprovider.local",
                "db_port": 26379,
                "db_name": "10",
                "db_user": "cgrates",
                "db_password": "",
                "redis_sentinel": "mymaster"
        },
```
I don't know why cgrates keeping default configuration for data db...

**3.** In kamailio@trunks config, ports are 5060

**4.** kamailio services didn't enabled in systemd

**5.** In my tests for outgoing call, trunks proxy was unable to load gateways [load_gws from lcr module] with defined prefix.

### Application Server & Portal Profile:
**6.** Locutions uploaded on wep portal profile, They needed on application servers too.

---

- IvozProvider version: latest artemis distributed packages

- Related sections: 
    - [X] SIP & Telephony
    - [X] vPBX Functionalities
    - [X] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
install artemis distributed packages on 4 virtual machines

**Comment by rkm7232** [comment]
### Portal Profile
After adding brands:
```
 workers.ERROR: [KAM-RPC] Unable to send request domain.reload to server proxyusers [127.0.0.1:8000]: cURL error 7: Failed to connect to 127.0.0.1 port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []
```

**Comment by Kaian** [comment]
Hi @rkm7232 

Currently distributed installation are not documented. Packages are not designed to work in distributed mode as-is and require additional software (for clustering, distributed storage, database replication and so on).

FAQ has an entry on this topic [here](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md#i-have-tested-standalone-how-can-i-install-a-distributed-installation)

You can also find further information in #271 

I would recommend to share your findings in [ivozprovider users group](https://groups.google.com/forum/#!forum/ivozprovider-users) and maybe other users can provide some light. Of course, like FAQ mentions, you can try contacting our commercial team for further support.

Regards
