### ISSUE TITLE
When will artemis be feature frozen?

### ISSUE THREAD

**Issue by sdwru** [irontec/ivozprovider#1233]
We have been waiting for Artemis to be considered stable or at least feature frozen before getting more involved.  Do you guys have any idea if/when that day may come?

**Comment by Kaian** [comment]
Hi @sdwru 

The answer to this is more or less the same in #1061 

We wil try to start a new major release with the newest features in the following months, but meanwhile artemis will receive fixes and all features anyone is willing to pay. We'll move it to stable as soon as we have a 3.x release. 

Regards!

**Comment by sdwru** [comment]
Does that mean Artemis is feature frozen?  When I had a look at it before I sort of gave up because you guys were adding and removing things, moving things around etc. so it was too much of a moving target to spend too much time on.

The reason I ask is because I would most likely be doing some customization.  So it helps to have a base system that does not change much other than bug and security fixes.  Adding new features is usually not a problem either.

**Comment by Kaian** [comment]
The core of the solution won't change too much, but our clients still require some features that will be included in artemis. New endpoints or small changes in API will appear, but at this stage of the development we don't plan any big change.

There is no ETA for new release nor marking artemis stable, so small features will be implemented as long as someone is interested in paying for them. 

Regatds!
