### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by giandiego** [irontec/ivozprovider#1306]
Hi forget the password, how can I reset the administrator password from mysql

**Comment by gil-obradors** [comment]
Hi @giandiego , I think it could be better to ask to appropriated channels :  https://github.com/irontec/ivozprovider#feedback--questions

Here you can found install data for admin user, changeme password. If you are asking for portal reset password
https://github.com/irontec/ivozprovider/blob/a41e7540de5de9754c1914c0bcddb1a504558dae/schema/initial.sql#L53


See you

**Comment by Kaian** [comment]
Please, use provided issue templates.
