### ISSUE TITLE
web/rest: expose Company.MaxDailyUsage in Brand API

### ISSUE THREAD

**Issue by Kaian** [irontec/ivozprovider#1309]
### Description
Afaik, this field should be available to Brand Administrators through their Company API endpoint.

---

- IvozProvider version: 

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [X] API
    - [ ] Other

**Comment by cruzccl** [comment]
Fixed in #1318
