### ISSUE TITLE
Login error after update from Artemis 2.9 to 2.15

### ISSUE THREAD

**Issue by 3p1v0z** [irontec/ivozprovider#1369]
### Description

Hi.
I've  Artemis 2.9 working correctly.
After finalising command "apt-get dist-upgrade" and restart, cannot login panel and show error:

_"[Semantical Error] line 0, col 184 near 'restricted =': Error: Class Ivoz\Provider\Domain\Model\Administrator\Administrator has no field or association named restricted"_
And cannot login at panel.
Console migrations show correct,
¿?
there are a special procedure for update from previous versión?
Thks,

- IvozProvider version: 2.15~2.15.0~2020041
(IvozProvider from version:  2.9~2.9.3~2019031)

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [] Other

**Comment by mmadariaga** [comment]
It might be a cache issue, try `rm -fr /opt/irontec/ivozprovider/web/rest/platform/var/cache/prod/*`

If that solves the issue you should the clear cache of every app. Checkthis script out: https://github.com/irontec/ivozprovider/blob/bleeding/library/bin/cache-rm

Hope it helps

**Comment by 3p1v0z** [comment]
Hi,
This worked!
Thanks you
