### ISSUE TITLE
Caller Name from Twilio is missing

### ISSUE THREAD

**Issue by afernandez2000** [irontec/ivozprovider#1374]
### Description
I activate the CNAM lookup in twilio and twilio is sending the Caller ID and Name in PAI, From and Contact but somehow the Caller Name is removed and terminals only receive the CallerID number.

---

- IvozProvider version: 1.7.0~20180404.1330~632c4af+oas

- Related sections: 
    - [X] SIP & Telephony
    - [X] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
PCAP File

[capture.zip](https://github.com/irontec/ivozprovider/files/4520215/capture.zip)

**Comment by Kaian** [comment]
Hi @afernandez2000 

If this is an incoming external call to the terminal (From KamTrunks to Asterisk to KamUsers), this is something that also will happen in artemis release.
 
Sadly, this is a limitation done on purpose for all incoming calls that reach Asterisk: we remove presentation and diversion information. This keeps some problems away and the CallerIdNum was usually enough for external calls identification.

You can try to change this logic here:
https://github.com/irontec/ivozprovider/blob/oasis/asterisk/agi/library/Agi/Action/DDIAction.php#L79-L84

Removing the else block may keep the original CallerName for the outgoing second leg.

For now, we prefer to keep the logic as is by only displaying incoming external numbers, but feel free to give it a try.

Thanks for reporting!
