### ISSUE TITLE
T.38 Negotiation Failed

### ISSUE THREAD

**Issue by rkm7232** [irontec/ivozprovider#1379]
### Description
Hi
When I trying to send a fax, I facing with the following error:

```
> [b3][faxout22] [FaxSendStatus.php:75     ] AGI Error ("Local/29700698@faxes-00000037;1", "Error sending fax: error negotiating T.38 (T38_NEG_ERROR)")
```

And when I receive a fax it appears in incomming files but status is "Error"

- IvozProvider version: 2.15

- Related sections: 
    - [X] SIP & Telephony
    - [X] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Just created a fax in vpbx, and tested send and receive fax functionality.

**Comment by Kaian** [comment]
Hi @rkm7232 

This usually means your carrier does not support T.38 protocol and can not be used for sending or receiving faxes in IvozProvider. You should make network captures to check the SIP dialog. There should be an initial negociation followed by a switch to T.38 in SDP contents.

With the information provided, this is more likely an environment problem related to your Carriers or DDIProviders than a bug in ivozprovider, so we can not provide further assistance.

Regards!
