### ISSUE TITLE
How to make a full backup?

### ISSUE THREAD

**Issue by prodh971** [irontec/ivozprovider#1381]
I have been using Ivoz for a few months and I would like to know how to make a good backup and also a way to restore it in case of problems please

**Comment by Kaian** [comment]
Hi @prodh971 

We use VMs for most environments so we backup and restore the whole system.

Persistent data in the solution is located in:

- MySQL
- Redis 
- File Storage (/opt/irontec/ivozprovider/storage) 

As mentioned before, we dont backup individual services data, so we can't help you too much here. Try asking in [users-group](https://groups.google.com/forum/#!forum/ivozprovider-users), maybe someone can share its actual methods.

Regards
