### ISSUE TITLE
FreePBX SIP trunk to Ivoz Standalone Retail account, no working

### ISSUE THREAD

**Issue by ajpetidier** [irontec/ivozprovider#1399]
Hello,

We have a FreePBx system and we are interesting in connect with IVOZ via SIP trunk and Retail accounts,

Always the same error in IVOZ: SIP/2.0 407 Proxy Authentication Required.

Asterisk SIP trunk configuration:
secret=xxxxx
type=friend
host=IVOZ.IP
context=from-internal
disallow=all
allow=alaw
defaultuser=RetailIVoz
fromuser=RetailIVoz
fromdomain=IVOZ.IP
insecure=port,invite
qualify=yes
sendrpid=pai
trustrpid=yes
canreinvite=no
send_pai=yes

Can you help me about this?

**Comment by Kaian** [comment]
Hi,

We don't solve environment related issues in GitHub. 

In the future, also try to use issue templates or they will be closed unanswered.

I've seen you've opened also a message in the User group. Other users may share their experiences there if they have the time.

https://groups.google.com/forum/#!topic/ivozprovider-users/G9eG3f3_tp8

Regards
