### ISSUE TITLE
Rate destination name field not populated for Italian and Català when importing rates from CSV

### ISSUE THREAD

**Issue by nitefood** [irontec/ivozprovider#1403]
### Description

When importing rates from a CSV file, the "Destination Name" field is only populated for Spanish and English languages.

---

- IvozProvider version: `2.15~2.15.1~20200528.2756~7a9`

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [X] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Reproducible by importing a CSV rate file and navigating to `Brand Configuration` -> `Billing` -> `Destinations`, the _Name_ column will be empty for Italian and Català translations.

### Additional Information
Problem appears to be here:

https://github.com/irontec/ivozprovider/blob/b62e94fbf68e5b70f4e22bdd6c0620bb9a0ec45e/library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DestinationDoctrineRepository.php#L39

This statement updates rate destination names only for two (_en_ and _es_) of the four possible localizations.

**Comment by mmadariaga** [comment]
Thanks for reporting :)
