### ISSUE TITLE
How to Rebuild Admin UI  after Adding New field 

### ISSUE THREAD

**Issue by maruqmch** [irontec/ivozprovider#1433]
I added a new field into the brand table by editing the brand abstract orm file and use the console doctrine migration command to apply changes and rebuild the code using run-generator command.  

please guide how can I re-build UI code, I check the documentation of klear framework, but unable to find any file in the current source which rebuilds the UI,  please guide how can I set up dev environment for admin development. 

thanks

**Comment by mmadariaga** [comment]
Hi @maruqmch,

Please use issue template next time.

About your question, there is not automated tool to rebouild UI config. I suggest you to find a model that has a similar field in web/admin/application/configs/klear/model/*.yaml. Copy & Paste it in your model, change the name, etc. It should be enough.

Hope it helps

**Comment by maruqmch** [comment]
Hi @mmadariaga  thank you for your comment, I edit model *.yaml file as you mentioned, field show on screen, but  set value is not saving into DB, form is submitted without error.  

Please put further light on it.

Thanks

**Comment by mmadariaga** [comment]
That's weird. Does the attribute in klear yaml match de one in the orm?

You can find a lot of examples in merged PRs (https://github.com/irontec/ivozprovider/pull/1166/commits for instance). The steps are:
- Define the field in the orm and create the migration (https://github.com/irontec/ivozprovider/pull/1166/commits/fb4ea242cc96b666bcfde6ef8e56403b21d96933)
- Regenerate entities (https://github.com/irontec/ivozprovider/pull/1166/commits/a2bde850609522a74f153537b2824da11a544b12)
- Set the field on klear yamls (https://github.com/irontec/ivozprovider/pull/1166/commits/adb9373d6bf465358f51b2d9420c38b1e69a71a9#diff-4d582310d4d6072428f5d009a5876222R121)

Make sure the attribute on orm and klear have the same name. Remove caches in web/rest/platform/var/cache al well, just in case.
