### ISSUE TITLE
Logo Upload it's not working on artemis 2.15 at any Portal level

### ISSUE THREAD

**Issue by dsmaldone** [irontec/ivozprovider#1451]
I tried at every level to Upload a logo for a brand/company portal, but klear is always returning "Undefined error"

**Comment by Kaian** [comment]
Hi @dsmaldone !

It sounds like a storage problem, try `chmod -R 777 /opt/irontec/ivozprovider/storage/`.

Also, check journal errors with `journalctl -f` while uploading a logo. 

You can enable debug mode in portal changing `prod` with `dev` in /opt/irontec/ivozprovider/web/admin/public/index.php but performance will be very bad so do it only for debugging.

And try to use provided templates for Github Issues!

Regards

**Comment by dsmaldone** [comment]
Hi again

`journactl -f` showed

`Jul 02 17:18:34 ex01 klear[3647]: Exception captured [500]: Could not create dir //opt/irontec/ivozprovider/storage/ivozprovider_model_brandurls.logo (0) # /opt/irontec/ivozprovider/library/vendor/irontec/ivoz-core/Domain/Service/TempFile.php (120)`

so was a permission issue. I was on a fresh installation, so I was not expecting something like this. Anyway, thank you for the very quick feedback!

About "And try to use provided templates for Github Issues!" would you be so kind to point me to the related docs? I'm not a real expert of GitHub but I can improve as I like to follow the rules!

**Comment by dsmaldone** [comment]
This is not a real issue, but better to check in the deployment script to avoid further similar requests

**Comment by Kaian** [comment]
Will do!!

About the Issue templates: When you click on the new issue button in github there should be two choices: one for Bug Reports and one for Feature requests.

![](https://i.imgur.com/KDwZI0F.png)

If you click one, there editor comes with a template that you can fill with your problem data.

You can add a description in the Description section and mark with an *X* the boxes you think are related. There is a section to enter ivozprovider version too!

![imagen](https://user-images.githubusercontent.com/800069/86378147-9c79f080-bc89-11ea-8013-9830dbc0a44f.png)


Best Regards!

**Comment by dsmaldone** [comment]
Great! Thanks

**Comment by Kaian** [comment]
Problem introduced in https://github.com/irontec/ivozprovider/commit/2bf572708ab27dac3bb682ef3859f743330e9807#diff-c77824d83e0ee00cecc3a2606497479e
