### ISSUE TITLE
outgoing DDI

### ISSUE THREAD

**Issue by udee297** [irontec/ivozprovider#1469]
- IvozProvider version: standalone oasis

- Related sections: 
    - [x] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

after add peering contracts from other trunk provider, i cant call external because i dont have DDI number ,im using random DDI from trunk provider

MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] Executing [62217657525@users:1] ESC[1;34mNoOpESC[0m("ESC[1;34mPJSIP/b1c1t2_bob-00000026ESC[0m", "ESC[1;34mOutgoing call from user "Bob Bobson" <102> to 62217657525ESC[0m") in new stack
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] Executing [62217657525@users:2] ESC[1;36mAGIESC[0m("ESC[1;35mPJSIP/b1c1t2_bob-00000026ESC[0m", "ESC[1;35magi://127.0.0.1:4573/cli.php?model=default/calls/usersESC[0m") in new stack
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [Wrapper.php:358          ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m_CALLER_TYPE = USERESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [Wrapper.php:359          ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m_CALLER_ID = 2
ESC[0;37m")ESC[0m
ESC[1;30m       > ESC[0m[b1][f0405163] [Wrapper.php:358          ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m_ORIGIN_TYPE = USERESC[0;37m")ESC[0m
ESC[1;30m       > ESC[0m[b1][f0405163] [Wrapper.php:359          ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m_ORIGIN_ID = 2ESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:137  ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m__COMPANYID = 1
ESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:140  ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m__CALL_TYPE = internalESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:143  ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35m__CALL_ID = PPqACNK1NlNQtN-_PG-J0g..ESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:146  ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35mCHANNEL(language) = enESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:147  ] ESC[0;36mAGI SetVarESC[0;37m("ESC[0;35mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;35mCHANNEL(musicclass) = defaultESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:164  ] ESC[0;93mAGI NoticeESC[0;37m("ESC[0;93mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;93mProcessing outgoing call from ESC[0;32mBob Bobson [user2]ESC[0;93m to number 62217657525ESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [CallsController.php:222  ] ESC[0;34mAGI VerbosESC[0;37m("ESC[0;34mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;34mNumber 62217657525 is handled as external number.ESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [ExternalUserCallAction:43] ESC[0;93mAGI NoticeESC[0;37m("ESC[0;93mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;93mProcessing External call from ESC[0;32mBob Bobson [user2]ESC[0;93m to 62217657525ESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m       > ESC[0m[b1][f0405163] [ExternalCallAction.php:59] ESC[0;34mAGI VerbosESC[0;37m("ESC[0;34mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;34mSkipping tarificate checking as Externally Rating will be usedESC[0;37m")ESC[0m
ESC[1;30m       > ESC[0m[b1][f0405163] [ExternalUserCallAction:84] ESC[0;31mAGI Error ESC[0;37m("ESC[0;31mPJSIP/b1c1t2_bob-00000026ESC[0;37m", "ESC[0;31mUser Bob [user2] has not OutgoingDDI configuredESC[0;37m")ESC[0m
^MESC[K199*CLI> ^MESC[0KESC[1;30m    -- ESC[0m<PJSIP/b1c1t2_bob-00000026>AGI Script agi://127.0.0.1:4573/cli.php?model=default/calls/users completed, returning 0
ESC[1;30m    -- ESC[0mAuto fallthrough, channel 'PJSIP/b1c1t2_bob-00000026' status is 'UNKNOWN'
^MESC[K199*CLI> 
Disconnected from Asterisk server
Asterisk cleanly ending (0).
Executing last minute cleanups

**Comment by gil-obradors** [comment]
I think this is the desired behaveour, almost in all acounts types less
...wholesales?


https://irontec.github.io/ivozprovider/en/getting_started/external_outgoing_calls/outgoing_ddi.html

https://irontec.github.io/ivozprovider/en/administration_portal/client/index.html

El dt., 28 de jul. 2020, 18:53, udee <notifications@github.com> va escriure:

**Comment by udee297** [comment]
What should u do if u dont have did provider? The client only do outgoing
calls and sometimes internal calls, no need for incoming calls from outside

**Comment by Kaian** [comment]
Hi @udee297 

All users require a DDI for placing outgoing calls. This number will be added as presentation in P-Asserted-Identity or Diversion headers to identify the caller and it's mandatory in IvozProvider. You can assign an OutgoingDDI in User or Company edit screen (for all users of the company)


DDI Providers are not required in order to create a DDI, its just an optional field, but take into account that if anyone in the platform calls the DDI number, the call will be routed internally not reaching any Carrier.

More information can be found in the links posted by @gil-obradors 

I recommend uisng users google group for questions and leave github issues for bug reports and feature requests.

Regards
