### ISSUE TITLE
Data exposure: full list of brand clients exposed within Client Portal

### ISSUE THREAD

**Issue by nitefood** [irontec/ivozprovider#1473]
### Description
The client portal exposes a full list of clients for the same brand in the _Call CSV Schedulers_ section.

---

- IvozProvider version: 2.15

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
In order to reproduce, I'll report the steps I did:

- created a client portal for brand _X_
- created a wholesale client
- created a client admin _Y_ for the wholesale client
- logged to the client portal using Y's credentials
- entered the _Calls -> Call CSV Schedulers_ menu
- clicked **Add Call CSV Schedulers**
- the _Client_ dropdown exposes a full list of brand X customers.

### Additional Information
My perception of the functionality is that the _Client_ dropdown shouldn't exists at all within this section, being the client admin tied to a single client.

**Comment by mmadariaga** [comment]
Hi @nitefood,

I comfirm the bug in v2.15.  It seems to be working properly in dev branch already (https://github.com/irontec/ivozprovider/pulls?q=is%3Apr+is%3Amerged+scheduler+milestone%3A2.16.0). 

I'll keep this issue open until v2.16 is released to ensure that no regression  occurs. Thanks for reporting

**Comment by mmadariaga** [comment]
Fixed in 2.16
