### ISSUE TITLE
Login error after upgrade: Unable to get API access token

### ISSUE THREAD

**Issue by 3p1v0z** [irontec/ivozprovider#1474]
Hi.
After upgrading Artemis 2.9 to last version, login to control panel as admin, show this error: _"Unable to get API access token"_
Restarted/shutdown vm, clear all var cache, upgrade several times from snapshot.... always same result.
Any idea??
Thank you 

- IvozProvider version:  2.15~2.15.2~202006

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [x] Web Interface
    - [ ] API
    - [ ] Other

**Comment by Kaian** [comment]
Hi @3p1v0z 

Could you check *journalctl -f* and _/var/log/apache/*.log_ files for error messages?

You can also try to regenare JWT key info with `/opt/irontec/ivozprovider/web/rest/platform/bin/generate-keys --initial`


Regards

**Comment by Kaian** [comment]
Any update on this?

**Comment by 3p1v0z** [comment]
Hi,
sorry for delay... on holidays.
it didn't work, I restored the vm and next weekend i'll try again.
curiously that already happened to me in another update moths ago, and after a while it solved itself ¿?
I will report the result...
thanks and regards

**Comment by 3p1v0z** [comment]
Hi,
sorry for delay
After last update 2.16,  delete cache and sugested "/opt/irontec/ivozprovider/web/rest/platform/bin/generate-keys --initial"
updgrade worked!!!
Thanks
