### ISSUE TITLE
Moving from Oasis to Artemis

### ISSUE THREAD

**Issue by amvidalrc** [irontec/ivozprovider#1481]
Hello. Sorry if the question has been already asked, but I can't really find it. We have an Oasis working distribution in a VM, as a productive machine. We want to know two things:

1º) Its possible to upgrade easily to Artemis? Or it's better to deploy a new machine? Is there any way to restore the DB from Oasis to Artemis?

2º) In oasis, if I execute apt list --upgradable i got a lot of updates. It's safe to update? Is there any systemctl/systemd command for stop all the irontec/voip procceses for safe update?

`Listando... Hecho
apache2/oldoldstable 2.4.10-10+deb8u16 amd64 [actualizable desde: 2.4.10-10+deb8u13]
apache2-bin/oldoldstable 2.4.10-10+deb8u16 amd64 [actualizable desde: 2.4.10-10+deb8u13]
apache2-data/oldoldstable 2.4.10-10+deb8u16 all [actualizable desde: 2.4.10-10+deb8u13]
apache2-utils/oldoldstable 2.4.10-10+deb8u16 amd64 [actualizable desde: 2.4.10-10+deb8u13]
apt/oldoldstable 1.0.9.8.6 amd64 [actualizable desde: 1.0.9.8.5]
apt-utils/oldoldstable 1.0.9.8.6 amd64 [actualizable desde: 1.0.9.8.5]
bind9/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
bind9utils/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
bzip2/oldoldstable 1.0.6-7+deb8u2 amd64 [actualizable desde: 1.0.6-7+b3]
cpio/oldoldstable 2.11+dfsg-4.1+deb8u2 amd64 [actualizable desde: 2.11+dfsg-4.1+deb8u1]
cracklib-runtime/oldoldstable 2.9.2-1+deb8u1 amd64 [actualizable desde: 2.9.2-1]
curl/oldoldstable 7.38.0-4+deb8u16 amd64 [actualizable desde: 7.38.0-4+deb8u14]
dbus/oldoldstable 1.8.22-0+deb8u3 amd64 [actualizable desde: 1.8.22-0+deb8u1]
dbus-x11/oldoldstable 1.8.22-0+deb8u3 amd64 [actualizable desde: 1.8.22-0+deb8u1]
e2fslibs/oldoldstable 1.42.12-2+deb8u2 amd64 [actualizable desde: 1.42.12-2+b1]
e2fsprogs/oldoldstable 1.42.12-2+deb8u2 amd64 [actualizable desde: 1.42.12-2+b1]
file/oldoldstable 1:5.22+15-2+deb8u7 amd64 [actualizable desde: 1:5.22+15-2+deb8u5]
ghostscript/oldoldstable 9.26a~dfsg-0+deb8u6 amd64 [actualizable desde: 9.26a~dfsg-0+deb8u1]
imagemagick-common/oldoldstable 8:6.8.9.9-5+deb8u19 all [actualizable desde: 8:6.8.9.9-5+deb8u15]
isc-dhcp-client/oldoldstable 4.3.1-6+deb8u4 amd64 [actualizable desde: 4.3.1-6+deb8u3]
isc-dhcp-common/oldoldstable 4.3.1-6+deb8u4 amd64 [actualizable desde: 4.3.1-6+deb8u3]
klear/desconocido 2.1.0~20200211.121~6a93e1b+chloe all [actualizable desde: 2.1.0~20171122.99~6a93e1b+chloe]
klear-matrix/desconocido 2.1.0~20200219.163~dece4d5+chloe all [actualizable desde: 2.1.0~20190320.120~b0decf8+chloe]
libapache2-mod-php5/oldoldstable 5.6.40+dfsg-0+deb8u12 amd64 [actualizable desde: 5.6.40+dfsg-0+deb8u2]
libapt-inst1.5/oldoldstable 1.0.9.8.6 amd64 [actualizable desde: 1.0.9.8.5]
libapt-pkg4.12/oldoldstable 1.0.9.8.6 amd64 [actualizable desde: 1.0.9.8.5]
libav-tools/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libavcodec56/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libavdevice55/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libavfilter5/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libavformat56/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libavresample2/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libavutil54/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libbind9-90/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libbsd0/oldoldstable 0.7.0-2+deb8u1 amd64 [actualizable desde: 0.7.0-2]
libbz2-1.0/oldoldstable 1.0.6-7+deb8u2 amd64 [actualizable desde: 1.0.6-7+b3]
libcomerr2/oldoldstable 1.42.12-2+deb8u2 amd64 [actualizable desde: 1.42.12-2+b1]
libcrack2/oldoldstable 2.9.2-1+deb8u1 amd64 [actualizable desde: 2.9.2-1]
libcups2/oldoldstable 1.7.5-11+deb8u8 amd64 [actualizable desde: 1.7.5-11+deb8u4]
libcupsfilters1/oldoldstable 1.0.61-5+deb8u4 amd64 [actualizable desde: 1.0.61-5+deb8u3]
libcupsimage2/oldoldstable 1.7.5-11+deb8u8 amd64 [actualizable desde: 1.7.5-11+deb8u4]
libcurl3/oldoldstable 7.38.0-4+deb8u16 amd64 [actualizable desde: 7.38.0-4+deb8u14]
libdbus-1-3/oldoldstable 1.8.22-0+deb8u3 amd64 [actualizable desde: 1.8.22-0+deb8u1]
libdns-export100/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libdns100/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libexpat1/oldoldstable 2.1.0-6+deb8u6 amd64 [actualizable desde: 2.1.0-6+deb8u4]
libexpat1-dev/oldoldstable 2.1.0-6+deb8u6 amd64 [actualizable desde: 2.1.0-6+deb8u4]
libfreetype6/oldoldstable 2.5.2-3+deb8u4 amd64 [actualizable desde: 2.5.2-3+deb8u2]
libgcrypt20/oldoldstable 1.6.3-2+deb8u8 amd64 [actualizable desde: 1.6.3-2+deb8u5]
libgd3/oldoldstable 2.1.0-5+deb8u14 amd64 [actualizable desde: 2.1.0-5+deb8u12]
libgl1-mesa-glx/oldoldstable 10.3.2-1+deb8u2 amd64 [actualizable desde: 10.3.2-1+deb8u1]
libglapi-mesa/oldoldstable 10.3.2-1+deb8u2 amd64 [actualizable desde: 10.3.2-1+deb8u1]
libglib2.0-0/oldoldstable 2.42.1-1+deb8u3 amd64 [actualizable desde: 2.42.1-1+b1]
libgs9/oldoldstable 9.26a~dfsg-0+deb8u6 amd64 [actualizable desde: 9.26a~dfsg-0+deb8u1]
libgs9-common/oldoldstable 9.26a~dfsg-0+deb8u6 all [actualizable desde: 9.26a~dfsg-0+deb8u1]
libhiredis0.10/oldoldstable 0.11.0-4+deb8u1 amd64 [actualizable desde: 0.11.0-4]
libice6/oldoldstable 2:1.0.9-1+deb8u1 amd64 [actualizable desde: 2:1.0.9-1+b1]
libicu52/oldoldstable 52.1-8+deb8u8 amd64 [actualizable desde: 52.1-8+deb8u7]
libirs-export91/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libisc-export95/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libisc95/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libisccc90/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libisccfg-export90/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libisccfg90/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libjasper1/oldoldstable 1.900.1-debian1-2.4+deb8u6 amd64 [actualizable desde: 1.900.1-debian1-2.4+deb8u5]
libjson-c2/oldoldstable 0.11-4+deb8u2 amd64 [actualizable desde: 0.11-4]
libldap-2.4-2/oldoldstable 2.4.40+dfsg-1+deb8u6 amd64 [actualizable desde: 2.4.40+dfsg-1+deb8u4]
liblwres90/oldoldstable 1:9.9.5.dfsg-9+deb8u19 amd64 [actualizable desde: 1:9.9.5.dfsg-9+deb8u17]
libmagic1/oldoldstable 1:5.22+15-2+deb8u7 amd64 [actualizable desde: 1:5.22+15-2+deb8u5]
libmagickcore-6.q16-2/oldoldstable 8:6.8.9.9-5+deb8u19 amd64 [actualizable desde: 8:6.8.9.9-5+deb8u15]
libmagickwand-6.q16-2/oldoldstable 8:6.8.9.9-5+deb8u19 amd64 [actualizable desde: 8:6.8.9.9-5+deb8u15]
libntlm0/oldoldstable 1.4-3+deb8u1 amd64 [actualizable desde: 1.4-3]
libonig2/oldoldstable 5.9.5-3.2+deb8u4 amd64 [actualizable desde: 5.9.5-3.2+deb8u1]
libopenjp2-7/oldoldstable 2.1.0-2+deb8u10 amd64 [actualizable desde: 2.1.0-2+deb8u6]
libpcap0.8/oldoldstable 1.6.2-2+deb8u1 amd64 [actualizable desde: 1.6.2-2]
libpq5/oldoldstable 9.4.26-0+deb8u1 amd64 [actualizable desde: 9.4.21-0+deb8u1]
libpython2.7/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
libpython2.7-dev/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
libpython2.7-minimal/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
libpython2.7-stdlib/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
libpython3.4-minimal/oldoldstable 3.4.2-1+deb8u7 amd64 [actualizable desde: 3.4.2-1+deb8u2]
libpython3.4-stdlib/oldoldstable 3.4.2-1+deb8u7 amd64 [actualizable desde: 3.4.2-1+deb8u2]
libsasl2-2/oldoldstable 2.1.26.dfsg1-13+deb8u2 amd64 [actualizable desde: 2.1.26.dfsg1-13+deb8u1]
libsasl2-modules-db/oldoldstable 2.1.26.dfsg1-13+deb8u2 amd64 [actualizable desde: 2.1.26.dfsg1-13+deb8u1]
libsdl1.2debian/oldoldstable 1.2.15-10+deb8u2 amd64 [actualizable desde: 1.2.15-10+deb8u1]
libsox-fmt-alsa/oldoldstable 14.4.1-5+deb8u4 amd64 [actualizable desde: 14.4.1-5+deb8u3]
libsox-fmt-base/oldoldstable 14.4.1-5+deb8u4 amd64 [actualizable desde: 14.4.1-5+deb8u3]
libsox-fmt-mp3/oldoldstable 14.4.1-5+deb8u4 amd64 [actualizable desde: 14.4.1-5+deb8u3]
libsox2/oldoldstable 14.4.1-5+deb8u4 amd64 [actualizable desde: 14.4.1-5+deb8u3]
libsqlite3-0/oldoldstable 3.8.7.1-1+deb8u6 amd64 [actualizable desde: 3.8.7.1-1+deb8u4]
libss2/oldoldstable 1.42.12-2+deb8u2 amd64 [actualizable desde: 1.42.12-2+b1]
libssh2-1/oldoldstable 1.4.3-4.1+deb8u6 amd64 [actualizable desde: 1.4.3-4.1+deb8u2]
libssl-dev/oldoldstable 1.0.1t-1+deb8u12 amd64 [actualizable desde: 1.0.1t-1+deb8u11]
libssl1.0.0/oldoldstable 1.0.1t-1+deb8u12 amd64 [actualizable desde: 1.0.1t-1+deb8u11]
libswscale3/oldoldstable 6:11.12-1~deb8u9 amd64 [actualizable desde: 6:11.12-1~deb8u6]
libsystemd0/oldoldstable 215-17+deb8u13 amd64 [actualizable desde: 215-17+deb8u11]
libtasn1-6/oldoldstable 4.2-3+deb8u4 amd64 [actualizable desde: 4.2-3+deb8u3]
libtiff-tools/oldoldstable 4.0.3-12.3+deb8u10 amd64 [actualizable desde: 4.0.3-12.3+deb8u8]
libtiff5/oldoldstable 4.0.3-12.3+deb8u10 amd64 [actualizable desde: 4.0.3-12.3+deb8u8]
libudev1/oldoldstable 215-17+deb8u13 amd64 [actualizable desde: 215-17+deb8u11]
libvorbis0a/oldoldstable 1.3.4-2+deb8u3 amd64 [actualizable desde: 1.3.4-2+deb8u1]
libvorbisenc2/oldoldstable 1.3.4-2+deb8u3 amd64 [actualizable desde: 1.3.4-2+deb8u1]
libvorbisfile3/oldoldstable 1.3.4-2+deb8u3 amd64 [actualizable desde: 1.3.4-2+deb8u1]
libvpx1/oldoldstable 1.3.0-3+deb8u3 amd64 [actualizable desde: 1.3.0-3+deb8u1]
libxdmcp6/oldoldstable 1:1.1.1-1+deb8u1 amd64 [actualizable desde: 1:1.1.1-1+b1]
libxml2/oldoldstable 2.9.1+dfsg1-5+deb8u8 amd64 [actualizable desde: 2.9.1+dfsg1-5+deb8u7]
linux-compiler-gcc-4.9-x86/oldoldstable 3.16.84-1 amd64 [actualizable desde: 3.16.64-2]
linux-image-amd64/oldoldstable 3.16+63+deb8u7 amd64 [actualizable desde: 3.16+63+deb8u4]
linux-libc-dev/oldoldstable 3.16.84-1 amd64 [actualizable desde: 3.16.64-2]
ntp/oldoldstable 1:4.2.6.p5+dfsg-7+deb8u3 amd64 [actualizable desde: 1:4.2.6.p5+dfsg-7+deb8u2]
openssl/oldoldstable 1.0.1t-1+deb8u12 amd64 [actualizable desde: 1.0.1t-1+deb8u11]
patch/oldoldstable 2.7.5-1+deb8u3 amd64 [actualizable desde: 2.7.5-1+deb8u1]
php-pear/oldoldstable 5.6.40+dfsg-0+deb8u12 all [actualizable desde: 5.6.40+dfsg-0+deb8u2]
php5/oldoldstable 5.6.40+dfsg-0+deb8u12 all [actualizable desde: 5.6.40+dfsg-0+deb8u2]
php5-cli/oldoldstable 5.6.40+dfsg-0+deb8u12 amd64 [actualizable desde: 5.6.40+dfsg-0+deb8u2]
php5-common/oldoldstable 5.6.40+dfsg-0+deb8u12 amd64 [actualizable desde: 5.6.40+dfsg-0+deb8u2]
php5-curl/oldoldstable 5.6.40+dfsg-0+deb8u12 amd64 [actualizable desde: 5.6.40+dfsg-0+deb8u2]
php5-gd/oldoldstable 5.6.40+dfsg-0+deb8u12 amd64 [actualizable desde: 5.6.40+dfsg-0+deb8u2]
php5-mysql/oldoldstable 5.6.40+dfsg-0+deb8u12 amd64 [actualizable desde: 5.6.40+dfsg-0+deb8u2]
python-urllib3-whl/oldoldstable 1.9.1-3+deb8u1 all [actualizable desde: 1.9.1-3]
python2.7/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
python2.7-dev/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
python2.7-minimal/oldoldstable 2.7.9-2+deb8u5 amd64 [actualizable desde: 2.7.9-2+deb8u2]
python3.4/oldoldstable 3.4.2-1+deb8u7 amd64 [actualizable desde: 3.4.2-1+deb8u2]
python3.4-minimal/oldoldstable 3.4.2-1+deb8u7 amd64 [actualizable desde: 3.4.2-1+deb8u2]
redis-server/oldoldstable 2:2.8.17-1+deb8u7 amd64 [actualizable desde: 2:2.8.17-1+deb8u6]
redis-tools/oldoldstable 2:2.8.17-1+deb8u7 amd64 [actualizable desde: 2:2.8.17-1+deb8u6]
rsyslog/oldoldstable 8.4.2-1+deb8u3 amd64 [actualizable desde: 8.4.2-1+deb8u2]
sasl2-bin/oldoldstable 2.1.26.dfsg1-13+deb8u2 amd64 [actualizable desde: 2.1.26.dfsg1-13+deb8u1]
sox/oldoldstable 14.4.1-5+deb8u4 amd64 [actualizable desde: 14.4.1-5+deb8u3]
sudo/oldoldstable 1.8.10p3-1+deb8u7 amd64 [actualizable desde: 1.8.10p3-1+deb8u5]
systemd/oldoldstable 215-17+deb8u13 amd64 [actualizable desde: 215-17+deb8u11]
systemd-sysv/oldoldstable 215-17+deb8u13 amd64 [actualizable desde: 215-17+deb8u11]
tcpdump/oldoldstable 4.9.3-1~deb8u1 amd64 [actualizable desde: 4.9.2-1~deb8u1]
tzdata/oldoldstable 2019c-0+deb8u1 all [actualizable desde: 2018i-0+deb8u1]
udev/oldoldstable 215-17+deb8u13 amd64 [actualizable desde: 215-17+deb8u11]
unzip/oldoldstable 6.0-16+deb8u6 amd64 [actualizable desde: 6.0-16+deb8u3]
vim/oldoldstable 2:7.4.488-7+deb8u4 amd64 [actualizable desde: 2:7.4.488-7+deb8u3]
vim-common/oldoldstable 2:7.4.488-7+deb8u4 amd64 [actualizable desde: 2:7.4.488-7+deb8u3]
vim-runtime/oldoldstable 2:7.4.488-7+deb8u4 all [actualizable desde: 2:7.4.488-7+deb8u3]
vim-tiny/oldoldstable 2:7.4.488-7+deb8u4 amd64 [actualizable desde: 2:7.4.488-7+deb8u3]
wget/oldoldstable 1.16-1+deb8u7 amd64 [actualizable desde: 1.16-1+deb8u5]
zlib1g/oldoldstable 1:1.2.8.dfsg-2+deb8u1 amd64 [actualizable desde: 1:1.2.8.dfsg-2+b1]
zlib1g-dev/oldoldstable 1:1.2.8.dfsg-2+deb8u1 amd64 [actualizable desde: 1:1.2.8.dfsg-2+b1]`

Eskerrik Asko!

Álvaro.

**Comment by Kaian** [comment]
Hi @amvidalrc 

I think this questions belongs more to the user group than github issue, but I'll try to give some light. Also try to use provided github issue templates.

Packages were designed with compatibility in mind, but take into account that Oasis and Artemis are based on different Debian versions so upgrading is possible, but risky as there are lots of changes.

> Its possible to upgrade easily to Artemis? Or it's better to deploy a new machine? Is there any way to restore the DB from Oasis to Artemis?

Yes, it should be possible to migrate Oasis DB to Artemis. 

- Upgrade Oasis to latest version available (this will apply all requires changes in Oasis database)
- Dump ivozprovider Oasis database to a file (pe. oasis-ivozprovider-dump.sql)
- Install a new machine with artemis
- Drop ivozprovider database and create it again
- Load  ivozprovider Oasis database from created dump
- Apply all database migrations (this can take a while)

In commands:
 ```
cd /opt/irontec/ivozprovider/schema/
bin/console doctrine:database:drop --force
bin/console doctrine:database:create
bin/console doctrine:database:import oasis-ivozprovider-dump.sql
bin/console doctrine:migrations:migrate -n
```

If no error appears, then database should contain all data migrated to new tables. Otherwise, you may have to do some manual migrations in order to continue applying changes.

You will also need to move/sync storage files in /opt/irontec/ivozprovider/storage to the new artemis machine.
Be sure to read all upgrade notes, some of them apply to storage files:

https://github.com/irontec/ivozprovider/tree/bleeding/doc

Regards!
