### ISSUE TITLE
Malformed contact header

### ISSUE THREAD

**Issue by overload08** [irontec/ivozprovider#1491]
Hi.

I try to make a call with a residential device.
But le contact header sent to the provider is : "Contact: <sip:asterisk@127.0.0.1:6060>"

For my side, it must be "Contact: <sip:username@external_ip:6060>"

How I can change it ?

Thank's

**Comment by ironArt3mis** [comment]
Please, use provided templates for Bug Reports.

Be sure you have read the project FAQ before submitting an issue.

  * https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md

If you have trouble with your environment or a user question, please post them in ivozproider-users group

  * https://groups.google.com/forum/#!forum/ivozprovider-users
