### ISSUE TITLE
Klear web error after upgrade on login to god portal

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1539]
### Description

Unable to log to web portal after upgrade from 2.11.1 to 2.16.3

---

- IvozProvider version: 
from `2.11~2.11.1~20190711.2151~8cf11ef+artemis all`
to     ` 2.16~2.16.3~20201222.3042~d6363f9+artemis all `
- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [x] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting

Unable to log in to https://xxx.net nor https://ip.address

### Additional Information

```
Jan  1 13:13:32 sip klear[1110]: syntax error, unexpected '&&' (T_BOOLEAN_AND) (0) # /opt/irontec/klear/modules/klear/models/YamlStream.php(198) : eval()'d code(1)
```

I would like to congratulate the project team.
I have done an upgrade from 2.11.1 to 2.16.2 without major errors, db migrations perfect, despite this that seems to be minimal ( or maybe is my fault). It's not easy to keep the level high!!!!

Congratulations and go 2021!

**Comment by gil-obradors** [comment]
found it!

For upgrade, needs to follow this [guide](https://github.com/irontec/ivozprovider/blob/bleeding/doc/UPGRADE.md), and after manually `apt install klear`
```
Unpacking klear (3.0.0~20201221.124~5376d48+tayler) over (3.0.0~20190624.115~a587446+tayler)
```
Maybe `ivozprovider-web-admin 2.16~2.16.3~20201222.3042~d6363f9+artemis all`
must depends of `klear 3.0.0~20201221.124~5376d48+tayler` ?

**Comment by Kaian** [comment]
Hi @gil-obradors 

Sorry for the late response. I don't know why I thought we already talked about this :sweat: 

The dependency thing would be a good option, but it must be done manually, after committing and building klear packages. It's a procedure that is likely to be forgotten, as klear does not change that much.

I like more the idea to update docs to include klear, klear-matrix and klear-library in the upgrade instructions. Klear only maintains one branch, so the latest version is backwards compatible.

Thanks for reporting!
