### ISSUE TITLE
klear-generator: remove unused raw templates

### ISSUE THREAD

**Issue by Kaian** [irontec/ivozprovider#165]
Right now we use [klear-generator](https://github.com/irontec/klear-generator) to create SQL mappers, models, Rest API controllers and default YAML files from DB tables.

When a delta introduces a new db change, all this generated files changes and are commited but not all of them are used in the platform: their only purpose is to serve as base for the final files.

IMHO, this paths should be removed from git repos:

-  portals/application/configs/klearRaw
-  portals/application/modules/controllersRaw

This will reduce the commited data for database changes.

Right now the Rest API controllersRaw are directly copied to the final controllers so we could update generate-rest-controllers task to write generated files there.

Opinions?

**Comment by mmadariaga** [comment]
I agree on putting those directories out of version control. I wouldn't change generated rest controllers path, it's going to be a source of problems as soon as we add any custom modification.

**Comment by Kaian** [comment]
This has been done at 93347ea265346f1ccc06f3e977a33b54a05af16b

Tha [latest tayler changes](https://github.com/irontec/klear-generator/commit/554b43b7da0ea9c0277b282f9cbee920d9f20ce6) of klear generator will regenerate Rest API controllers directly to modules/rest/controllers directory.
