### ISSUE TITLE
DDI pattern support for numbering arcs (e.g. 1234500-99)

### ISSUE THREAD

**Issue by nitefood** [irontec/ivozprovider#1741]
### Description

An useful feature would be to support patterns in DDI creation, so to handle cases (very frequent in our scenario) where a customer purchases an arc of, say, 100 numbers (e.g. 1234500-99). Currently we have to add them manually one by one.
Sorry if there's a way already, but I haven't found how to do it from the documentation yet.
Thanks!

---

- I'm willing to: 

 - [ ] Implement this feature myself
 - [ ] Pay to priorize this new feature

**Comment by nitefood** [comment]
And of course right after opening the issue I noticed this is essentially a duplicate of #1727
Sorry about that, feel free to close if necessary.

**Comment by Kaian** [comment]
I think this could be done as part of #892

Right know DDIs must be assigned to a company, but #892 will allow to create DDIs that are unassinged, so an importer and mass assign options will be good enhacements.

Meanwhile, a solution could be to create and assign those DDIs through the Brand Rest API. 

I would close this as duplicated, thanks for the feedback!
