### ISSUE TITLE
instalacion con Nat

### ISSUE THREAD

**Issue by invental** [irontec/ivozprovider#177]
Estamos probando la solución y al realizar la instalación detrás de NAT los dispositivos no se conectan, ni terminales ni softphone, lo hemos probado con los usuarios de prueba que ya vienen configurados

Hemos probado a configurar la ip publica en el proxy de usuarios y de proveedores, hemos probado con una ip privada en ambos, solamente nos funciona correctamente si en ambos proxys y en la configuración de red tenemos la ip publica.
Hemos probado incluso con una dmz a una ip privada, la misma que tiene la interface de red y los proxys, tampoco funciona.

**Comment by Kaian** [comment]
Buenas @invental 

Gracias por probar la solución! 

IvozProvider está diseñado para funcionar con al menos una IP publica (que puede ser compartida por ambos proxies en las instalaciones standalone). En las versiones iniciales hicimos algunas pruebas empleando IPs privadas y DMZ pero no tuvimos éxito, por lo que el único soporte actual es estando expuesto a la red publica.

Intentamos actualizar la documentación para remarcarlo, aunque sin duda tendremos que darle una revisión: https://irontec.github.io/ivozprovider/es/intro/what_is_ivozprovider.html#exposed-to-the-public-network

No descartamos volverlo a intentar en un futuro, pero será necesario adaptar la configuración de ambos proxies. Actualmente, todas nuestros entornos productivos cuentan con IPs públicas, por lo que esta mejora no está planificada en el roadmap.

Un saludo!!

**Comment by invental** [comment]
Buenas tardes y gracias por la rapida respuesta.

como dices los dejasteis bien especificado, pero está claro que se nos pasó por alto este apartado de la documentación.

Teniendo es cuenta este detalle de funcionar tras nat, vamos a realizar la instal.lación y seguiremos con las pruebas, esperamos dar pronto un buen feedback.

saludos

**Comment by Kaian** [comment]
De Nada! A vosotros por vuestro tiempo y pruebas.

No dudéis en abrirnos una incidencia con cada una de las dudas o problemas que encotréis y trataremos de solucionarlos. Aunque el idioma preferente para las incidencias de GitHub es inglés (para que las respuestas puedan ser entendidas por el máximo de usuarios) podéis abrirlas en español si os resulta más cómodo. A fin de cuentas, también es nuestra primera lengua, por lo que estamos valorando hacer una lista de distribucción para usuarios en esta lengua.

Un saludo y esperamos oir vuestras noticias!
