### ISSUE TITLE
Allow users to use any screen extension

### ISSUE THREAD

**Issue by Kaian** [irontec/ivozprovider#18]
Right now users can only present as internal number any of the extensions that are routed to them.

I think there shouldn't be a problem (other than selecting the extension in the infernal selection box) if we allow selecting any existing extension.

**Comment by cruzccl** [comment]
The logic should also avoid selecting extensions that point to another user (or a friend), shouldn't it?

And what about using a extension that points to an external number, a fax or a conference room?

I think you should be able to choose between: extensions that point to you, to a huntgroup, to a queue (and maybe to IVRs...).

Opinions?

**Comment by Kaian** [comment]
Users can only use as presented extension one that route to them.

That is fine and simple, so this no longer seems a good enhancement to me.

Let's just keep it short and simple
