### ISSUE TITLE
IVR: difference routing for no digit entered and wrong extensions

### ISSUE THREAD

**Issue by gelexpe** [irontec/ivozprovider#182]
To send caller to operator when nothing pressed, but maybe you want to repeat the IVR if callers press a wrong extension, need to difference two causes.

**Comment by cruzccl** [comment]
Hi @gelexpe,

The IVR sections need a lot of work, you are right :confused: 

The first thing we want to evaluate is merging the two sections into a unique one (see #180), we add your suggestion to the roadmap too.

Thanks for reporting!

**Comment by Kaian** [comment]
Implemented in #287
