### ISSUE TITLE
Close all tabs button

### ISSUE THREAD

**Issue by pedro-reis** [irontec/ivozprovider#1820]
### Description
While using iVoz it's very common to visit several sections of the configuration, the consequence is that after some time several dozens of tabs are open.
As far as I can see there's no option/button to close all the tabs, it would be fantastic to have a button to close all open tabs instead of having to manually close them.

---

Something like this below, or something native to Klear/UI Framework

var lis = document.getElementsById("tabsList");
for(var i = 0, il = lis.length;i<il;i++) {
    root.removeChild(lis[i]);
}

**Comment by Kaian** [comment]
Hi!

There are some keybindings in klear thay you can use to manage your tabs. You can find them in the info icon next to logout.

![image](https://user-images.githubusercontent.com/800069/173292826-f6e05199-f144-4221-b2e8-092e3769b8f8.png)

Ctrl+Alt+Q can help, which closes all tabs except the current one.

Regards!
