### ISSUE TITLE
MOH while ringing in huntgroups

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#184]
Evaluate making optional to use MOH instead of ringing tone in huntgroups (using the m option of Dial application).

**Comment by Kaian** [comment]
This behaviour was enabled long time ago in 864a0eb76ef830bf45324d965a919df693e70fa7 but the feedback is not the expected.

The music on hold in hunt groups is played in the Dial application, so it starts when dialing a huntgroup member and stops between members. This creates a sound effect when moh starts and stops all the time (the sorter the dial timeout, the worse).
