### ISSUE TITLE
web access not working

### ISSUE THREAD

**Issue by hosseinj00n** [irontec/ivozprovider#1889]
Hi,
 i just installed a fresh setup of IVOZ(artemis stable) , web access is not working for me i got this error :

Internal Server Error
Please contact the server administrator.

More information about this error may be availabe in the server syslog.
------------------
o
Sep 06 09:59:57 ivozprovider-standalone klear[775]: An exception occured in driver: SQLSTATE[HY000] [1698] Access den
Sep 06 09:59:57 ivozprovider-standalone httpd[767]: XXX.XXX.XXX.XXX - - [06/Sep/2022:09:59:57 -0400] "GET / HTTP/1.1"
apache status has this error.
Thanks in advance.

**Comment by Kaian** [comment]
Hi, 

This looks like an enviroment issue, so It's better reported on https://groups.google.com/forum/#!forum/ivozprovider-users

Looks like a problem accessing mysql. Database password must be entered twice during installation menu, once during mysql-server install dialogs and another time in ivozprovider configuration menu. Be sure both entered passwords match.

You can check the entered password in ivozprovider configuration menu running in the shell:

    # echo get ivozprovider/mysql_password | debconf-communicate
