### ISSUE TITLE
Debian 11

### ISSUE THREAD

**Issue by MichaelSTK** [irontec/ivozprovider#1915]
Hi,

Is there a way to install a standalone version on Debian 11?

**Comment by Kaian** [comment]
Please use provided templates when reporting issues in github.

Questions are always welcomed at [users list](https://groups.google.com/g/ivozprovider-users), leaving github for software bugs or feature requests.

Check [FAQ](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md) for more details.
