### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by damidani** [irontec/ivozprovider#1919]
- IvozProvider version: Artemis 2.21

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [X] Other

### Troubleshooting

cd /etc/apt/sources.list.d
echo deb http://packages.irontec.com/debian artemis main extra > ivozprovider.list
echo deb http://packages.irontec.com/debian tayler main > klear.list

apt update
apt Install ivozprovider 
### Error

Paramétrage de ivozprovider-scheduler (2.21~2.21.2~20221021.3497~8cfb0f7+artemis) ...
setfacl: var: Aucun fichier ou dossier de ce type
dpkg: erreur de traitement du paquet ivozprovider-scheduler (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Paramétrage de ivozprovider-realtime (2.21~2.21.2~20221021.3497~8cfb0f7+artemis) ...
setfacl: var: Aucun fichier ou dossier de ce type
dpkg: erreur de traitement du paquet ivozprovider-realtime (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
dpkg: des problèmes de dépendances empêchent la configuration de ivozprovider-profile-portal :
 ivozprovider-profile-portal dépend de ivozprovider-scheduler (= 2.21~2.21.2~20221021.3497~8cfb0f7+artemis) ; cependant :
 Le paquet ivozprovider-scheduler n'est pas encore configuré.
 ivozprovider-profile-portal dépend de ivozprovider-realtime (= 2.21~2.21.2~20221021.3497~8cfb0f7+artemis) ; cependant :
 Le paquet ivozprovider-realtime n'est pas encore configuré.

dpkg: erreur de traitement du paquet ivozprovider-profile-portal (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de ivozprovider :
 ivozprovider dépend de ivozprovider-profile-portal (= 2.21~2.21.2~20221021.3497~8cfb0f7+artemis) ; cependant :
 Le paquet ivozprovider-profile-portal n'est pas encore configuré.

dpkg: erreur de traitement du paquet ivozprovider (--configure) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 ivozprovider-scheduler
 ivozprovider-realtime
 ivozprovider-profile-portal
 ivozprovider
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@voip:~# 

Do you have a solution ?

thanks

**Comment by Kaian** [comment]
Hi!!

Thanks for reporting!! We have recently changed the package postinstall scripts to fail on any error, and we missed some directory creation lines.

This has been fixed in https://github.com/irontec/ivozprovider/commit/d2fca20dc0029eed106cf4f23c972e5707808a1d and should be available in latests artemis packages if you update from repos and retry install commands.

Regards!
