### ISSUE TITLE
Outgoing DDI rules

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#192]
Currently when a user calls, its outgoing DDI is used as presentation number.

This feature aims to add flexibility to this behaviour, letting you use a different DDI when calling to specific destinations:

**Changes in Users:**

- Users will need an outgoingDDI as they do now.

- Users may have an OutgoingDDIRule assigned.

**New section: OutgoingDDIRules:**

- _Name_
- _Default action_: what will be done if no rule applies (Keep original DDI / Force DDI)
- _Forced DDI_: DDI used if previous setting is "Force DDI".
- None, one or multiple rules:
  - _Destination regexp_: when will this rule apply.
  - _Action_: what will this rule do (Keep original DDI / Force DDI).
  - _Forced DDI_: DDI used if previous setting is "Force DDI".
  - _Metric_ (to handle collisions).

**Usage examples**

- User that shows his/her DDI only when calling to certain destinations and shows a global DDI for remaining destinations.
  - Name: Known destinations
  - Default action: force DDI
  - Forced DDI: company global DDI
  - One rule per known destination with "keep original DDI" as action.
  - User OutgoingDDI: the one that points to this user.

- User that shows a german DDI when calling to Germany, a french one when calling to France and a generic DDI when for remaining countries.
  - Name: Country specific
  - Default action: keep original
  - One rule per country with "force DDI" as action and that country's DDI as forced value.
  - User OutgoingDDI: company global DDI.

**Comment by Kaian** [comment]
Implemented in #196
