### ISSUE TITLE
ERROR: rtpengine / Asterisk worker timeout / Failed to start RTPEngine Mediaproxy

### ISSUE THREAD

**Issue by MichaelSTK** [irontec/ivozprovider#1950]
### Description
My posts are deleted in the group, I would like to solve these problems as I want to use the software. If my messages are deleted every time then I can't solve the problems and also can't start using the software.

- IvozProvider version: 3.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [X] Other

### Troubleshooting
    (kamtail-proxyusers and in kamtail-proxytrunks)
    [Nov 24 07:41:40] rtpengine [rtpengine.c:3070]: send_rtpp_command(): can't send command "ping" to RTPEngine <udp:[127.0.0.1:22223](http://127.0.0.1:22223/)>
    [Nov 24 07:41:40] rtpengine [rtpengine.c:2919]: rtpp_test(): proxy did not respond to ping

    (journalct1 -p err -fa)
    Nov 24 07:41:40 debian /usr/sbin/kamailio[830]: ERROR: rtpengine [rtpengine.c:3070]: send_rtpp_command(): can't send command "ping" to RTPEngine <udp:[127.0.0.1:22223](http://127.0.0.1:22223/)>
    Nov 24 07:41:40 debian /usr/sbin/kamailio[830]: ERROR: rtpengine [rtpengine.c:2919]: rtpp_test(): proxy did not respond to ping
    Nov 24 07:41:40 debian /usr/sbin/kamailio[890]: ERROR: rtpengine [rtpengine.c:3070]: send_rtpp_command(): can't send command "ping" to RTPEngine <udp:[127.0.0.1:22223](http://127.0.0.1:22223/)>
    Nov 24 07:41:40 debian /usr/sbin/kamailio[890]: ERROR: rtpengine [rtpengine.c:2919]: rtpp_test(): proxy did not respond to ping
    Nov 24 07:41:40 debian systemd[1]: Failed to start RTPEngine Mediaproxy.
    Nov 24 07:41:49 debian asterisk[951]: ERROR[951]: file.c:1205 in __ast_file_read_dirs: Error reading path stats - /var/lib/asterisk/moh/custom: No such file or directory
    Nov 24 07:41:49 debian asterisk[951]: ERROR[951]: file.c:1252 in __ast_file_read_dirs: Error while reading directories - /var/lib/asterisk/moh: No such file or directory
    Nov 24 07:41:49 debian asterisk[951]: ERROR[951]: loader.c:2508 in load_modules: Error loading module 'codec_g729.so': /usr/lib/asterisk/modules/codec_g729.so: cannot open shared object file: No such file or directory
    Nov 24 07:41:49 debian /usr/sbin/kamailio[840]: ERROR: [5f34dfb5] PARSE-MANDATORY-X-HEADER: 'X-Info-BrandId' not present or not valid, aborting
    Nov 24 07:41:49 debian /usr/sbin/kamailio[830]: ERROR: [faaba9e7] PARSE-MANDATORY-X-HEADER: 'X-Info-BrandId' not present or not valid, aborting
    Nov 24 08:09:10 debian httpd[661]: [Thu Nov 24 08:09:10.985148 2022] [core:error] [pid 682] [client [152.89.196.211:35082](http://152.89.196.211:35082/)] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
    Nov 24 08:41:39 debian worker[808]: workers.ERROR: Invoicer timeout [] []
    Nov 24 08:41:39 debian worker[804]: workers.ERROR: Invoicer timeout [] []
    Nov 24 08:41:39 debian worker[807]: workers.ERROR: Invoicer timeout [] []
    Nov 24 08:41:39 debian worker[801]: workers.ERROR: Asterisk worker timeout: read error on connection to [127.0.0.1:6379](http://127.0.0.1:6379/) [] []
    Nov 24 08:41:39 debian worker[803]: workers.ERROR: Invoicer timeout [] []
    Nov 24 08:41:39 debian worker[802]: workers.ERROR: Asterisk worker timeout: read error on connection to [127.0.0.1:6379](http://127.0.0.1:6379/) [] []
    Nov 24 08:41:39 debian worker[806]: workers.ERROR: KamRpc timeout: read error on connection to [127.0.0.1:6379](http://127.0.0.1:6379/) [] []
    Nov 24 08:41:39 debian worker[805]: workers.ERROR: KamRpc timeout: read error on connection to [127.0.0.1:6379](http://127.0.0.1:6379/) [] []

    (systemctl status rtpengine.service)
    Nov 24 07:41:40 debian systemd[1]: rtpengine.service: Start request repeated too quickly.
    Nov 24 07:41:40 debian systemd[1]: rtpengine.service: Failed with result 'exit-code'.
    Nov 24 07:41:40 debian systemd[1]: Failed to start RTPEngine Mediaproxy.

### Additional Information
 https://groups.google.com/g/ivozprovider-users/c/FpqaF5OFLIE/m/hGOfej9zCgAJ

I tested the above and these are the results

/etc/default/rtpengine configuration
.# Control socket
CONTROL_SOCK=127.0.0.1:22223
.# Interface to bind rtpengine to
AUDIO_SOCK=(external server ip)
.# Destination files for recordings
RECORDINGS_SPOOL=/var/spool/rtpengine/
.# Additional command line options
EXTRA_OPTS="-m 13000 -M 19000"

~# redis-cli ping
PONG

~# redis-cli -p 26379
127.0.0.1:26379> info
.# Server
redis_version:6.0.16
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:6d95e1af3a2c082a
redis_mode:sentinel
os:Linux 5.10.0-19-cloud-amd64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:10.2.1
process_id:567
run_id:bc7f429d2af74f3526d7db37db0d6374eb66a989
tcp_port:26379
uptime_in_seconds:456867
uptime_in_days:5
hz:17
configured_hz:10
lru_clock:8788181
executable:/usr/bin/redis-sentinel
config_file:/etc/redis/sentinel.conf
io_threads_active:0

.# Clients
connected_clients:62
client_recent_max_input_buffer:8
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

.# CPU
used_cpu_sys:640.824934
used_cpu_user:712.789717
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

.# Stats
total_connections_received:1225
total_commands_processed:2388
instantaneous_ops_per_sec:0
total_net_input_bytes:111886
total_net_output_bytes:756263
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:13208
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_reads_processed:3554
total_writes_processed:2392
io_threaded_reads_processed:0
io_threaded_writes_processed:0

.# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=mymaster,status=ok,address=127.0.0.1:6379,slaves=0,sentinels=1
127.0.0.1:26379>

---

I know it doesn't belong here but since my posts are being deleted I can never solve the problem on my own

**Comment by Kaian** [comment]
Hi @MichaelSTK 

For some reason your posts in the group are held waiting for approval of an administator. It's the first time I see pending posts to be validated (all moderation settings are disabled except from spam), so I don't know the reason.

Anyway, I check from time to time the list to approve all pending posts.

Use Github only for bug reports and not your enviroment problems.

Thanks!
