### ISSUE TITLE
grandstream ip phones templates

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#200]
I'm trying to create templates to provision grandstream phones but I'm not able to do so.

Grandstream phones can provision in two phases.

When the phone boots it supports DHCP option 66 and DHCP option 43 (in more recent models) to get the provision path. We can config this path manually too.

The phone will try to get the provision template from the configured path.

First it searches for  cfg000B82000000.xml file -where 000B82000000 is phone MAC- and if it doesn't find that file it searches for cfg.xml file.

So if path is `198.51.100.10/gs` it will first try to search for `http://198.51.100.10/gs/cfg000B82000000.xml` and if that doesn't exists it will try `http://198.51.100.10/gs/cfg.xml`. These are examples for http provision but there is a config value to make it search on http, https or tftp.

The first problem I found is that the phone needs xml files not plain text files, but that can be easily solved as we can write php code on the template field.

So the generic file is easy. Something like this.

```php
<?php 
header('Content-Type: application/xml');
?><?xml version="1.0" encoding="UTF-8" ?> 
<gs_provision version="1">
  <config version="1">
    <P212>2</P212>
    <P237><?php echo $_SERVER['SERVER_NAME']; ?>:443/provision/gxp2130</P237>
    <P8387>1</P8387>
  </config>
</gs_provision>
```

The code for the specific file is easy to code too. It would be something like this:

```php
<?php 
header('Content-Type: application/xml');
?><?xml version="1.0" encoding="UTF-8" ?> 
<gs_provision version="1">
  <mac><?php echo $this->terminal->getMac(); ?></mac>
  <config version="1">
    <P270><?php echo $this->terminal->getName(); ?></P270>
    <P47><?php echo $this->company->getDomainUsers(); ?></P47>
    <P35><?php echo $this->user->getName(); ?></P35>
    <P36><?php echo $this->user->getName(); ?></P36>
    <P34><?php echo $this->user->getPassword(); ?></P34>
    <P3><?php echo $this->user->getName(); ?></P3>
    <P33>*93</P33>
  </config>
</gs_provision>
```

The problem is that I don't know how can I manage to make ivozprovider to reply to request to cfg{MAC}.xml files as I can not edit the path in the specific file.

It is a fixed value `https://{PROVISIONING_URL}:{PORT_IN_GENERIC_FILE}/provision/{OPTIONAL_SUBPATHS}/`

And I would need it to be something like `https://{PROVISIONING_URL}:{PORT_IN_GENERIC_FILE}/provision/{OPTIONAL_SUBPATHS}/cfg{MAC}.xml`

**Comment by mmadariaga** [comment]
Hi @manfer,

We're already working on a patch in order to make that possible. 

Thanks for your report :)

**Comment by mmadariaga** [comment]
Hi @manfer,

Could you confirm that everything works as spected with https://github.com/irontec/ivozprovider/pull/202 applied?

Thank you so much

**Comment by manfer** [comment]
On next upgrade of my IvozProvider I will test and provide some grandstream phones templates. Thanks.

**Comment by manfer** [comment]
Hi @mmadariaga 
Tested and working

I will share templates when ready.
