### ISSUE TITLE
doc: Queue strategies

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#204]
Add some documentation explaining different call distribution strategies supported by queues.

**Comment by Kaian** [comment]
I would also extend this to include info boxes next to the field, for both Queues and HuntGroups strategies.

**Comment by Kaian** [comment]
I have discovered that in fact this is documented in [field info box](https://github.com/irontec/ivozprovider/blob/bleeding/portals/application/configs/klear/conf.d/queuesHelp.yaml), but like many other multiline help text is not translated.
