### ISSUE TITLE
AWS: Kamailio cannot assign public IP address

### ISSUE THREAD

**Issue by mveerdon** [irontec/ivozprovider#215]
Hi, 
i'm getting installation errors during my first installation of ivozproivder on an Amazon AWS debian 8 instance.
The log is attached via PasteBin.
[https://pastebin.com/EeqKBSvr](url)
Anybody any ideas?

regards, Marty

**Comment by Kaian** [comment]
Hi @mveerdon 

```
/var/lib/dpkg/info/ivozprovider.config: line 140: /etc/resolv.conf: Permission denied
```
Which makes reference to [initial resolv.conf setup](https://github.com/irontec/ivozprovider/blob/bleeding/debian/ivozprovider.config#L140)
Be sure /etc/resolv.conf has the following content:
```
domain ivozprovider.local
search ivozprovider.local
nameserver 127.0.0.1
```

```
Jul 20 12:08:38 ip-172-31-35-201 /usr/sbin/kamailio[23346]: ERROR: <core> [udp_server.c:367]: udp_init(): bind(7, 0x7ff53903594c, 16) on XX.XX.XX.XX: Cannot assign requested address
```

During installation, configuration menu should have prompted to enter Porxies IP addresses.
Be sure that IP addresses are available in any of your interfaces and try to finish the installation with `apt-get -f install`

Best regards,

**Comment by mveerdon** [comment]
Thanks, I will change/adjust it and look at the result.

Do I need 2 different ip addresses for users SIP proxy and providers SIP proxy?

**Comment by Kaian** [comment]
For standalone installations (all packages in the same machine) you can configure the same address for both proxies. The package installation script will change the ports of the trunks SIP proxy to listen to a different port.

More info in the blue box [here](https://irontec.github.io/ivozprovider/en/installation/requirements.html)

You can change your IP addresses anytime by runing `dpkg-reconfigure ivozprovider` and entering new values.

Regards!

**Comment by mveerdon** [comment]
@Kaian 
the resolv.conf file is okay.
the public IP address is associated to the private IP address via Amazon AWS service. 
The result is that still the system is not totally up and running.

Any ideas?

> apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.


eth0      Link encap:Ethernet  HWaddr 06:23:f3:f5:c4:77  
          inet addr:172.31.35.201  Bcast:172.31.47.255  Mask:255.255.240.0
          inet6 addr: fe80::423:f3ff:fef5:c477/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:180926 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30751 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:251124509 (239.4 MiB)  TX bytes:3561382 (3.3 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3327 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3327 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:500485 (488.7 KiB)  TX bytes:500485 (488.7 KiB)

          systemctl status
          ● ip-172-31-35-201
              State: degraded
               Jobs: 0 queued
             Failed: 3 units
              Since: Thu 2017-07-20 11:15:52 UTC; 19h ago
             CGroup: /
                     ├─1 /bin/systemd
                     └─system.slice
                       ├─dbus.service
                       │ └─21234 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
                       ├─cron.service
                       │ └─328 /usr/sbin/cron -f
                       ├─rtpproxy.service
                       │ └─22747 /usr/bin/rtpproxy -u root -f -p /var/run/rtpproxy.pid -s udp:127.0.0.1 22222 -l 0.0.0.0 -r /opt/irontec/ivozprovider/storage/ivozprovider_model_recordings.originalfile/ -S /opt/
                       ├─apache2.service
                       │ ├─21864 /usr/sbin/apache2 -k start
                       │ ├─22840 /usr/sbin/apache2 -k start
                       │ ├─22841 /usr/sbin/apache2 -k start
                       │ ├─22842 /usr/sbin/apache2 -k start
                       │ ├─22843 /usr/sbin/apache2 -k start
                       │ ├─22844 /usr/sbin/apache2 -k start
                       │ └─23567 /usr/sbin/apache2 -k start
                       ├─gearman-job-server.service
                       │ └─20085 /usr/sbin/gearmand --listen=localhost --pid-file=/run/gearman/server.pid --log-file=/var/log/gearman-job-server/gearman.log
                       ├─memcached.service
                       │ └─22929 /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1
                       ├─networking.service
                       │ └─307 dhclient -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
                       ├─asterisk.service
                       │ └─23358 /usr/sbin/asterisk -f -C /etc/asterisk/asterisk.conf
                       ├─system-serial\x2dgetty.slice
                       │ └─serial-getty@ttyS0.service
                       │   └─449 /sbin/agetty --keep-baud 115200 38400 9600 ttyS0 vt102
                       ├─systemd-journald.service
                       │ └─173 /lib/systemd/systemd-journald
                       ├─ssh.service
                       │ ├─  440 /usr/sbin/sshd -D
                       │ ├─26030 sshd: admin [priv]  
                       │ ├─26032 sshd: admin@pts/0   
                       │ ├─26033 -bash
                       │ ├─26092 sshd: admin [priv]  
                       │ ├─26094 sshd: admin@pts/1   
                       │ ├─26095 -bash
                       │ ├─26108 sudo -i
                       │ ├─26109 -bash
                       │ ├─26474 systemctl status
                       │ └─26475 pager
                       ├─bind9.service
                       │ └─23299 /usr/sbin/named -f -u bind
                       ├─system-getty.slice
                       │ ├─getty@tty4.service
                       │ │ └─445 /sbin/agetty --noclear tty4 linux
                       │ ├─getty@tty6.service
                       │ │ └─443 /sbin/agetty --noclear tty6 linux
                       │ ├─getty@tty1.service
                       │ │ └─448 /sbin/agetty --noclear tty1 linux
                       │ ├─getty@tty3.service
                       │ │ └─446 /sbin/agetty --noclear tty3 linux
                       │ ├─getty@tty5.service
                       │ │ └─444 /sbin/agetty --noclear tty5 linux
                       │ └─getty@tty2.service
                       │   └─447 /sbin/agetty --noclear tty2 linux
                       ├─systemd-udevd.service
                       │ └─182 /lib/systemd/systemd-udevd
                       ├─mysql.service
                       │ ├─13085 /bin/sh /usr/bin/mysqld_safe
                       │ └─13430 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.p
                       ├─supervisor.service
                       │ └─22453 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
                       ├─redis-server.service
                       │ └─22546 /usr/bin/redis-server 127.0.0.1:6379       
                       └─rsyslog.service
                         └─332 /usr/sbin/rsyslogd -n

**Comment by mveerdon** [comment]
@Kaian changing the user and provider SIP proxy ip address helps, but at the end I want to make use of public IP address offcourse.

How can this been done, when I use associations between public <> private (using Amazon AWS -> Elastic IP)?

Marty

**Comment by Kaian** [comment]
HI @mveerdon 

My experience in AWS is little to none, but a quick search leads us to [this old post](https://lists.kamailio.org/pipermail/sr-users/2015-May/088143.html)

We use two kamailio, so try updating these files:

- /etc/kamailio/proxyusers/kamailio.cfg
- /etc/kamailio/proxytrunks/kamailio.cfg

I don't know if this will work, because we've neved tested the solution in AWS, but try changing the listen line from:
`listen=udp:IP:SIP_PORT`
to
`listen=udp:X.X.X.X:SIP_PORT advertise IP:SIP_PORT`

where X.X.X.X is your private address.

And restart both proxies
```
systemct restart kamailio@users
systemct restart kamailio@trunks
```

Regards!

**Comment by mveerdon** [comment]
@Kaian I changed the global parameters
listen=udp:172.31.35.201:SIP_PORT advertise x.x.x.x:SIP_PORT
listen=tcp:172.31.35.201:SIP_PORT advertise x.x.x.x:SIP_PORT
listen=tls:172.31.35.201:SIPS_PORT advertise x.x.x.x:SIPS_PORT

The result is

> systemctl restart kamailio@users
root@ip-172-31-35-201:/etc/kamailio/proxyusers# journalctl -xn
-- Logs begin at Thu 2017-07-20 11:15:53 UTC, end at Fri 2017-07-21 09:11:08 UTC. --
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27531]: ERROR: rtpengine [rtpengine.c:2540]: rtpp_test(): proxy did not respond to ping
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27520]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27533]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27522]: ERROR: rtpengine [rtpengine.c:2636]: send_rtpp_command(): can't send command "ping" to RTP proxy <udp:127.0.0.1:22223>
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27522]: ERROR: rtpengine [rtpengine.c:2540]: rtpp_test(): proxy did not respond to ping
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27522]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27531]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27527]: ERROR: rtpengine [rtpengine.c:2636]: send_rtpp_command(): can't send command "ping" to RTP proxy <udp:127.0.0.1:22223>
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27527]: ERROR: rtpengine [rtpengine.c:2540]: rtpp_test(): proxy did not respond to ping
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27527]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
root@ip-172-31-35-201:/etc/kamailio/proxyusers# 
root@ip-172-31-35-201:/etc/kamailio/proxyusers# 
root@ip-172-31-35-201:/etc/kamailio/proxyusers# 
root@ip-172-31-35-201:/etc/kamailio/proxyusers# systemctl restart kamailio@trunks
root@ip-172-31-35-201:/etc/kamailio/proxyusers# journalctl -xn
-- Logs begin at Thu 2017-07-20 11:15:53 UTC, end at Fri 2017-07-21 09:11:18 UTC. --
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27581]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27579]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27585]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27556]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27587]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27590]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27592]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 systemd[1]: Started Kamailio - the Open Source SIP Server.
-- Subject: Unit kamailio@trunks.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kamailio@trunks.service has finished starting up.
-- 
-- The start-up result is done.
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27583]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27594]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
root@ip-172-31-35-201:/etc/kamailio/proxyusers#

**Comment by mveerdon** [comment]
`systemctl restart kamailio@users
root@ip-172-31-35-201:/etc/kamailio/proxyusers# journalctl -xn
-- Logs begin at Thu 2017-07-20 11:15:53 UTC, end at Fri 2017-07-21 09:11:08 UTC. --
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27531]: ERROR: rtpengine [rtpengine.c:2540]: rtpp_test(): proxy did not respond to ping
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27520]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27533]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27522]: ERROR: rtpengine [rtpengine.c:2636]: send_rtpp_command(): can't send command "ping" to RTP proxy <udp:127.0.0.1:22223>
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27522]: ERROR: rtpengine [rtpengine.c:2540]: rtpp_test(): proxy did not respond to ping
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27522]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27531]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27527]: ERROR: rtpengine [rtpengine.c:2636]: send_rtpp_command(): can't send command "ping" to RTP proxy <udp:127.0.0.1:22223>
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27527]: ERROR: rtpengine [rtpengine.c:2540]: rtpp_test(): proxy did not respond to ping
Jul 21 09:11:08 ip-172-31-35-201 /usr/sbin/kamailio[27527]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
root@ip-172-31-35-201:/etc/kamailio/proxyusers# 
root@ip-172-31-35-201:/etc/kamailio/proxyusers# 
root@ip-172-31-35-201:/etc/kamailio/proxyusers# 
root@ip-172-31-35-201:/etc/kamailio/proxyusers# systemctl restart kamailio@trunks
root@ip-172-31-35-201:/etc/kamailio/proxyusers# journalctl -xn
-- Logs begin at Thu 2017-07-20 11:15:53 UTC, end at Fri 2017-07-21 09:11:18 UTC. --
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27581]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27579]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27585]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27556]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27587]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27590]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27592]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 systemd[1]: Started Kamailio - the Open Source SIP Server.
-- Subject: Unit kamailio@trunks.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kamailio@trunks.service has finished starting up.
-- 
-- The start-up result is done.
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27583]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
Jul 21 09:11:18 ip-172-31-35-201 /usr/sbin/kamailio[27594]: INFO: rtpproxy [rtpproxy.c:1605]: rtpp_test(): rtp proxy <udp:127.0.0.1:22222> found, support for it enabled
root@ip-172-31-35-201:/etc/kamailio/proxyusers# `

**Comment by Kaian** [comment]
So the services have started without errors (well.. the rtpengine is not working, but rtpproxy seems to be up and running).

Does it actually work? Can you register a couple of terminals follwing the [documentation](https://irontec.github.io/ivozprovider/en/internal_calls/god_portal.html)?

**Comment by Kaian** [comment]
Any advances on this? Did you manage to make it work with AWS public IPs architecture?

Thanks for the info!

**Comment by cruzccl** [comment]
Closed due to lack of feedback. Feel free to reopen.

**Comment by kakarata** [comment]
Hola!
Refloating on this to get it working and documented.
I'm new about ivozprovider. So my question Is there any other service in front network besides kamailio and rtpproxy/engine should I need to pay attention about NAT thing? I've used a kamailio/RTP behind NAT before.

Thanks in advance!

**Comment by Kaian** [comment]
Hi!

Not that I'm aware of. 

SIP Proxies + RTP Proxies + Web Interface are the only required exposed services.

Regards!
