### ISSUE TITLE
translations embedded into database

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#218]
As for now, there are at least two tables that had embedded translations: Services and Features. These translations are included as columns.

That is going to be a problem in the future if someday you decide to add more languages to the project.

I understand the need to add those translations to the database because those are translations of dynamic strings. But the way those translations are stored in the database must be redesigned in my opinion.

There must be separated tables with languages and translations somehow.

**Comment by mmadariaga** [comment]
We agree. The translation system we'll be eventually redesigned. The problem is that a lot code is highly coupled to the current translation system, klear for instance. It'll be much easier to tackle once the [migration to doctrine](https://github.com/irontec/ivozprovider/commits/loose-coupling) is done.

**Comment by Kaian** [comment]
Yep, one table column for each language is something that itches me each time I see it (not taking into account the extra empty column). I can't imagine those tables with support for 50 languages :smile: 
Anyway there's no way to fix this, as far as I know, with current portals framework.

These tables use multi-language columns.

- Countries
- Languages
- Pricing Plans
- Routing Patterns
- Services
- Target Patterns
- Timezones
- Features

**Comment by cruzccl** [comment]
Portals framework will eventually change in 3.0 and this won't be a problem anymore (I hope!)
