### ISSUE TITLE
Will this work on debian 9.1?

### ISSUE THREAD

**Issue by samarnath** [irontec/ivozprovider#222]
Will this work on debian 9.1?

**Comment by Kaian** [comment]
Hi @samarnath 

Current stable release is designed and tested under Debian Jessie, but our next major release (2.0.0) will aim to work in the Debian Stretch. There's still a lot to do so it won't be soon, but we'll get there eventually.

I have tested a development environment (not using packages) in Debian Stretch with success (with a couple of manual fixes), but current stable packages most propably won't resolve their dependencies in Debian 9, and if they do, we can't warranty everything works until we test everything more.

Best regards,

**Comment by Kaian** [comment]
Next release will be designed with Debian 9 in mind, so we'll keep current release in Debian 8 and leave Debian 9 for 2.0 release.

Regards
