### ISSUE TITLE
asterisk 'LTS' future?

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#225]
Is the plan to stick with the 'LTS' asterisk release?  more to the point, when the next LTS is released will there be a strong effort to get up to date as soon as possible?

**Comment by Kaian** [comment]
HI @syadnom 

Yep, our plan is to move with asterisk. Currently we have a custom patched version of asterisk 13.10.0, but most of the patches are cosmetic or bugfixes already present in latest brach 13 version, so we'll soon move our patches to asterisk 13.17.0 

We only move to the latest branch version when we have tested it enough, and usually when it fixes problems that can not be easily backported, so we eventually move onwards but it wont happen as new asterisk releases appear.

Best regards

**Comment by syadnom** [comment]
ok, thanks.
