### ISSUE TITLE
ARM? for sip proxy?

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#228]
Does your deb allow for installation on ARM system such as a raspberry pi3?  This would be interesting specifically for the sip proxy

**Comment by Kaian** [comment]
Hi @syadnom 

Right now our repositories only have debs for amd64 and i386, but packages are built with jenkis and [debian-jenkins-glue](https://jenkins-debian-glue.org/) so adding new architectures are quite easy and the building environment is ready for that.

But the only component (if any) from the platform that can fit in a raspberry pi is the media-relay (rtpproxy and rtpengine), so RTP traffic stays near the users' endpoints. In the scenario you commented in #224, it will only improve the traffic between users' endpoints, while external calls (that require transcoding) will still require an application-server.

Application servers, in the other hand, have all the routing process coded in php and if you plan to use them as transcoders they will require quite some power. They can be still compiled for arm for sure, but we won't recommend it (you will also find problems with some binary distributed codecs like g729).

Best regards,

**Comment by syadnom** [comment]
I have customers that could benefit more from on-site proxying (thus removing of the round trip between sip switch and provider) than from transcoding.

I like the idea of a raspberry pi 3 as a local media proxy for g711 codec customers that don't need any transcoding.    Most of my customers fit under this category, and some of them I run an on-site freepbx system because the majority of their calls are local.  Some endpoints simply don't work properly with direct media etc so that isn't a reliable option.  A local proxy would completely solve this and would have a very low load.

**Comment by syadnom** [comment]
I've been mixing definitions here, so just correcting.

On site media relaying is what I meant.  I've been using 'proxy' when ivoz jargon seems to only use proxy for the kamailio instance and not for rtp proxy.  I'll update my use of said jargon.

Still, the desire for an arm build for debian/raspbian for just rtpproxy and rtpengine and the other logic is there.

Thanks.

**Comment by syadnom** [comment]
awesome!
