### ISSUE TITLE
pairing application server with sip proxy for near-terminal connectivity?

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#229]
I see explicit mention on putting proxies nearer to terminals to reduce latencies.  Is it possible to pair these with application servers specifically to all that proxy to transcode?  Many of my customers are on consumer cable connections and jitter is high and packet loss (or extreme jitter) causes issues iwth g.711.   I can place the proxy on a high quality connection and have the terminals connect with opus to solve this *BUT* providers don't yet support opus so I must transcode at the proxy to make this a viable model.  This design isn't layed out in the docs so I'm not sure if putting application/asterisk with the 'remote' proxy is within the model.

I'm thinking 2 databases in 2 different locations, but application servers and proxies in more locations.  I have some multi-tenant locations that I would like to have all these services on-site while still being part of the overall cluster.

**Comment by Kaian** [comment]
Hi @syadnom

I understand sip proxy as media relay here. If I'm wrong, then all I'm gonna say has no sense :sweat_smile: 

Following what I've said in #228, you can distribute Application Servers and Media relays to different locations, but the static assigment of what Application Server and Media relay uses each company must be done manually by the Global platform administator right now.

If that isn't a problem, then yes, you can have for example 3 application servers and 3 media relays and distribute them in pairs in 3 different cities, manually assigning what will use each company based on its location.

We usually install media relays with sip proxy profile (kamailios), but it should work with any other profile (for example application servers), altough it will require some testing.

Thanks for your feedback in all these issues!

Best regards

**Comment by syadnom** [comment]
I just want to be clear on what you're saying.  If I put a media relay at a customer's site, I have to assign their devices to use that otherwise they will just some random media relay that could be at any site?

Is there a model to set a primary (the on-site) and a failover option (failover use 'global' config)?

**Comment by cruzccl** [comment]
We close this issue as it is already answered in #240 

Regards,
