### ISSUE TITLE
Rating Plan Not Found

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2342]
### Description

Hello, whenever I add a residential client and add it to the "rating plan" I have to press CTRL F5 for the plan to appear in the client, and after entering the rating plan and simulating a call I get the error: RATING_PLAN_NOT_FOUND, I also get the error in the proxytrunk.
Thanks

- IvozProvider version:  - Last 3.2.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Problem reproduction: Brand Configuration>>Residential>>Add Residential Client>>List of Rating Plans>>Add Rating Plan>>retur in List of Residential Clients>>List of Rating Plans>>Simulate a call and receive error: RATING_PLAN_NOT_FOUND

Resolution: After rebooting the server, I can simulate the call and also make calls.

Log web interface and proxytrunks:  https://i.postimg.cc/ryYZMzts/error-rate-plan.png

**Comment by Kaian** [comment]
Hi!

I was unable to reproduce this.

Reloading cgrates is done by a worker started by supervisor. Check the worker is running and reloads cgrates when a change in rating configuration is done.

```
# supervisorctl status cgrates:cgrates-0
cgrates:cgrates-0                RUNNING   pid 3193676, uptime 0:00:11
```

When you assign a rating profile to a residential client, you should see something like this in logs.

```
ago 09 11:58:32 halliday-dev-kaian php.changelog[3193699]: changelog.INFO: CommandWasExecuted > API::post([false,["id"],"Ivoz\\Provider\\Domain\\Model\\RatingProfile\\RatingProfile","application\/json","api_rating_profiles_post_collection",null,{"activationTime":"CURRENT_TIMESTAMP","company":3,"ratingPlanGroup":"1"}]) [] []
ago 09 11:58:32 halliday-dev-kaian php.changelog[3193699]: changelog.INFO: EntityWasCreated > Ivoz\Provider\Domain\Model\RatingProfile\RatingProfile#1 > {"activationTime":"2023-08-09 09:58:32","companyId":3,"ratingPlanGroupId":1,"id":1} [] []
ago 09 11:58:32 halliday-dev-kaian php.changelog[3193699]: changelog.INFO: EntityWasCreated > Ivoz\Cgr\Domain\Model\TpRatingProfile\TpRatingProfile#1 > {"tpid":"b1","loadid":"DATABASE","direction":"*out","tenant":"b1","category":"call","subject":"c3","activation_time":"2023-08-09 09:58:32","... [] []
ago 09 11:58:32 halliday-dev-kaian worker[3193823]: workers.INFO: ApierV1.LoadTariffPlanFromStorDb job payload array (   'tpid' => 'b1',   'notifyThresholdForAccount' => NULL,   'disableDestinations' => true, ) [] []
ago 09 11:58:32 halliday-dev-kaian worker[3193823]: workers.INFO: ApierV1.LoadTariffPlanFromStorDb job Reloading Tpid b1 through CGRateS API [] []
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: CGRateS <aabf777> [3193774]: ApierV1.LoadTariffPlanFromStorDb called for "b1"
ago 09 11:58:32 halliday-dev-kaian httpd[671]: 10.177.105.12 - - [09/Aug/2023:11:58:32 +0200] "POST /api/brand/rating_profiles HTTP/2.0" 201 778 "https://10.60.75.32/brand/residential/3/rating_profiles/create" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: CGRateS <aabf777> [3193774]: ApierV1.LoadTariffPlanFromStorDb, validate loaded data
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: CGRateS <aabf777> [3193774]: ApierV1.LoadTariffPlanFromStorDb, clean up unused rating plans and rating profiles
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: CGRateS <aabf777> [3193774]: ApierV1.LoadTariffPlanFromStorDb, write data to Redis
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Destinations: skip
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Reverse Destinations: skip
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Rating Plans: 1
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Rating Profiles: 1
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Action Plans: 0
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Account Action Plans: 0
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Action Triggers: 3
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Shared Groups: 0
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 LCR Rules: 0
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Actions: 1
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Account Actions: 3
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 Derived Chargers: 1
ago 09 11:58:32 halliday-dev-kaian cgr-engine[3193774]: 2023/08/09 11:58:32 CDR Stats Queues: 0
[...]
```

Be aware that at least one reboot after install is required to start all sevices. 
Does this still happen after the first initial reboot?


Regards

**Comment by dbbrito** [comment]
Hello Kaian, I installed ivoz via apt-get, is there any difference in installing the packages and the ISO image?
Because really this service is not working, see:

supervisorctl status cgrates
cgrates: ERROR (no such process)

supervisorctl status cgrates:cgrates-0
cgrates:cgrates-0                FATAL     Exited too quickly (process log may have details)

Could this be why the low balance notification emails and prepaid mode are not working?

Any command to enable on startup or restart this service? This error happens if it is installed with the ISO image, is it recommended to install it using the iso?
Thanks

**Comment by dbbrito** [comment]
Kain, I just tested with the iso image, and the service actually goes up.

supervisorctl status cgrates:cgrates-0
cgrates:cgrates-0                RUNNING   pid 857, uptime 0:02:11

There should probably be other improvements from other services using the ISO, I think you should always recommend the ISO.

If I migrate the current mysql database to this server that I just installed, will the iso work? 

Had I known I would have used the ISO from the start, and probably wouldn't have had so many problems.

Thanks Kaian

**Comment by Kaian** [comment]
Hi!

So the problem is more related to that cgrates worker crashing.

Task are enqueued in redis server, and the worker connects to redis and checks if there is a pending task. If there are not pending task of its type, then it waits until a task is received. 

Open a `journalctl -f` in one terminal to check logs and run in another:

```
/usr/bin/php /opt/irontec/ivozprovider/microservices/workers/bin/cgrates-reloader
 ```

multiple times until it simply keeps running (it will be in that wainting state). If that doesn't happen, some error will be happening in the logs. Take into account that there will be some reload task in redis enqueued, so you will have to run the command multiple times until an error is displayed or the script stays alive running.


Regards

**Comment by dbbrito** [comment]
Kaian, after several reload attempts and a reboot, the service came up and the RATING_PLAN_NOT_FOUND error was fixed.
Thanks
