### ISSUE TITLE
Evaluate using CGrates as billing engine

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#236]
Current billing logic is a quite basic home-made implementation to achieve the basic challenges of this complex world.

If we want to add more advanced billing features (such as prepaid billing, first X seconds for free, etc.), we have two approaches:

- Evolve current home-made logic.

- Using a third-party software.

We think [CGrates](http://www.cgrates.org) is a great software and can fit our needs :)

This issue aims to evaluate this approach.

**Comment by flantel** [comment]
+1 for CGRates! We are looking to move all our rating over to it.

**Comment by Kaian** [comment]
IMHO, I think this should be moved to 2.0, and complety replace current home-made tarification process with cgrates rather than supporting two ways to tarificate calls.

**Comment by cruzccl** [comment]
Fixed in #374
