### ISSUE TITLE
Active Calls

### ISSUE THREAD

**Issue by arsenieciprian** [irontec/ivozprovider#2372]
Active calls does not display correct information on login, it starts with 0 calls and then slowly is displaing new calls , also on dashboard 0 calls are displayed even if platform have a few calls  
---

- IvozProvider version: 

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X ] Web Interface
    - [ ] API
    - [ ] Other

**Comment by Kaian** [comment]
Hi!

This was fixed in https://github.com/irontec/ivozprovider/pull/2483 and should be already available in 4.0.2

Thanks for reporting!

Best regards
