### ISSUE TITLE
Media-relay sets and failover between sets

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#240]
Like many providers, I have customers on a number of different internet carriers.  Usually 2-3.  It makes a LOT of sense to have 3 media handlers, one on each carrier. 

For this to be useful without statically assigning things, there would have to be some priority for call distribution.  

Clients should be routed to the best proxy for them via some mechanism.  Could be a manual DNS-SRV configuration preferring the best connection for them, or by having each proxy attempt a latency test between their source address etc.  Then, calls should be distributed by the best proxy that is 'up'.

I think this also solves on-site proxies.  The devices would get ~1ms latency to that proxy and should prefer it, but failover if it's down.

thoughts?

**Comment by cruzccl** [comment]
Hi @syadnom 

I think there is a misunderstanding in IvozProvider different profiles :thinking: 

These are the current IvozProvider profiles that handle SIP sessions:

#### Application servers (AS-es)

This profile runs Asterisk and provides all the PBX related features (IVRs, voicemail, etc.). This profile can be scaled to increase the platform CPS limit.

#### Proxy servers

Machines running this profile run 2 Kamailio instances: KamUsers for UACs and KamTrunks for carriers.

They can handle thousands of concurrent SIP sessions so there is no need to scale them: there is always one Kamailio running for users and one Kamailio running for carriers. This profile cannot be scaled.

As they talk SIP (no media handling), latency is not as important as for media-relays described below.

#### Media relays

Machines running this profile run rtpproxy+rtpengine instances. This software relays the RTP flow of established sessions:

- It can be scaled to increase call-concurrency. As all media sessions relay on them once the call has been established, adding more media-relays allow handling more concurrent calls.

- It can be scaled and grouped in sets to minimize the latency to UACs, allowing geographic scaling. I think this is the key concept of your question.


<br><br>

Thus, the latency that has to be reduced to the minimum to guarantee a good user experience is the one between the media relay and the endpoints (both company UAC and carrier), not the one between the endpoints and the proxy.

The current approach allows grouping media-relays in sets and assigning them to companies:

_e.g. 3 media-relays on Germany to handle RTP streams of german companies_

This assignation could have been made by PeeringContract (or even by user), but making it by company seemed an easier approach to us.

Sorry for the length of the explanation, but I needed to separate responsibilities of each profile first to answer to your question :)

Regards,

**Comment by syadnom** [comment]
cruz, the misunderstanding was me using the wrong terminology, ie sip proxy vs media relay.

So, the correction here is:

Have customers have a priority media relay on-site, and a secondary in case the on-site fails.

What isn't ideal is the grouping of relays into sets to assign to tenants without having some priority.

so, a customer would just use the standard 2 sip proxies hosted in the datacenter(s), but would have a priority for media replays being like host:priority for example:
(onsite:1, default:10) which means always use the single on-site relay and if that fails, use whatever the system default is
(onsite:1, DCA15:5, DCB7:6, default:10) meaning onsite, then DC 'A' host 15 priority 5, then DC 'B' host 7 priority 6, finally fall back to system default.


I hope that's more clear.

I might configure something like 1 on-site media relay and 1 VM at the datacenter dedicated to a customer, but I would still need there to be a priority because I don't want calls randomly handled in the datacenter.

The catalyst for this type of request is using light-weight hardware on site like a raspberry pi.  If it's only handling relay duties, a pi could handle many dozens of calls.  The pi could fail, or could get unplugged or swiped etc so the fallback is necessary, don't want a single point of failure.

One last scenario here would be having 2 internet connections.
ISP1-Relay1
ISP2-Relay2

and the customer would need something like (Relay1:1, Relay2:2, default:10) so that ISP1 was the preferred connection by virtue of Relay1 being connected to it, ISP2-Relay2 would be the backup.    If I understand rtpproxy and rtpengine, the on-site phones would be using the rtproxy's LAN address for sip contact so this would be a functional configuration without resorting to adding a bunch of failover routing etc.

**Comment by cruzccl** [comment]
Hi @syadnom 

Unfortunately, Kamailio rtpproxy module does not support assigning priorities to media-relays within sets.

As explained [here](http://kamailio.org/docs/modules/devel/modules/rtpproxy.html#idp48050372), weights can be assigned to them to control how many calls they handle inside their set (```A socket with a weight of 2 will be chosen twice as often as one with a weight of 1```) but you cannot implement failover to use a media-relay only if the preferred one is faulty.

Nevertheless, you could add the local media-relay with high weight (e.g. 99) and the remote media-relay with low weight (e.g. 1): this way, when both are avaiable most calls will be handled by the local media-relay but if it is down, all calls will be handled by the remote one. I don't know which is the highest value for weight nor if assigning a weight of 0 is allowed (meaning _do not use it unless it is the only one available_).

IvozProvider does not assign weights to media-relays within a set, but you can make some tests to see if this workaround could work.

Regards,
