### ISSUE TITLE
Problem adding credit balance new interface 3.3.0

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2402]
### Description

Hello, I used version 3.2.0 normally without any problems, but I made the mistake of updating Debian and it automatically updated ivozprovider to 3.3.0, and now I can't add credit to any customer. Do you have any predictions for this correction, or any other way to add credit?
Thanks

- IvozProvider version:  - Last 3.3.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [X] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Problem reproduction>>https://ip/platform/brands>>Impersonate>>Billing>>Prepaid Balances>>Balance Operations>>Amount + 10.00 SEND  and the value is simply not added to the balance or in Balance Movements

**Comment by Kaian** [comment]
Fixed in #2410

Thanks for reporting this bug!
