### ISSUE TITLE
Not play call recordings by pressing PLAY through the browser version 3.3.0

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2405]
### Description

In version 3.3.0 we are unable to play call recordings by pressing PLAY through the browser, so to listen to the recordings we need to download all the messages.
![image](https://github.com/irontec/ivozprovider/assets/9949166/2c998480-c0c1-4c93-a477-7fdeae7b4cd4)
Thanks

- IvozProvider version:  - Last 3.3.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

**Comment by Kaian** [comment]
Hi!

We were able to reproduce this issue and a fix is in progress for next release.

Thanks a lot for reporting!
