### ISSUE TITLE
BUG: Several options cannot be selected in the new theme or not visible

### ISSUE THREAD

**Issue by MichaelSTK** [irontec/ivozprovider#2422]
### Description
Several options cannot be selected in the new theme

Add new user, pbx, residential etz
- No language selection
- Country code not propper text
- No numeric transformation selection

Edit/Add brand
- No language selection
- Currencies not propper text

Brand provider - Add new DDI Provider
- No numeric transformation selection

Brand - Billing - Rating Plan groups
- After adding a new plan, name and description is not visible

![ivozprovider](https://github.com/irontec/ivozprovider/assets/116265370/5e296379-5b94-4040-ad41-8c73425e87ad)

- IvozProvider version: 3.3~3.3.0~20231003.797~b5c9a32+halliday all - Virtual standalone package

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [x] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
New installation, in the classis theme no problem, only in the new theme (Looks really great)

**Comment by Kaian** [comment]
Hi!

I'm unable to reproduce this problem yet. A few questions to bring some light:

- Have you rebooted the box after initial install?
- Is there any error message in machine journal when you enter that screen? (check with journalctl -p err -f)
- Are you able to debug the requests using Browser inspector and check the responses?

Regards

**Comment by MichaelSTK** [comment]
Hi Kaian

Thanks for your reply.

- _Have you rebooted the box after initial install?_ - I have rebooted several times
- journalctl -p err -f
`-- Journal begins at Wed 2021-09-15 11:02:55 CEST. --
Nov 22 11:11:52 localhost /usr/sbin/kamailio[1046]: ERROR: <core> [core/tcp_read.c:1476]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7f5cbe59a8a8 r: 0x7f5cbe59a9d0 (-1)
Nov 22 11:13:32 localhost sshd[132127]: error: kex_exchange_identification: Connection closed by remote host
Nov 22 11:15:46 localhost worker[131104]: workers.ERROR: redis blPop error on channel CgratesReload [] []
Nov 22 11:17:58 localhost sshd[132182]: error: kex_exchange_identification: Connection closed by remote host
Nov 22 11:20:02 localhost worker[131141]: workers.ERROR: redis blPop error on channel RpcCallRetryOnError [] []
Nov 22 11:20:04 localhost worker[131142]: workers.ERROR: redis blPop error on channel AsteriskDialplanReload [] []
Nov 22 11:20:06 localhost worker[131144]: workers.ERROR: [INVOICER] Error was: redis blPop error on channel InvoicesCreate [] []
Nov 22 11:20:06 localhost worker[131143]: workers.ERROR: redis blPop error on channel AsteriskHintUpdate [] []
Nov 22 11:20:08 localhost worker[131145]: workers.ERROR: redis blPop error on channel MultimediaEncode [] []
Nov 22 11:20:15 localhost worker[131146]: workers.ERROR: redis blPop error on channel RatesImport [] []
`
- _Are you able to debug the requests using Browser inspector and check the responses?_ - Dont know how to do, Can I send you a private message with a username and password so you can take a look for yourself?

Regards

**Comment by MichaelSTK** [comment]
I have send you a email on k...@iron with login details.

**Comment by Kaian** [comment]
Hi!

I have tested the portal and found no issue while creating a new vPBX:

https://you-domain.nl/brand/vPbx/create 

![image](https://github.com/irontec/ivozprovider/assets/800069/272968db-fa70-46bf-923f-eec3538820dd)

**Comment by MichaelSTK** [comment]
Hi.

Thanks for testing

I tested Firefox, Opera, Google Chrome, all with the same result.

- Any idea how this could be possible?
- What could the error messages possibly mean?

Kind regards
Michael
![portalscreen](https://github.com/irontec/ivozprovider/assets/116265370/a2f29e3d-4069-4f35-8d2f-a36c69d06cb2)

**Comment by MichaelSTK** [comment]
I also have some problems with calling out "No valid Gateway", could this be related to the above error messages? (I reported this problem in the google group)

**Comment by MichaelSTK** [comment]
![mobilescreen](https://github.com/irontec/ivozprovider/assets/116265370/4ff5939c-14d0-428d-ba72-293cbaa0e04a)

On my mobile same problem, maby fonts?

**Comment by MichaelSTK** [comment]
2 fields that are not visible in the classis version, but are visible in the new one.

So I cannot adjust out of schedule configuration.

![portalscreen2](https://github.com/irontec/ivozprovider/assets/116265370/ab631070-2053-4c65-aa07-531076fd4b3c)

**Comment by Kaian** [comment]
All sections seems to work for us,

- Have you tried to access the portal using an private tab?
- Have you tried cleaning the browser cache?
- Could you try to debug the request using the browser inspector (F12 for chrome) and check the response from the server for those requests (language, country, ...)?

Regards

**Comment by MichaelSTK** [comment]
Hi

_Have you tried to access the portal using an private tab?_
Yes just now, but same problem
![portalscreen](https://github.com/irontec/ivozprovider/assets/116265370/ca722be5-8847-440e-bdcd-cd63c6a1c378)

_Have you tried cleaning the browser cache?_
Yes, but also tryed other devices

_Could you try to debug the request using the browser inspector (F12 for chrome)_
Is this what you mean?
![portalscreen2](https://github.com/irontec/ivozprovider/assets/116265370/fef054ae-5395-4608-b578-8fb9de86219c)

It looks like i can select something but isnt showing the text

Regards

**Comment by Kaian** [comment]
Is there any error displayed in the console tab of the browser inspector?

**Comment by MichaelSTK** [comment]
![portalscreen](https://github.com/irontec/ivozprovider/assets/116265370/ddf6b054-ad35-4358-887f-f902b660699a)

**Comment by Kaian** [comment]
![consoletab](https://github.com/irontec/ivozprovider/assets/800069/ac7cb987-0ed3-40b1-a318-6ed0cb24c376)

**Comment by MichaelSTK** [comment]
![portalscreen](https://github.com/irontec/ivozprovider/assets/116265370/d842c925-a42b-4447-b197-060cd3b1d2d9)
![portalscreen2](https://github.com/irontec/ivozprovider/assets/116265370/c3be3066-ef34-4b2d-b169-deb37092f41d)

**Comment by Kaian** [comment]
Although we have been unable to reproduce this issue, I will keep it open in case someone else is also experimenting this problem.

**Comment by Kaian** [comment]
Hi!

We think we have a solution for this problem. Sadly it could only be implemented in the latest version of the UI library we use for the new portals so I will only be avaible for next 4.x patch version.

Best regards,
