### ISSUE TITLE
CLIP no screening - function

### ISSUE THREAD

**Issue by Net-Spacy** [irontec/ivozprovider#243]
Is it possible to activate a option, that a user is able to set their own outgoing number (DDI) - which is not controlled by us? A lot of users want to have the option (after signing a legal letter) - to set their wished phone number as outgoing number? It's important - that the CLIPns-function is not activated by default.

**Comment by Kaian** [comment]
Hi @Net-Spacy 

With current implementation that's not possible:
- Users has own outgoing DDI enforced (also it can be dynamic assigned using outgoing ddi rules).
- Friend and Retail accounts must have own DDI as presented number or diverted number.

In future development, we'll maybe add an option to override this presented DDI based on used outgoing route, but that enhancement is not yet schedulled in the roadmap.

Best regards
