### ISSUE TITLE
Problem adding Carrier credit balance on new 3.4.0.

### ISSUE THREAD

**Issue by centralip** [irontec/ivozprovider#2449]
### Description

After updated to 3.4.0, cannot handle Carrier balances operation to increase or decrease credit balance. Similar this issue for Client balances was fixed on 3.4.0, but on Carriers balances issue remain. https://github.com/irontec/ivozprovider/issues/2402

Sitted on Brand, Providers, Carriers, clicking for more options on each carrier, Balance Operations, if you add some balance +, then balance still showing the same.

---

- IvozProvider version: 3.4~3.4.0~20231201.850~d4c64dc+halliday

- Related sections:
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [X] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Sitted on Brand, Providers, Carriers, clicking for more options on each carrier, Balance Operations, if you add some balance +, then balance still showing the same.

### Additional Information
Added balace + to Carriers, but then checking mysql table, balances where not added. Only negative:

select * from Carriers;"
+----+---------+-------------+---------+-------------------------+---------+---------------+------------+--------------+------------------+
| id | brandId | description | name    | transformationRuleSetId | balance | calculateCost | currencyId | proxyTrunkId | mediaRelaySetsId |
+----+---------+-------------+---------+-------------------------+---------+---------------+------------+--------------+------------------+
|  1 |       1 |             | Carrier A|                     254 | -0.0250 |             1 |          2 |            1 |             NULL |
|  2 |       1 |             | Carrier B |                     255 | -0.0248 |             1 |          2 |            1 |             NULL |
+----+---------+-------------+---------+-------------------------+---------+---------------+------------+--------------+------------------+

**Comment by Kaian** [comment]
Hi!

Thanks for reporting and following provided bug templates!

I have confirmed this issue in our testing environment and we'll try to fix it for next patch release.

Best regards
