### ISSUE TITLE
SRTP support

### ISSUE THREAD

**Issue by Guigui37** [irontec/ivozprovider#245]
Should be nice to enable SRTP support.
for now, pjsip show endpoint shows:
media_encryption                   : no

Maybe we should start by adding a field in the database ?
Thank you !

**Comment by cruzccl** [comment]
Currently calls are recorded in the media-relay. If SRTP is enabled end-to-end, it won't be possible to record them.

Once #375 is done, rtpengine can handle SRTP/RTP conversion and record the unencrypted call.

**Comment by cruzccl** [comment]
Fixed in #1492
