### ISSUE TITLE
question: Incoming DDI routes vs IVR routes

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#246]
Incoming DDIs can be routed to: users, friends, queues, hunt groups, IVRs, conferences, fax, retails.

IVRs, on the other hand, can be routed to: number, extensions, voicemail.

Is it posible to have more route options in IVRs? friends, queues, hunt groups, ...?

I can create virtual extensions routed to queues or hunt groups to bypass that limitation but it would be a lot easier to configure the route directly in the IVR. Not to mention that after a month it would be a lot easier to understand a configuration that shows a route to queue X than a configuration that shows a route to extension XXX.

If I try a virtual extension routed to a friend it won't work when used as a IVR route.

I would like to have a IVR that depending what the caller dials (1 or 2 for example) it routes the call to one friend or another. I have not been able to do it.

I wonder if those two route options could be the same for both incoming DDIs and IVRs. Users, extensions, number, voicemail, friends, queues, hunt groups, IVRs (a IVR can be routed to other IVR as for now it must be done with a virtual extension), conferences, fax, retails, as route options for both incoming DDIs and IVRs.

**Comment by Kaian** [comment]
Hi @manfer 

_Is it posible to have more route options in IVRs? friends, queues, hunt groups, ...?_

Right now route options and targets for those routes are stored in the entity itself. This was originally an interface limitation that we plan to remove in a future where a Routes table will have all routing options available so entities have just a route id assigned. That's what we call _generic routing_, and while it has no issue in github, it has been in our minds for some time. This introduces huge changes and lots of adaptations to preserve original functionalities, but will allow any routing option available everywhere (while simplifyfing database scheme).

Meanwhile, if you're interested in just evolving one routing option (say IVR ones) it should not be hard (by adding new columns in IVR tables and so on). Or use the extension workaround you mention.

_If I try a virtual extension routed to a friend it won't work when used as a IVR route.
I would like to have a IVR that depending what the caller dials (1 or 2 for example) it routes the call to one friend or another. I have not been able to do it._

This is a bug. If the number you set in the Extension friend value matches one of the Friends pattenrs, call should be routed through that friend. Please create a new issue with this problem.

Best regards and thanks!

**Comment by manfer** [comment]
> This is a bug. If the number you set in the Extension friend value matches one of the Friends pattenrs, call should be routed through that friend. Please create a new issue with this problem.

The extension configuration looks correct. When the extension is dialed directly it routes to the friend. But when I use that extension as route in a IVR the call is hangup.

I will open a new issue.

Thanks.

**Comment by cruzccl** [comment]
Can we close this issue @manfer ?

I think the bug is already solved and the generic router topic will be covered in 2.0.

Regards,

**Comment by manfer** [comment]
Yes of course. Thanks.
