### ISSUE TITLE
No filter date calls panel client

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2460]
### Description

Friends, I can't filter the external calls report in the customer area by day.

- IvozProvider version:  - Last 3.4.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [X] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
In the classic panel version, when I chose the Start time>>Greater than option and clicked inside the next field, it showed a calendar to choose the date and time, but now when entering the field it doesn't show anything, the Search field doesn't search either no data, see attachment.
Thanks
![ivoz vclassic](https://github.com/irontec/ivozprovider/assets/9949166/541d3b47-8663-4d54-8410-d3714ce66ff7)
![ivoz v340](https://github.com/irontec/ivozprovider/assets/9949166/b31db92b-0cd0-4553-9842-9349fcc51af9)

**Comment by mmadariaga** [comment]
Hi @dbbrito,

I have not been able to reproduce the problem. A calendar widget is not provided yet, but you should be able to type the value into the text field. Press `+` and `apply` then.

Alternatively, use the following url: `platform/billable_calls?startTime[after]=2023-12-23%2012%3A06%3A54`

**Comment by dbbrito** [comment]
> Hi @dbbrito,
> 
> I have not been able to reproduce the problem. A calendar widget is not provided yet, but you should be able to type the value into the text field. Press `+` and `apply` then.
> 
> Alternatively, use the following url: `platform/billable_calls?startTime[after]=2023-12-23%2012%3A06%3A54`

Yes, the complicated part is explaining how to proceed to the end customer, the calendar is much needed and is more intuitive. Thank you very much mmadariaga

**Comment by Kaian** [comment]
Hi!

This have been fixed in 4.1.0 and filtering using Dates should be now easier.

![image](https://github.com/user-attachments/assets/d50ed607-331b-491f-8114-fb701ced6099)


Best Regards
