### ISSUE TITLE
rtpengine error after updating

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2461]
### Description

Friends, I updated ivoz, and I thought it was strange that it only had the rtpengine update, but I continued with the update and now I'm still getting an error that I don't remember seeing before.

- IvozProvider version:  - Last 3.4.0

- Related sections: 
    - [X] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
See the attached image for errors, should I be worried, is there any configuration I missed?
Thanks
![error rtpengine](https://github.com/irontec/ivozprovider/assets/9949166/48dac58b-5306-4d51-9bfe-07e6e2388258)

**Comment by Kaian** [comment]
Hi!

This is usually generated when a loop in RTP packets are detecetd due to wrong configuration or bad behaviour of one of the endpoints. I don't think this is a bug or something ivozprovider or rtpengine could fix, but an environmental issue with one of your peers.

Best regards,

**Comment by Kaian** [comment]
We're closing this. It seems an environment issue rather than a software malfunction.

Best regards
