### ISSUE TITLE
Voicemail for Residential devices doesn't show email or attachSound fields

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2464]
### Description

Friends, we discovered that residential customers do not have two voicemail configuration fields.

- IvozProvider version:  - Last 3.4.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
When the customer accesses the voicemail settings, the email fields and the field to attach yes or no to the voicemail message are missing.
See the attached images for the difference.
Thanks and regards
![voicemail1](https://github.com/irontec/ivozprovider/assets/9949166/0a150112-637d-4244-9df1-2879ee4cec25)

![voicemail2](https://github.com/irontec/ivozprovider/assets/9949166/f13f17a8-40b9-4938-b90b-b355249f4a77)

**Comment by Kaian** [comment]
Hi!

Thanks for reporting, I can confirm those fields should be visible to be able to configure the email that will receive the notifications. We'll try to fix this for next release.

Best regards,
