### ISSUE TITLE
Missing domain field when creating the Brand

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2465]
### Description

No add domain field when creating the Brand.

- IvozProvider version:  - Last 3.4.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
In the classic version, when creating the brand with Features activated, the domain field appears, but in the new interface it is not shown.

Thanks and regards

**Comment by Kaian** [comment]
Hi!

Thanks for reporting, I can confirm this field should be visible to be able to configure the domain that residential and retail client will use. We'll try to fix this for next release.

Best regards,

**Comment by Kaian** [comment]
Fixed in #2480
