### ISSUE TITLE
IVR routed to extension routed to a friend

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#247]
I have created a extension routed to a friend just to try to use it as route in a IVR.

When I dial that extension directly from a user of the company it routes the call correctly to the friend.

But when I use that extension as a route in a IVR the call is hangup.

**Comment by Kaian** [comment]
Hi @manfer 

I have tested your setup and it actually fails with the error _Friend is not properly defined. Check configuration._

The commit above should fix this problem. Most probably this will be backported to 1.5.0

Best regards and thanks for reporting!

**Comment by Kaian** [comment]
Merged into stable in d092bec
