### ISSUE TITLE
outgoing routes company parameter

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#253]
When configuring outgoing routes you have to configure the company for that route.

We can assign the route to one company or to all of the companies.

We can't assign the route to three, five, two, six, four, or whatever number of companies.

This means that if I have 10 companies and I want only 5 to be able to call to Spain through same peering contract, I have to create 5 outgoing rules, one for each company.

The underlying database stores this data as one line with NULL value in company column if the route is applied to all companies or one line per company with the company ID in the company column if the route is applied to several companies.

It would be a lot more manageble if the company select is a multiselect field so we can choose several companies at the same time.

This maybe could be just a frontend change. In the outgoing routes list view the database lines would have to be grouped by (company+peering contract) and when edited the company field would have to be a multiselect field. The underlying database and outgoing routing model would not be changed at all.

**Comment by cruzccl** [comment]
Hi @manfer 

Thanks for you suggestion, you are totally right: this section needs several improvements.

One of these improvements will be the one you propose, but we have in mind evolving outgoing routing logic to support new features, such as real LCR call distribution.

This will need a parcial rework, planned for 2.0 version (not so far away) so we prefer waiting until this new major version arrives :)


Thanks and regards,

**Comment by manfer** [comment]
Great. Thanks.

**Comment by cruzccl** [comment]
We close this issue: 2.0 will have such a rework in routing logics that this is just a detail (that will be taken into account if possible).

Regards!
