### ISSUE TITLE
Text problem 

### ISSUE THREAD

**Issue by damidani** [irontec/ivozprovider#2534]
### Description

When I'm editing a brand, for example, some text isn't displayed, such as features and language etc... see screen.
I have no error in my chrome console and I've tried putting the url in portal platform but nothing changes.
---

- IvozProvider version: 3.4-3.4.1

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [X] Web Interface
    - [ ] API
    - [ ] Other
<img width="435" alt="Capture d’écran 2024-03-01 à 23 02 30" src="https://github.com/irontec/ivozprovider/assets/29334932/785b81d1-a69f-4f8e-9097-54714c340f49">
<img width="573" alt="Capture d’écran 2024-03-01 à 23 02 52" src="https://github.com/irontec/ivozprovider/assets/29334932/498061b3-12cf-4aa1-a803-4a5ac4f593d3">

**Comment by Kaian** [comment]
Hi,

Thanks for reporting following the provided template.

This looks like a duplicate from https://github.com/irontec/ivozprovider/issues/2422 

In that issue, the reporter have some values like countries, languages or currencies not properly displayed. He provided some credentials to his portal and when we entered everything was working fine and all fields were filled with the correct data. Not sure if this is a browser dependant problem or some browser language issue, but doesn't seem to be an easy to reproduce bug for us.

Regards

**Comment by Kaian** [comment]
Duplicated from #2422 

Please check https://github.com/irontec/ivozprovider/issues/2422#issuecomment-1983118889 

Best Regards
