### ISSUE TITLE
doc: wrong decimal tip

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#257]
On pricing plans documentation we can read

> Floating number must be quoted with double quotes and use a comma as decimal separator.

But the sample CSV file provided uses dot as decimal separator and it is correctly imported.

I did not try with a CSV file with commas as decimal separator so I don't know if both comma and dot works as separator or just dot.

The doc is not accurate any way and should be fixed.

Same on spanish doc.

**Comment by cruzccl** [comment]
Totally agree, we will check it and fix it :+1: 

Thanks for reporting, regards.

**Comment by manfer** [comment]
By the way if dot is the correct decimal separator most probable the quotes are not mandatory any more
