### ISSUE TITLE
Typo in debian/ivozprovider-web-admin.postinst

### ISSUE THREAD

**Issue by kamils85** [irontec/ivozprovider#2574]
### Description

---

- IvozProvider version: 4.0.2

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [x] Other

### Troubleshooting
`apt upgrade` on standalone installation 

### Additional Information
I believe there is a typo in file  [debian/ivozprovider-web-admin.postinst](https://github.com/irontec/ivozprovider/blob/86746f6650d74d9606ed88e646a4f341886b1f0b/debian/ivozprovider-web-admin.postinst) causing this to show a warning message while upgrading via debian repo.
```
Setting up ivozprovider-web-admin (4.0~4.0.2~20240313.1019~86746f6+tempest) ...
chown: warning: '.' should be ':': ‘www-data.www-data’
```

**Comment by Kaian** [comment]
Hi!

Thanks for reporting!

Yep, although it's just a warning, it's also easy to fix.

Regards!
