### ISSUE TITLE
how to change the password for globe admin

### ISSUE THREAD

**Issue by zhulizhong** [irontec/ivozprovider#274]
Hello:
I forgot the globe admin password, how to rest it ?

**Comment by Kaian** [comment]
Hi @zhulizhong 

Default credencials are admin/changeme

You could update database entry to [its default](https://github.com/irontec/ivozprovider/blob/5e4403d03a57818e20db9528efd8a9a4e754c1a2/scheme/deltas/001-oasis.sql#L1579)

Regards
