### ISSUE TITLE
DDI Provider Addresses not evaluated |No Inbound calls

### ISSUE THREAD

**Issue by dsmaldone** [irontec/ivozprovider#2786]
### Description
Inbound calls from DDI Provider are not going through because [DDI Provider Addresses] are not taken into account in kamailio routing at lines

```
 419     if (!$var(is_from_inside) && !has_totag() && !allow_source_address_group()) {
 420         xwarn("[$dlg_var(cidhash)] Inbound initial request from $si, not recognized as a valid DDI Provider, 403 Forbidden\n");
 421         send_reply("403", "Forbidden");
 422         exit;
 423     }
```

---

- IvozProvider version:   4.2~4.2.0~20240916.1269~b5628ac+tempest

- Related sections: 
    - [X] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Receive  an Inbound Call with a DDi will show in the log something similar to
`Oct 07 13:59:35] [d8ab9be4] Inbound initial request from 185.243.5.78, not recognized as a valid DDI Provider, 403 Forbidden
`
### Additional Information
The solution was to move from allow_source_address_group() to allow_address_group() passing the source IP and address Port

```
 419     //if (!$var(is_from_inside) && !has_totag() && !allow_source_address_group()) {
 420     if (!$var(is_from_inside) && !has_totag() && !allow_address_group($si,$sp)) {
 421         xwarn("[$dlg_var(cidhash)] Inbound initial request from $si, not recognized as a valid DDI Provider, 403 Forbidden\n");
 422         send_reply("403", "Forbidden");
 423         exit;
 424     }
```

**Comment by cruzccl** [comment]
Hi Danilo,

Both `allow_source_address_group()` and `allow_address_group($si,$sp)` are equal, the change solves your problem due to the Kamailio service restart you make afterwards.

It seems that the problem is related to non-working Kamailio module reloads in your setup, so it cannot be considered a software problem.

Thank you and regards,
