### ISSUE TITLE
ivozprovider v2 debian version

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#280]
Is v2 ment to be installed on debian stretch?

If it is not, are you going to build php 7.0 packages and other needed packages for debian jessie and provide them through packages.irontec.com or add instructions on php 7.0 installation from other repository?

**Comment by Kaian** [comment]
Hi @manfer 

Yep, It will be based on stretch.

We've starting working without a properly communicating the changes, our bad. Check #281.

We recommend you switching to oasis, as bleeding will now be usable for now.

Regards!

**Comment by manfer** [comment]
Great. Thanks @Kaian.

My personal installation is just to test new features before they reach production so probably I decide to install bleeding on a debian stretch virtual machine to have a look from time to time.

I understand it is still soon and maybe it does not work correctly.
