### ISSUE TITLE
delete users/terminals

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#288]
When you try to delete a user or a terminal ivozprovider triggers a confirmation popup.

On that popup it shows only a number that has nothing to do with the details we configure about the user or the terminal but just an internal number that must be the database id of the user or terminal.

This creates no confidence of what you are actually deleting.

Extensions delete feature on the other hand shows correctly details of the selected extensions on the popup and not just an internal number.

**Comment by Kaian** [comment]
Hi @manfer 

This seems to be determined by the default field in the klear model yaml. It seems only a field can be set as default, so I've choosen the name for Users.

This change is quite easy as you can see in the above commit. If you find any other places where this can improve we highly appreciate any contribution (via PR or commenting in this issue).

Also note that PR for 1.x versions are now created from oasis branch and not bleeding.

Thanks a lot for your feedback!!

**Comment by manfer** [comment]
I tried to find out how it could be done with no luck.

Thanks for the fix.

**Comment by Kaian** [comment]
To be honest I found how to solve it by comparing the differences and a bit of luck :sweat_smile:
