### ISSUE TITLE
users: register timeout min value

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#290]
Currently KamUsers forces register expiration to be not higher than 300 [set here](https://github.com/irontec/ivozprovider/blob/b7fd5d7fa55627c41d2ae65cb779ef48469bde50/kamailio/users/config/kamailio.cfg#L67).

This was meant to avoid low expiration times that lead to high SIP REGISTER traffic, so should use min_expires instead of max_expires [(registrar Kamailio documentation).](http://kamailio.org/docs/modules/devel/modules/registrar.html#registrar.p.min_expires)

Evaluate making some changes to achieve the original goal.

**Comment by Guigui37** [comment]
Is this bug only for proxyusers ? I saw some SIP trunks not working properly if I don't ask it to register every 300 seconds, whereas on an other IPBX, 3600 works perfect.

**Comment by cruzccl** [comment]
Hi @Guigui37 

**KamUsers acts as a UAS** here, as it handles incoming REGISTER requests (registrar server). These requests are handled by Kamailio registrar module that controls the negociated expiration time as follows:

- Current configuration: max_expires=300 (min_expires not set, [defaults to 60](http://kamailio.org/docs/modules/devel/modules/registrar.html#registrar.p.min_expires)).

- UAC sends register suggesting a registration time of X seconds in Expire header or expires Contact param, as described in [this section of RFC 3261](https://tools.ietf.org/html/rfc3261#section-10.2.1.1).

- If X is higher than 300, 300 is forced by KamUsers.

- If X is lower than 60, 60 is forced by KamUsers.

- Otherwise, proposed X seconds is accepted.

In other words, registration interval must be between 60 and 300 seconds with current configuration. The proposed change is to adapt this interval to be between 300 (lower values increases SIP traffic) and 1800.


On the other hand, **KamTrunks acts as a UAC**, sending its own REGISTER requests to carriers using [Kamailio UAC module](https://www.kamailio.org/docs/modules/devel/modules/uac.html). The time configured in each Peering Contract register is the one proposed by KamTrunks on outgoing REGISTER requests.

As negotiated expiration time depends on registrar server as explained above (following [the processing described in point 7 of RFC 3261](https://tools.ietf.org/html/rfc3261#section-10.3)), the carrier receiving this REGISTER should force the expiration time it wants (if proposed one is not considered valid).

The problem you describe does not seem to be related to this issue, if you want to troubleshoot your situation SIP traffic should be captured and analyzed to detect:

- If KamTrunks sends REGISTER requests with a right Expires header (or expires param in Contact).
- Which expiration time is negociated following the registrar expiration policy.
- If KamTrunks renews the registration before it expires.

If you detect any misbehaviour there, don't hesitate to open a different issue :)

Regards,
