### ISSUE TITLE
Conflict in Companies database between vpbx and retail type

### ISSUE THREAD

**Issue by Guigui37** [irontec/ivozprovider#292]
If I add a vpbx company with the same name as a retail company, the WebUI gives us the following error: "Error saving record"
Portal logs show the following:
>Sep 22 14:34:40 voip-portal-2 ivozprovider[25506]: 2017/09/22 - 16:34:40 ERR (3): Exception encountered while attempting to save IvozProvider\Mapper\Sql\Companies with an empty primary key  Exception: Mysqli statement execute error : Duplicate entry 'test-1' for key 'nameBrand'
Sep 22 14:34:40 voip-portal-2 ivozprovider[25506]: 2017/09/22 - 16:34:40 DEBUG (7): #0 /usr/share/php/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)#012#1 /usr/share/php/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)#012#2 /usr/share/php/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `Co...', Array)#012#3 /usr/share/php/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('Companies', Array)#012#4 /opt/irontec/ivozprovider/library/IvozProvider/Mapper/Sql/Raw/Companies.php(414): Zend_Db_Table_Abstract->insert(Array)#012#5 /opt/irontec/ivozprovider/library/IvozProvider/Mapper/Sql/Companies.php(62): IvozProvider\Mapper\Sql\Raw\Companies->_save(Object(IvozProvider\Model\Companies), true, true, false, false)#012#6 /opt/irontec/ivozprovider/library/IvozProvider/Mapper/Sql/Raw/Companies.php(335): IvozProvider\Mapper\Sql\Companies->_save(Object(IvozProvider\Model\Companies), true, true, false, false)#012#7 /opt/irontec/ivozprovider/library/IvozProvider/Model/Raw/ModelAbstract.php(905): IvozProvider\Mapper\Sql\Raw\Companies->saveRecursive(Object(IvozProvider\Model\Companies), true, false)#012#8 /opt/irontec/klear/modules/klearMatrix/controllers/NewController.php(146): IvozProvider\Model\Raw\ModelAbstract->saveRecursive()#012#9 /opt/irontec/klear/modules/klearMatrix/controllers/NewController.php(81): KlearMatrix_NewController->_save(Object(IvozProvider\Model\Companies), true)#012#10 /usr/share/php/Zend/Controller/Action.php(516): KlearMatrix_NewController->saveAction()#012#11 /usr/share/php/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('saveAction')#012#12 /usr/share/php/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))#012#13 /usr/share/php/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()#012#14 /usr/share/php/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()#012#15 /opt/irontec/ivozprovider/portals/public/index.php(29): Zend_Application->run()#012#16 {main}
Sep 22 14:34:40 voip-portal-2 ivozprovider[25506]: 2017/09/22 - 16:34:40 CRIT (2): Error saving in new::save for \IvozProvider\Mapper\Sql\Companies [Error saving record]

I think we should have a check on the company name before trying insertion in the database.

**Comment by Kaian** [comment]
That sounds good to me, there are a lot of undefined errors!

This could be done like we did with the users emails (that are unique in the whole platform!) [here](https://github.com/irontec/ivozprovider/blob/oasis/library/IvozProvider/Mapper/Sql/Users.php#L130)

**Comment by manfer** [comment]
Is such a constraint really needed? It is quite a rigid constraint to make it unique on whole platform.

I see on the database there is already a constraint nameBrand for companies and it looks good.

If you want to allow same name for retails and vpbx on same brand I wonder if you just can change that constraint to one that includes the type.

From
`  UNIQUE KEY nameBrand  (name,brandId),`
to
`  UNIQUE KEY nameBrandType (name,brandId,type),`

Not sure if there is any other problem on having same name. Any internal task should be dependant on the entity `id` and not on its `name`. But I don't know the code in depth to know if there is any problem.

User's emails constraint is very rigid either. Users can't login into another brand portal so a constraint per brand should be enough. Anyway It is ok as a user filling same email as another one will rarely happen.

**Comment by Kaian** [comment]
As far as I know, this was implemented in #297 long time ago
