### ISSUE TITLE
suitability of ivoz for delivering trunks to dynamic ip customers

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#296]
I'm looking for a way to deliver SIP channels to customers with dynamic IP addresses for their on-prem pbx.

ivoz appears to have a solution to this in having an rtpproxy on-site for direct media.

Is this something that is doable out-of-box?

host the ivoz cluster in a datacenter, but essentially never handle media there except when a customer's site cant be reached (ie, failover call handling).

key issues here are that most decent orig/term providers send calls to specific IP addresses, *static* IP addresses.  Static IP's have become very very expensive, adding some $25/m to an internet service.  Having the customer's PBX register to kamailio but still get direct media would be a very very solid solution.

I'm not sure how ivoz handles peers as trunks though.

Thanks for any help/advice in advance.

**Comment by Kaian** [comment]
Hi @syadnom !

> Having the customer's PBX register to kamailio but still get direct media would be a very very solid solution.
> I'm not sure how ivoz handles peers as trunks though.

You can provide trunking service in provider with Retail. Retails Accounts are endpoints that only process incoming external calls to DDIs and send outgoing external calls to Contract peerings. Retail accounts can be direct or via register. For the second configuration you can register your customer's PBX so IvozProvider can locate it after ip changes.

Also, note that we have disabled direct media for contract peering in the latest release, so if you want direct media you must change the proxytrunks configuration in pjsip.conf 

Regards!

**Comment by syadnom** [comment]
great, thanks!
