### ISSUE TITLE
core: terminal/friend uniqueness

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#308]
All devices that register to a sip domain must have unique authentication id (name attribute on friends, terminals and retail accounts).

Restricting that for retail accounts is simple because a retail client can only have retail accounts. It can't have terminals nor friends. So the database unique index on name/brand is enough for retail accounts.

But a company can have both terminals and friends. So it can't have two terminals with same name. Easy to handle, it is already a unique index on database (name/domain). It can't have friends with same name. Easy to handle, an unique index can be created on database (name/domain). But, besides, it can't have a terminal and a friend with same name. And this last is not easy to handle right now.

Don't know which is the best way to solve this.

**Comment by Kaian** [comment]
Hi @manfer!

The only possible way to implement this would be to query terminals table for the company before saving in friends mapper and vice-versa. Not to fancy to be honest :thinking: 

As far as I know there is no way to do this using SQL constraints, but I'll dig it a bit. 

Any thoughts @mmadariaga?

**Comment by mmadariaga** [comment]
I don't dislike the idea of triggering a query to ensure that everything is correct before we actually run the insert. 

I would put all those validation methods into one single class and use it then from the mappers involved.

**Comment by Kaian** [comment]
We could also add a unique in ast_ps_aors contact field to ensure user@domain are unique.

This won't work for oasis because this table is updated after saving the friend/terminal, but it may work in 2.0 if all database updates are transactional.

**Comment by Kaian** [comment]
I have fixed this for artemis and will be available in 2.8.0

We won't bother fixing this for oasis, but as @mmadariaga mentions, it could be done by adding an extra query in both Terminals and Mappers _save_ methods.

Regards!
