### ISSUE TITLE
GL258 Translate portals to english/spanish

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#34]
Some fields/parameters are not translated to both languages.

**Comment by Kaian** [comment]
There are lots of untranslated strings through all the software. Some code still have messages in spanish, so this also involves changing sources. This issue will take a long long time.

Please report any **major** wrong translated strings as you find them :smile:

**Comment by Kaian** [comment]
Most of visible labels has been translated.

Please, report any typo or found unstralated string.
