### ISSUE TITLE
Exception on Provisioning templates options

### ISSUE THREAD

**Issue by afernandez2000** [irontec/ivozprovider#354]
In provisioning templates when I click on Load File, restore last backup or Restore default template the server throws an error:

ivozprovider-standalone ivozprovider[1753]: 2017/12/16 - 01:57:22 ALERT (1): syntax error, unexpected '<' (4) in /opt/irontec/ivozprovider/portals/application/controllers/KlearCustomUploadFileController.php +24

ivozprovider-standalone ivozprovider[1750]: 2017/12/16 - 01:57:34 ALERT (1): syntax error, unexpected ',' (4) in /opt/irontec/ivozprovider/portals/application/controllers/KlearCustomRestoreBackupController.php +40

ivozprovider-standalone ivozprovider[1533]: 2017/12/16 - 01:57:37 ALERT (1): syntax error, unexpected ',' (4) in /opt/irontec/ivozprovider/portals/application/controllers/KlearCustomRestoreDefaultController.php +42

**Comment by mmadariaga** [comment]
Hi @afernandez2000,

Thanks for the bug reporting. It should be already fixed in https://github.com/irontec/ivozprovider/commit/bec38d6cdfe0d44bf4fcd9b8806db987c97f31b8
