### ISSUE TITLE
User portal logins not working

### ISSUE THREAD

**Issue by csharp305** [irontec/ivozprovider#355]
I am having a problem with the user portal (company -> user). Each
login attempt to the URL defined at "Portal URLs" under Brand
Configuration fail. I added some debugging to
klear/modules/klear/plugins/Auth.php as well as
irontec/ivozprovider/library/IvozProvider/Mapper/Sql/Users.php to
confirm the password and usernames are being passed correctly. Below
are logs from when the password was set to "Password" as well as a
login attempt. Any guidance would be appreciated.

Password Set:
Dec  1 18:51:43 pbx ivozprovider[30166]: 2017/12/01 - 18:51:43 INFO
(6): edit::save action for mapper:\IvozProvider\Mapper\Sql\Users > PK(3)
Dec  1 18:51:43 pbx ivozprovider[30166]: 2017/12/01 - 18:51:43 INFO
(6): Password set: Password
Dec  1 18:51:44 pbx ivozprovider[30166]: 2017/12/01 - 18:51:44 INFO
(6): model save succesfully for \IvozProvider\Mapper\Sql\Users > PK(3)
Dec  1 18:51:44 pbx ivozprovider[30166]: 2017/12/01 - 18:51:44 INFO
(6): List mapper: \IvozProvider\Mapper\Sql\Users
Dec  1 18:51:44 pbx ivozprovider[30166]: 2017/12/01 - 18:51:44 INFO
(6): 6 elements return by fetchList for:\IvozProvider\Mapper\Sql\Users

Login Attempt
Dec  1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
(6): Auth adapter: IvozProvider\Klear\Auth\Adapter
Dec  1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
(6): Invalid credentials for user csharp2@<[1]domain>
Dec  1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
(6): Invalid credentials using password Password
Dec  1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
(6): LoginError: Array#012(#012    [message] => Usuario o contraseña
incorrectos.#012)
Dec  1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
(6): new KlearLogin
Dec  1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
(6): klearLogin with no extraInfoLoaderClass

DB:

mysql> select email,pass from Users where id=3;
+---------------------------+---------------------------------------------------------------------+
| email                     | pass
                            |
+---------------------------+---------------------------------------------------------------------+
| csharp2@<domain> |
$5$rounds=5000$be972c77$ZhRVxoDp.Mkch.vMNQUZ.vrl8BV2Vx.4TTy55JrfWn/ |
+---------------------------+---------------------------------------------------------------------+
Which is the salt + "Password"

**Comment by Kaian** [comment]
Hi @csharp305 

> Login Attempt
> Dec 1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
> (6): Auth adapter: IvozProvider\Klear\Auth\Adapter
> Dec 1 18:52:11 pbx ivozprovider[30157]: 2017/12/02 - 00:52:11 INFO
> (6): Invalid credentials for user csharp2@<[1]domain>

User portal is a separated application and should not share the same authentication method that administration portals (based on klear framework) so It's quite strange those login attempts errors.

Be sure you have properly configured the portals URL for users: if the portal loader does not match the URL correctly it automatically loads the Main administration portal. You can provide the contents of your BrandsURLs table if you need some hints.

I have attached an image of how the users portal login page looks like. Contrary to the administration portals, it is only translated to spanish, but improving it for new languages shouldn't be too difficult.
![userportal](https://user-images.githubusercontent.com/800069/34202793-20b88284-e579-11e7-806d-458619ef637e.png)

Thanks for reporting!

**Comment by csharp305** [comment]
You are are correct. I had an issue within our DNS configuration. Everything is working as it should. Thank you for the assistance and sorry for wasting your time.
