### ISSUE TITLE
RTPengine as unique media-relay

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#375]
We currently ship 2 different media-relays:

- _rtpengine_ for WSS sessions.
- _rtpproxy_ for remaining sessions.

Artemis should end with this duality and RTPengine seems the best option to go.

Related tasks:

- [x] Migrate media-relay sets feature to rtpengine.
- [x] Migrate stop-recording feature to rtpengine.
- [ ] Make some tests with media liberation mechanism.

**Comment by cruzccl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RTPproxy vs RTPengine: solo puede quedar RTPengine](https://trello.com/c/E6qwLv7y/14-rtpproxy-vs-rtpengine-solo-puede-quedar-rtpengine)

**Comment by cruzccl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RTPengine as unique media-relay](https://trello.com/c/E6qwLv7y/14-rtpengine-as-unique-media-relay)

**Comment by Kaian** [comment]
done in #544
