### ISSUE TITLE
asterisk: Endpoints in unavailable state

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#377]
Executing _pjsip list endpoints_ sometimes shows endpoints in _unavailable_ state.

This leads to problems as Asterisk thinks this endpoint is not reachable.

Running _pjsip qualify $endpoint_name_ fixes the endpoint.

This issue aims to fix this.

**Comment by Kaian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SEMS<>Asterisk en retail sin transcoding (X-Info out)](https://trello.com/c/KNJBMzE0/3-semsasterisk-en-retail-sin-transcoding-x-info-out)

**Comment by cruzccl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asterisk: Endpoints in unavailable state](https://trello.com/c/orUKujtZ/1-asterisk-endpoints-in-unavailable-state)

**Comment by Kaian** [comment]
Fixed in https://github.com/irontec/asterisk/commit/d500603448e580bd096cf4fdee0ac03b44cfd993
