### ISSUE TITLE
Evaluate brand SIP domains usefulness

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#42]
They point to KamTrunks IP address.

Think about removing them, as they complicate the underlying logic and are rarely used.

**Comment by Kaian** [comment]
Application Servers don't use that domain for sure.

AS matches endpoints using the user@domain in the From header, which is Company's Domain (that is mandatory for all companies).

**Comment by cruzccl** [comment]
This brand domain may be used in #85, pointing to ProxyUsers instead of ProxyTrunks.

Read #85 for further details.

**Comment by Kaian** [comment]
Brand's domain_trunks field has been removed in #133 
Brand's domain_users field has been added in #133 as domain from all RetailAccounts.
