### ISSUE TITLE
keep caller id in forward

### ISSUE THREAD

**Issue by invental** [irontec/ivozprovider#426]
in a call that enters a vpbx and meets a filter, that from a certain time that call is diverted to another number, how can I keep the id of the initial caller?

**Comment by Kaian** [comment]
Hi @invental 

## Current Forwarding options
Right now there are two scenarios where the calls are forwarded (a Diversion header is added with the forwarder information and the origin number is kept):

- [External Call Filters](https://irontec.github.io/ivozprovider/en/pbx_features/external_filters.html)
- [User Call Forward Settings](https://irontec.github.io/ivozprovider/en/pbx_features/users.html#user-call-forward)

The rest of the routes that have number are not handled as Diverted calls, and the called DDI (for external calls) or the outgoing DDI (for user calls) will be presented as origin.

## Is there any plans to change this behaviour?
There is no enhancement scheduled for changing this behaviour in the 1.x branch, and we could discuss if 2.x branch this is the best behaviour, or maybe we could consider all external calls (that have a DDI as entrypoint) should be considered diverted when they reach a number route option.

## Is there any workaround?
We've found some administrators that managed to archive diversions by routing to users with inconditional call forward settings to external numbers. This way the Diversion will contain the outgoing DDI of the user and the origin is kept. This configuration was not used for that and, although it may work it also can cause inexpected or untested behaviours.

**Comment by invental** [comment]
We have tested the call diversion with the indicated methods and it works preferably, it transfers the original numer of the call.
Thank you
