### ISSUE TITLE
invite 403 forbidden

### ISSUE THREAD

**Issue by invental** [irontec/ivozprovider#432]
We have an installation in tests of ivoz, has been working properly for 1 month. Without having made any changes in the installation or in the network, we have stopped receiving calls, we received the invite from the operator but ivoz does not return it. Outgoing calls work correctly.
We have made a new installation of ivoz on another computer but with the same network equipment. It does not work properly either.
We have configured this same trunk in a physical pbx and it is working correctly.

I do not see where to keep looking for the problem.

Thank you

**Comment by cruzccl** [comment]
Hi @invental,

Could you please attach logs from kamailio@trunks?

You can have them in realtime with:

`journalctl -u kamailio@trunks -f`

Regards,

**Comment by invental** [comment]
when we execute the "journalctl -u kamailio@users -f" command and receive a call, it returns the following error:

mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: NOTICE: [b<null>][6cffd285] Calculated hash for INVITE 08050f3b-abc0-1236-3bb8-14187736d68c
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: NOTICE: [b<null>][6cffd285] Request: INVITE 'sip:"telf_destino"@"ip_ivoz":5060' (120707039 INVITE) from 'sip:"telf_origen"@"ip_operador"' ("ip_operador":5060) [udp]
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: INFO: [b<null>][6cffd285] REQINIT: "ip_operador" will be checked against antiflood
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: INFO: [b<null>][6cffd285] REQINIT: "ip_operador" granted by antiflood
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: INFO: [b<null>][6cffd285] REQINIT: All checks passed, continue...
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: INFO: [b<null>][6cffd285] NATDETECT: Force rport
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: INFO: [b<null>][6cffd285] NATDETECT: No NAT detected
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: INFO: [b<null>][6cffd285] NOT in dialog request - not has_to_tag: Initial transaction
mar 26 19:42:29 ivozprovider-standalone /usr/sbin/kamailio[1182]: ERROR: [b<null>][6cffd285] "ip_operador" is not my domain, 403 forbidden
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: NOTICE: [b<null>][e7f0aa55] Calculated hash for INVITE 085020c1-abc0-1236-cd96-842b2b5827a5
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: NOTICE: [b<null>][e7f0aa55] Request: INVITE 'sip:"telf_destino"@"ip_ivoz":5060' (120707039 INVITE) from 'sip:"telf_origen"@"ip_operador"' ("ip_operador":5060) [udp]
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: INFO: [b<null>][e7f0aa55] REQINIT: "ip_operador" will be checked against antiflood
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: INFO: [b<null>][e7f0aa55] REQINIT: "ip_operador" granted by antiflood
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: INFO: [b<null>][e7f0aa55] REQINIT: All checks passed, continue...
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: INFO: [b<null>][e7f0aa55] NATDETECT: Force rport
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: INFO: [b<null>][e7f0aa55] NATDETECT: No NAT detected
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: INFO: [b<null>][e7f0aa55] NOT in dialog request - not has_to_tag: Initial transaction
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1175]: ERROR: [b<null>][e7f0aa55] "ip_operador" is not my domain, 403 forbidden
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: NOTICE: [b<null>][3626a94b] Calculated hash for INVITE 086aba53-abc0-1236-3bb8-14187736d68c
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: NOTICE: [b<null>][3626a94b] Request: INVITE 'sip:"telf_destino"@"ip_ivoz":5060' (120707040 INVITE) from 'sip:"telf_origen"@"ip_operador"' ("ip_operador":5060) [udp]
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: INFO: [b<null>][3626a94b] REQINIT: "ip_operador" will be checked against antiflood
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: INFO: [b<null>][3626a94b] REQINIT: "ip_operador" granted by antiflood
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: INFO: [b<null>][3626a94b] REQINIT: All checks passed, continue...
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: INFO: [b<null>][3626a94b] NATDETECT: Force rport
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: INFO: [b<null>][3626a94b] NATDETECT: No NAT detected
mar 26 19:42:30 ivozprovider-standalone /usr/sbin/kamailio[1171]: INFO: [b<null>][3626a94b] NOT in dialog request - not has_to_tag: Initial transaction

**Comment by cruzccl** [comment]
Hi @invental ,

when you receive an inbound call from a carrier, you should see Kamtrunks logs running the command I suggested.

If not, you must check that:

- KamTrunks is running:
```systemctl status kamailio@trunks```

- trunks.ivozprovider.local points to the IP address assigned to KamTrunks:
```ping trunks.ivozprovider.local```

- Requests you see in sngrep are reaching that IP address (and port, in case both KamUsers and KamTrunks are sharing the same IP address).

- In this last case (KamUsers and KamTrunks sharing IP), KamTrunks should listen to 7060 UDP port instead of 5060 UDP, check that requests go to that port. If you see KamUsers logs as you pasted it seems that carriers are talking to KamUsers IP:PORT instead of KamTrunks ones.

If all these is correct, there may be an iptables/firewall issue preventing requests from arriving to application layer.

Regards,

**Comment by lainard** [comment]
i have smiliar issue but mline show:

Apr 15 19:01:51 sbc /usr/sbin/kamailio[1498]: ERROR: [b1][3e10674e] XX.XX.XX.XX is not one of my domains, 404 Not Here
Apr 15 19:01:58 sbc /usr/sbin/kamailio[1504]: NOTICE: [b<null>][0cef969a] Calculated hash for OPTIONS 35f86664111dc9ab778fd9a8040f0847@91.209.123.138:5060
Apr 15 19:01:58 sbc /usr/sbin/kamailio[1504]: NOTICE: [b<null>][0cef969a] Request: OPTIONS 'sip:1523810251856@XX.XX.XX.XX:7060' (102 OPTIONS) from 'sip:weepee@91.209.123.138' (91.209.123.138:5060) [udp]
Apr 15 19:02:23 sbc /usr/sbin/kamailio[1502]: NOTICE: [b<null>][282048d7] Calculated hash for OPTIONS 2418bfdf3ff55898225762b6702214c3@91.209.123.138:5060
Apr 15 19:02:23 sbc /usr/sbin/kamailio[1502]: NOTICE: [b<null>][282048d7] Request: OPTIONS 'sip:1523810251856@XX.XX.XX.XX:7060' (102 OPTIONS) from 'sip:weepee@91.209.123.138' (91.209.123.138:5060) [udp]
Apr 15 19:02:48 sbc /usr/sbin/kamailio[1493]: NOTICE: [b<null>][eb33229f] Calculated hash for OPTIONS 2b920d107fd18fcc2a1afbb332653e45@91.209.123.138:5060
Apr 15 19:02:48 sbc /usr/sbin/kamailio[1493]: NOTICE: [b<null>][eb33229f] Request: OPTIONS 'sip:1523810251856@XX.XX.XX.XX:7060' (102 OPTIONS) from 'sip:weepee@91.209.123.138' (91.209.123.138:5060) [udp]
Apr 15 19:03:13 sbc /usr/sbin/kamailio[1497]: NOTICE: [b<null>][97d7dc28] Calculated hash for OPTIONS 6a190e2372d384f856a165661bfcd687@91.209.123.138:5060
Apr 15 19:03:13 sbc /usr/sbin/kamailio[1497]: NOTICE: [b<null>][97d7dc28] Request: OPTIONS 'sip:1523810251856@XX.XX.XX.XX:7060' (102 OPTIONS) from 'sip:weepee@91.209.123.138' (91.209.123.138:5060) [udp]


but the ip is in the list of domains

**Comment by invental** [comment]
apparently the problem has been solved. I did not notice in the documentation that working with a single ip had to change the port by 7060.

Thanks for the help

**Comment by cruzccl** [comment]
Hi @lainard ,

Try executing 

```kamcmd-proxyusers domain.list```

to see if the domain (the IP address in this case, as described in [the documentation](https://irontec.github.io/ivozprovider/en/oasis/internal_calls/brand_portal.html#i-have-no-time-for-a-dns-registry)) is assigned to KamUsers.

If it is not, you could have a problem in the XMLRPC worker that reloads kamailio modules when changes are made in the UI, try restarting KamUsers and execute again the command above.

Regards,

**Comment by lainard** [comment]
root@sbc:~# kamcmd-proxyusers domain.list
error: 500 - command domain.list not found
root@sbc:~#

**Comment by cruzccl** [comment]
Sorry, the right command is

```kamcmd-proxyusers domain.dump```

as documented [in Kamailio domain module documentation page](http://kamailio.org/docs/modules/4.4.x/modules/domain.html#idp35877300)

**Comment by lainard** [comment]
root@sbc:~# kamcmd-proxyusers domain.dump
{
	domain: sip.XXXXX.be
	did: sip.XXXXX.be
}
{
	domain: users.ivozprovider.local
	did: users.ivozprovider.local
}
{
	domain: XX.XX.XX.70
	did: XX.XX.XX.70
}
{
	did: sip.alphatel.be
	attr: brandId
}
{
	did: XX.XX.XX.70
	attr: brandId
}

**Comment by lainard** [comment]
Sorry for late reply
yes i installed all in the same machine.

**Comment by cruzccl** [comment]
Related with #491, already fixed.
