### ISSUE TITLE
How to extract CDRs

### ISSUE THREAD

**Issue by afernandez2000** [irontec/ivozprovider#433]
Hi Om using version 1.7 and I need to export the CDR to my billing company. I tried to use the ParsedCDRs table of the database directly with a reporting server, but I think that table doesnt have the right CDR information. Can you advise please?

Thanks

Alain

**Comment by cruzccl** [comment]
Hi @afernandez2000,

CDRs you see in billable calls sections are in BillableCalls view, which has a subset of rows of table kam_acc_cdrs.

Regards,
