### ISSUE TITLE
doc: reorder documentation and add links to admin portal

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#442]
Documentation was written with a tutorial design. This is fine to have a first approach to the project, but makes it difficult to find the help page of a particular web section.

This issue aims to reorder the documentation so that a link to the corresponding help page can be added to each administration section.

**Comment by Kaian** [comment]
This has improved but there are still lots of work. 

I will try adding here a checklist with pending and obsolete sections!
