### ISSUE TITLE
web/admin: Change billing related sections

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#444]
CGrateS tables were directly mapped into administration portal.

This lead to some new sections (Destination patterns, Rates, Destination Rates, Rating Plans) that make the point but are quite unusable when you need to work with several rating plans.

This issue aims to merge these sections into a unique one (or two) so that they are easier to use.

**Comment by mmadariaga** [comment]
Fixed in https://github.com/irontec/ivozprovider/pull/446
