### ISSUE TITLE
Force Peering contract codec

### ISSUE THREAD

**Issue by amvidalrc** [irontec/ivozprovider#449]
Hello. I want to get the possibility of force the peering contract codec. I have all the users working with G729 but the calls gets out with G711. I want all traffic of the peering contract in G729 too. The provider allows G729.

How I can force it?

Thanks and nice work!!

**Comment by Kaian** [comment]
Hi @amvidalrc 

Right now, all peering contracts use the same codec setup defined as proxytrunks peer in asterisk. You can change it in [/etc/asterisk/pjsip.conf](https://github.com/irontec/ivozprovider/blob/oasis/asterisk/config/pjsip.conf#L26) by setting `allow=g729` for all endpoints defined there.

For future releases if #387 is approved and the encoding is done at proxy level, it could be possible to specify different codecs per carrier.

Regards!

**Comment by amvidalrc** [comment]
Eskerrik asko!!
I will wait for the new revisions. Forcing to G729 the proxytrunks will affect to Faxing via T.38?
Thanks again.

**Comment by Kaian** [comment]
Ez dago zergatik!!
It shouldn't affect T.38 as far I know. Codec definition is only used for SDP payloads and we don't support T.38 fallback to RTP, so as long as the initial negotiation is not rejected, after switching to T.38 codecs should not matter.

Regards!!
