### ISSUE TITLE
How does one start ivozprovider / configure it when installing using apt?

### ISSUE THREAD

**Issue by chiragd** [irontec/ivozprovider#450]
I followed the instructions here: https://irontec.github.io/ivozprovider/en/installation/debian_install.html#installing-profile-package

I have all the packages installed...but it's not clear from the instructions how to configure or start them. Any guidance please? I have this installed on ubuntu.

In the documentation there is a link to "finishing role configuration" however this just links to the github page and I can't find any useful info. http://github.com/irontec/ivozprovider

Please could you point me in the right direction?

**Comment by Kaian** [comment]
Hi @chiragd 

Documentation is sometimes a bit confusing (we are working on reordering it at #442), so I will point you to the pages with requested informaron. 

Ivozprovider 1.7 is designed to be installed using a Debian 8 Jessie base system, as documentation mentions in [Minimum Requeriments](https://irontec.github.io/ivozprovider/en/oasis/installation/requirements.html) and also [Debian packages install](https://irontec.github.io/ivozprovider/en/oasis/installation/debian_install.html). We have not even tested any other base system with ivozprovider, so avoid them in any production environment.

The distributed installation (with multiple boxes per role and clusters to manage resources) is not documented. We will change the documentation to link that section with #271 to avoid confusion.

Standalone installations (all profiles in the same machine) are configured by installing ivozprovider package as documented in [Configuring ivozprovider section](https://irontec.github.io/ivozprovider/en/oasis/installation/cd_install.html). It should display a menu to enter the public IPs of the SIP proxies and so on.

When package installation has ended, you can connect to the web interface in any of the box ips using default credentials documented  [here](https://irontec.github.io/ivozprovider/en/oasis/installation/cd_install.html), [here](https://irontec.github.io/ivozprovider/en/oasis/installation/debian_install.html) or [here](https://irontec.github.io/ivozprovider/en/oasis/internal_calls/god_portal.html)

Using the web interface you can follow the getting started guides to configure a company domain and test internal and external calls.

Regards!!

**Comment by chiragd** [comment]
Thanks for the reply @Kaian 
I am travelling and without my normal set up, but still wanted to play with ivozprovider. I'm (dangerously) running debian as a crouton on a Chromebook. I managed to get the ivozprovider package installed, but it didnt run.

I got an error like this. Any ideas?

` ok ] Starting MySQL database server: mysqld ..
[info] Checking for tables which need an upgrade, are corrupt or were 
not closed cleanly..
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
/opt/irontec/ivozprovider/scheme /
Buildfile: /opt/irontec/ivozprovider/scheme/build_prod.xml
 [property] Loading /opt/irontec/ivozprovider/scheme/./build.properties.production

ivozprovider > init:

Execution of target "init" failed for the following reason: /opt/irontec/ivozprovider/scheme/build_prod.xml:15:13: Task exited with code 1

BUILD FAILED
/opt/irontec/ivozprovider/scheme/build_prod.xml:15:13: Task exited with code 1
Total time: 0.8104 seconds

/
Buildfile: /opt/irontec/ivozprovider/scheme/build_prod.xml
 [property] Loading /opt/irontec/ivozprovider/scheme/./build.properties.production

ivozprovider > first-pass-migrate:

 [dbdeploy] Getting applied changed numbers from DB: mysql:host=data.ivozprovider.local;dbname=ivozprovider
Execution of target "first-pass-migrate" failed for the following reason: /opt/irontec/ivozprovider/scheme/build_prod.xml:35:16: 
#0 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#1 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#2 /usr/share/php/phing/Target.php(297): Task->perform()
#3 /usr/share/php/phing/Target.php(320): Target->main()
#4 /usr/share/php/phing/Project.php(824): Target->performTasks()
#5 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#6 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#7 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#8 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#9 /usr/share/php/phing.php(43): Phing::fire(Array)
#10 {main}

Previous exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php:175
Stack trace:
#0 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(175): PDO->__construct('mysql:host=data...', 'root', 'changeme')
#1 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(153): DbDeployTask->getAppliedChangeNumbers()
#2 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#3 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#4 /usr/share/php/phing/Target.php(297): Task->perform()
#5 /usr/share/php/phing/Target.php(320): Target->main()
#6 /usr/share/php/phing/Project.php(824): Target->performTasks()
#7 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#8 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#9 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#10 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#11 /usr/share/php/phing.php(43): Phing::fire(Array)
#12 {main}

BUILD FAILED
/opt/irontec/ivozprovider/scheme/build_prod.xml:35:16: 
#0 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#1 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#2 /usr/share/php/phing/Target.php(297): Task->perform()
#3 /usr/share/php/phing/Target.php(320): Target->main()
#4 /usr/share/php/phing/Project.php(824): Target->performTasks()
#5 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#6 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#7 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#8 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#9 /usr/share/php/phing.php(43): Phing::fire(Array)
#10 {main}

Previous exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php:175
Stack trace:
#0 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(175): PDO->__construct('mysql:host=data...', 'root', 'changeme')
#1 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(153): DbDeployTask->getAppliedChangeNumbers()
#2 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#3 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#4 /usr/share/php/phing/Target.php(297): Task->perform()
#5 /usr/share/php/phing/Target.php(320): Target->main()
#6 /usr/share/php/phing/Project.php(824): Target->performTasks()
#7 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#8 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#9 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#10 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#11 /usr/share/php/phing.php(43): Phing::fire(Array)
#12 {main}
Total time: 0.1290 seconds

dpkg: error processing package ivozprovider-scheme (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libgeoip1:amd64 (1.6.2-4) ...
Setting up libisc95 (1:9.9.5.dfsg-9+deb8u14) ...
Setting up libdns100 (1:9.9.5.dfsg-9+deb8u14) ...
Setting up libisccc90 (1:9.9.5.dfsg-9+deb8u14) ...
Setting up libisccfg90 (1:9.9.5.dfsg-9+deb8u14) ...
Setting up libbind9-90 (1:9.9.5.dfsg-9+deb8u14) ...
Setting up liblwres90 (1:9.9.5.dfsg-9+deb8u14) ...
Setting up libpython2.7-stdlib:amd64 (2.7.9-2+deb8u1) ...
Setting up python2.7 (2.7.9-2+deb8u1) ...
Setting up libpython-stdlib:amd64 (2.7.9-1) ...
Setting up python (2.7.9-1) ...
Setting up bind9utils (1:9.9.5.dfsg-9+deb8u14) ...
Setting up bind9 (1:9.9.5.dfsg-9+deb8u14) ...
Adding group `bind' (GID 111) ...
Done.
Adding system user `bind' (UID 107) ...
Adding new user `bind' (UID 107) with group `bind' ...
Not creating home directory `/var/cache/bind'.
wrote key file "/etc/bind/rndc.key"
#
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libstring-crc32-perl (1.5-1+b1) ...
Setting up libgearman-client-perl (1.11-3) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 ivozprovider-scheme
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by Kaian** [comment]
Hi @chiragd 

MySQL password is configured during ivozprovider installation process, in the menu shown in [these screenshots](https://irontec.github.io/ivozprovider/en/oasis/installation/cd_install.html) and should be set with the same password used during MySQL Server install. If none is entered, the defaults _root/changeme_ are used. 

That configures the migrations file with the proper credentials. Check `/opt/irontec/ivozprovider/scheme/build.properties.production`, it should contain the entered credentials for root user in MySQL.

Also note that IvozProvider assumes the base system is empty when installed as documented [here](https://irontec.github.io/ivozprovider/en/oasis/installation/requirements.html).

Regards!

**Comment by chiragd** [comment]
Hi @Kaian,

I'm sure I set a mysql password. The file you suggested contained root/changeme. I updated it with the value I entered during initial setup but it still doesn't work.

BIt stumped now.

**Comment by Kaian** [comment]
Hmm, [this](https://github.com/irontec/ivozprovider/blob/oasis/debian/ivozprovider-scheme.postinst) is the script executing the database migrations during package installs and updates. As you see, it relays on the debconf setting entered during install called ivozprovider/mysql_password

You can also check the entered value by running:
```
echo get ivozprovider/mysql_password | debconf-communicate
```
You should be able to reconfigure that value running `dpkg-reconfigure ivozprovider`, not sure if it will work with broken packages, but just fyi.

Check you can login into your mysql running:
```
mysql -u root -p -h data.ivozprovider.local 
```
And entering that password. Otherwise you should reset your mysql root password

Regards!!
