### ISSUE TITLE
Full Backup or Easy Migration Tool

### ISSUE THREAD

**Issue by amvidalrc** [irontec/ivozprovider#459]
Hello.
I want to know if there is any easy way to backup and restore an ivozprovider implementation.

My case:
I have my ivozprovider installed in one VPS provider, and I want to migrade to another one without losing any configuration. I thinked two possibilities but please, tell me what of these are the best or what is the "official" way:

- rsync the full vps to another vps including the mysql database
- install a clean ivozprovider and restore the full mysql database

The rsync option its possible to copy two ivozprovider in real time for having 1+1? For example: balancing or if one of the VPS go down the second machine can give the service.

In resume: What is the best way to backup & restore and have a 1+1 ivozprovider implementation in case of one vps get down?

Thanks again for your work.

**Comment by Kaian** [comment]
Hi @amvidalrc 

The variable data of ivozprovider is stored in MySQL and storage. The later is used for files, like uploaded locutions, musics on hold, faxes and so on and it's located at `/opt/irontec/ivozprovider/storage/`

> For example: balancing or if one of the VPS go down the second machine can give the service.

What you mention here requires clustering software that ensures each service is running in any of the two nodes. Some of the platform software, like each kamailio proxy, are designed to be just once in the platform, so cluster must ensure it's up in any of the two nodes (where its IP is also present). For MySQL you can also create a master-master replication with two nodes, and for storage there are some solutions like GlusterFS that works quite well.

There is no _easy way_ to create distributed installations yet. There are no discovery tools for services or something like that implemented yet. Documentation for configuring these distributed installations with multiple nodes is not easy at all and it has been requested many times (see #271)

Maybe someone reading is willing to provide their experience, or you can contact our commercial team if you need specific support.

Best regards!!
