### ISSUE TITLE
Invoice & Billable calls Date/Timezone Issue

### ISSUE THREAD

**Issue by afernandez2000** [irontec/ivozprovider#462]
Hi,

In a current setup I already setup a company with my local TimeZone (GMT-5) When I create an Invoice and specify the dates for example: Mar/1/2018 to Mar/31/2018 in the invoice are appearing calls from Feb/28/2018 I think is an issue with the TimeZone converting.

Attached some images.

![image](https://user-images.githubusercontent.com/1214749/39099610-a2f8a1ba-464b-11e8-97dd-3b646ea7af1f.png)

![image](https://user-images.githubusercontent.com/1214749/39099632-f2b819a6-464b-11e8-8d04-921e5745bf54.png)

**Comment by mmadariaga** [comment]
Hi there,

Which version of IvozProvider are you using? Oasis (1.7) or Artemis (2.1)?

**Comment by mmadariaga** [comment]
By the way,

Is your brand administrator in GMT-5 as well? 

Calls are fetched based on company timezone but represented in logged in user time zone.

**Comment by afernandez2000** [comment]
Hi the version is 1.7.0. And yes the brand administrator and the Brand already have America/New_York timezone

**Comment by mmadariaga** [comment]
Hi,

Could you apply the changes found in https://github.com/irontec/ivozprovider/pull/465/files into /opt/irontec/ivozprovider/library/IvozProvider/Gearmand/Invoices/Generator.php, regenerate the invoice and confirm that it works please?

Thanks

**Comment by mmadariaga** [comment]
Sorry, I forgot to mention that in order to apply those changes a service restart is required :disappointed: : 
`sudo systemctl restart supervisor.service` 

Could you restart it and try again please?

**Comment by afernandez2000** [comment]
Hi,

Yes now it works. Thank you very much

Alain Fernandez
