### ISSUE TITLE
2.1.0 Rest API doc

### ISSUE THREAD

**Issue by majortom81** [irontec/ivozprovider#468]
Hi guys,
is there any chance to have the REST API documentation for version 2.1.0?
Cheers.

**Comment by mmadariaga** [comment]
Hi,

You can find API swagger specification at https://your-domain/api/swagger.json and a visual tool at  https://your-domain/api/index.html

Be aware that the API may still suffer some major changes before artemis (2.x) goes stable, so any integration is discouraged for now.

Hope it helps
