### ISSUE TITLE
wholesale

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#470]
A minor question.

What are exactly wholesales? Looks like they are like peers which run on static IPs.  But I can't see how to do anything with them.

I can't assign DDIs to wholesales so it seems I can't send incoming calls to those peers. I haven't tried outgoing calls so I don't know if those would work.

Is that feature still on early development stage or is it a totally different concept?

**Comment by Kaian** [comment]
Hi @manfer 

Wholesale is a new peer type and the main focus of the next minor releases. We will be adding new features to this client type on next releases (like calling prefix, optional transcoding, and so on).

Wholesale allows trunking services with Carriers without any _application server_ features, focusing on concurrency and quality rather on having lots of services. For a brief description of this kind of entity check https://github.com/irontec/ivozprovider/pull/461

Documenting this entity is also part of the #442

Regards!
