### ISSUE TITLE
unable to install profile data

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#471]
I'm trying to install ivozprovider-profile-data in a machine with no success. I install a debian 8 base system, I fully update it, I add ivozprovider oasis and klear chloe repositories, I procced to install the data profile and I get the errors shown in the attached images.

I have done two attempts. On second attempt I had used **data** as hostname and **ivozprovider.local** as domain and used **changeme** as mysql root password. But same result.

![ivprofiledata](https://user-images.githubusercontent.com/458420/39571416-b7e993c6-4ecb-11e8-8e1b-9f7587de1d7a.png)

![ivprofiledata2](https://user-images.githubusercontent.com/458420/39571635-680aebf6-4ecc-11e8-9ea4-802936f6adba.png)

**Comment by manfer** [comment]
If I do

```mysql -p -u root```

I can access mysql database.

**Comment by Kaian** [comment]
Can you ping _data.ivozprovider.local_ ?

Can you provide the contents of `/etc/resolv.conf` and `/etc/bind/db.ivozprovider.local`

Regards

**Comment by manfer** [comment]
```
root@data:~# ping -c 4 data.ivozprovider.local
PING data.ivozprovider.local (127.0.1.1) 56(84) bytes of data.
64 bytes from data.ivozprovider.local (127.0.1.1): icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from data.ivozprovider.local (127.0.1.1): icmp_seq=2 ttl=64 time=0.057 ms
64 bytes from data.ivozprovider.local (127.0.1.1): icmp_seq=3 ttl=64 time=0.064 ms
64 bytes from data.ivozprovider.local (127.0.1.1): icmp_seq=4 ttl=64 time=0.064 ms

--- data.ivozprovider.local ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2998ms
rtt min/avg/max/mdev = 0.049/0.058/0.064/0.009 ms
```

About `/etc/resolv.conf` has two nameservers from my ISP

There is no ivozprovider.local zone. The file `/etc/bind/db.ivozprovider.local` doesn't exist.

`/etc/hosts` file reads like this
```
127.0.0.1       localhost
127.0.1.1       data.ivozprovider.local data

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by manfer** [comment]
Maybe this has nothing to do as I am not familiarized with debian packaging system. But I had tried to follow what is done during package installation.

In the postinstall of ivozprovider-scheme on line 15 I read

`db_get ivozprovider/mysql_password || true`

which I suppose is trying to get the mysql password from what was configure during installation of ivozprovider package. But I had never installed ivozprovider package as I'm trying to install in a machine ivozprovider-profile-data alone.

Could it be is trying to connect to mysql as root with a blanck password?

**Comment by manfer** [comment]
Looks consistent to me with the error messages when trying to install ivozprovider-profile-data

I can see two failed attempts to connect to the database
```
Configurando ivozprovider-scheme (1.7.0~20180420.1364~6922536+oasis) ...
sed: -e expresión #1, carácter 39: opción desconocida para `s'
[ ok ] Starting mysql (via systemctl): mysql.service.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
/opt/irontec/ivozprovider/scheme /
```
which may come from the execution of these lines on ivozprovider-scheme postinstall script

```
    # Load Timezones
    mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --user=root --password="$MYSQL_PASSWORD" mysql

    # Create database if it doesn't exist
    /usr/bin/mysql --user=root --password="$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS ivozprovider"
```

**Comment by manfer** [comment]
Thanks for clarification. As I'm trying just for testing purpose I will try to do it with artemis. I just chosen oasis because was the stable realease. I didn't think about artemis having a different packaging implementation.

**Comment by manfer** [comment]
Worked like a charm using artemis. I have to just investigate which IPs need to be configured for each service but the installation was completed successfully.

As for now I have configured the IPs as follows:

**users.ivozprovider.local**
one IP I'm going to use on the machine where I'm going to install profile-proxy

**trunks.ivozprovider.local**
a second IP I'm going to use on the machine where I'm going to install profile-proxy

**jobs.ivozprovider.local**
IP I'm going to use on the machine where I'm going to install profile-portal as I suppose this is the gearman-job-server

**data.ivozprovider.local**
IP I'm going to use on this machine where I installed profile-data as it is the one in which bind9 is installed

**storage.ivozprovider.local**
one IP I'm going to use on the machine where I'm going to install profile-proxy as it is where the recordings package is installed. I'm not sure at all about this.

**logs.ivozprovider.local**
not sure about this either. I configured it with the IP I'm going to use in the machine where I'm going to install profile-portal

**Comment by Kaian** [comment]
> storage.ivozprovider.local
> one IP I'm going to use on the machine where I'm going to install profile-proxy as it is where the recordings package is installed. I'm not sure at all about this.

This is usually a data server, but any profile with a distributed network storage like a NFS server will work. All machines must have storage mounted at _/opt/irontec/ivozprovider/storage/_ to access shared files.

> logs.ivozprovider.local
> not sure about this either. I configured it with the IP I'm going to use in the machine where I'm going to install profile-portal

This can be used to centralize all machines logs to a server from journald using journald-remote or journal2gelf (the later for graylog server type). It's not mandatory to centralize logs.

**Comment by Kaian** [comment]
The storage path is the same as for standalone installations, but network mounted. Browse the files there for your installation if you have the opportunity.

It's used for all filles referenced in database: locutions, music on hold, recordings, faxes, voicemails, logos, and so on.

Regards

**Comment by manfer** [comment]
It is being easy process so far. Amazing, I thought I would have to do a lot more configuration manually.

The only problem I found for now is that when installing data profile the mysql only listens on localhost so I had to edit mysql server bind address. Maybe ivozprovider-profile-data config could do it automatically? On that config we configure already data.ivozprovider.local IP which is the one mysql server has to bind to, isn't it?

**Comment by Kaian** [comment]
> It is being easy process so far. Amazing, I thought I would have to do a lot more configuration manually.

Glad to hear it has improved and not the opposite! :smile: 

> On that config we configure already data.ivozprovider.local IP which is the one mysql server has to bind to, isn't it?

That's not mandatory. You can have a master-master mysql replication with a balanced virtual IP address. In that scenario they bind to 0.0.0.0 instead of data.ivozprovider.local.

We use some ansible playbooks for provisioning our distribution installations that do a lot of work still missing in the packages, but they are far for ready to be published in any way. In one of those tasks, we create a file at _/etc/mysql/conf.d/ivozprovider-distributed.cnf_ with following contents:

```[mysqld]
bind-address = 0.0.0.0
 ```

To keep the issue on-topic so it can be referenced in the future for others: the problem is the oasis packages are not ready to be distributed installed. The artemis ones have improve but they won't also work _out of the box_. Feel free to open other issues for installation process comments or drop us a line on IRC channel.

Regards!!
