### ISSUE TITLE
typo in debian config scripts

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#474]
There is a minor typo in debian/ivozprovider.config

In bleeding it is located at line 102

`db_get ivozprovider/mysql_passowrd`

Looks the typo has no effect on functionality as that variable doesn't seems to be used on configure_finish function.

So, if I'm not wrong, there are two possible solutions: correcting the typo or removing lines 102 and 103

**Comment by Kaian** [comment]
Hi @manfer 

That should be used to check if the database password has not been entered (so the default changeme will be used) to display a confirmation dialog to use default settings.

This seems to be implemented    with proxy addresses but not the password, so I would remove those two lines for now.

Would you mind Pull requesting the change for bleeding? 

Thanks!!!

**Comment by Kaian** [comment]
Merged in #482 :+1:
