### ISSUE TITLE
release 1.7, API search parameter and PUT request

### ISSUE THREAD

**Issue by majortom81** [irontec/ivozprovider#485]
Hi guys,
I'm testing REST API on release 1.7, following the documentation I found under https://mydomain.com/apidocs.

It's quite straightforward, and I can successfully make GET, POST, DELETE.
I can also query entry per id, for example, this works fine:

curl -s -i -X GET --user 'user:password' https://my.domain/rest/companies/?id=11

as well as:

curl -s -i -X GET --user 'user:password' https://my.domain/rest/companies/11

Also the order parameter works fine:

curl -s -i -X GET --user 'user:password' https://my.domain/rest/companies/?order=id

My question are:

1) I was not able to use the"search" parameter. It says it should be a json_encode format, but it seems not working:

curl -s -i -X GET --user 'user:password' https://my.domain/rest/companies/?search={"name":"test"}

it response with: 500
Exception: {"exception":"The provided search should be something iterable!","developerRef":""}

I tried several other formats, without success.
What is the correct syntax for search parameter?

2) How can I make a successfully PUT request, in order to change/update a field? For example Company name?

Thanks.

**Comment by manfer** [comment]
I don't think that curl request with json parameter is correct. It is fine to do it that way for your first simple example with parameter ?order=id but when you have to pass a json as parameter I think syntax is totally different.

https://stackoverflow.com/questions/21326397/curl-get-request-with-json-parameter/21326644

**Comment by manfer** [comment]
The problem is for sure the way to send a GET request with command line curl and a json parameter.

If you go to https://mydomain.com/apidocs and you expand the companies GET  /rest/companies/ you will have three tabs: Info, Sandbox, Sample Output

If you click on Sandbox it lets you test that api function.

Just add `{"name":"test"}` to the search input box and click the send button and you will get the result.

I suggest doing your test on that apidocs page or with a programming language that gives you an API to make GET requests. You will be able to do those tests easily with PHP Curl for example.

**Comment by manfer** [comment]
The parameter must be properly json encoded and url encoded.

Looks the problem is more the url encoding as the json is correct already.

Try:
`curl -s -i -X GET --user 'user:password' https://my.domain/rest/companies/?search=%7B%22name%22%3A%22test%22%7D`

**Comment by manfer** [comment]
In PHP with PHP-Curl would be something like this

```
$ch = curl_init();
$data = array("name" => "test");
$jsondata = urlencode(json_encode($data));
curl_setopt($creq, CURLOPT_URL, "https://my.domain/rest/companies/?search=".$jsondata);
curl_setopt($creq, CURLOPT_RETURNTRANSFER, true);
curl_setopt($creq, CURLOPT_USERPWD, "user:password");
curl_setopt($creq, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($creq, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($creq, CURLOPT_SSL_VERIFYPEER, 0);
$output = curl_exec($creq);
var_dump($output);
```

Setting CURLOPT_SSL_VERIFYHOST and CURLOPT_SSL_VERIFYPEER to value 0 is only needed if you don't have a valid SSL certificate on your domain.

**Comment by majortom81** [comment]
Thanks Fernando for your effort!
I was able to get it work on my python script as well!

What about the PUT tos change fields?
What would be the syntax in that case?
Let's suppose I need to change the domain name, from test to "test-1234"

I tried several options, but without success

**Comment by Kaian** [comment]
With no intention to disturb the thread, just some mandatory disclaimer for oasis users.

API rework is one of the main goals of next release as mentioned in #281. Although is not yet production ready, API has changed a lot and has no backwards compatibility (PUT method won't be even suppprted initially).

Feel free to integrate with current API implementation, but be aware the mentioned incompatibilities.

Regards!!

**Comment by majortom81** [comment]
Hi @Kaian !
thanks for the comment. I'm currently playing with the software, in order to evaluate his potentiality.
Anyway, I will wait for release 2.x for sure, before building something for production. 

API is a must for us, so I hope they will be part of upcoming stable release 2.x.

**Comment by mmadariaga** [comment]
Hi @majortom81,

PUT Curl request would be something like :
curl 'https://your-domain.com/rest/domains/' -X PUT --user 'user:passwd' --data 'id=89&domain=my-new-domain.com'

**Comment by majortom81** [comment]
@mmadariaga , It works, thanks!
