### ISSUE TITLE
RTPengine recording support

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#488]
#375 added the feature to add RTPengine media relay sets but recording of calls managed by these sets wasn't implemented.

This issue aims to:

- Record calls by DDI (for non-wholesale clients).

- On-demand call recording (for non-wholesale clients).

- Record all calls: for wholesale clients only.

First two points mean recovering an existing rtpproxy feature. The latter implies:

- Wholesale clients: choose only among rtpengine sets.

- New wholesale client feature: record all calls ON/OFF.

**Comment by Kaian** [comment]
Recordings can not be enabled simultaneously for rtpengine and rtpproxy because the exported functions of kamailio modules have the same name.

We should remove rtpproxy support and replace existing recording parser to only handle new recording types.

I'll move this to 2.X

**Comment by Kaian** [comment]
DDI and onDemand recording are implemented in #548 for rtpengine

**Comment by cruzccl** [comment]
About this:

- Wholesale clients do not support any kind of recoding.

- Recording of bouncing calls need improvements (see #549).

- Several on-demand recording of same call fail (see #550).

Apart from these, this issue is over :)
