### ISSUE TITLE
recordings: Do not save them all in a unique directory

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#49]
year/month/day approach?

Saving them all in the same directory will lead us to trouble.

**Comment by Kaian** [comment]
I though this was already done by Mappers FSO system but doesn't seem the case.

We convert from wav to mp3 in the [recordingsDir](https://github.com/irontec/ivozprovider/blob/bleeding/kamailio/recordings/application/controllers/RecordingsController.php#L138). Then we [put the file using FSO](https://github.com/irontec/ivozprovider/blob/bleeding/kamailio/recordings/application/controllers/RecordingsController.php#L192) which removes the mp3 file from that dir and moves it to the final directory in storage (_ivozprovider_model_recordings.recordedfile_) but does not create any subdir like in other cases (for example, fax files).

Are we doing something wrong?
Maybe we must first save the Recordfile and then put the file?
