### ISSUE TITLE
question: cgrates reply artemis

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#495]
I'm testing a distributed installation of ivozprovider artemis installed from debian packages.

Internal calls are working with audio though I'm almost sure I have not everything correctly configured yet.

I'm trying now to test outbound call. Outbound calls does not work because I'm getting the error Rating Plan not found which is what I'm trying to debug at this moment.

On call simulator in the rating plan I get error "Destination Rate not found"

If I dump interface packages with tcpdump to see what is happening I see a request comming into port 2080 on trunks.ivozprovider.local machine. Cgr-engine is listening on that port and sends back a Rating Plan Id not found json reply.

The credentials and host in cgrates.json for mysql are tested and working. The rating plan id exists on the database.

Don't know what to look at next to debug this.

**Comment by cruzccl** [comment]
Hi @manfer ,

CGRateS works with two different storages: stordb (mysql in IvozProvider) and datadb (redis in IvozProvider).

There is a systemd-timer that synchronizes both storages, you can see it #376.

Is this timer is not running properly?

Regards,
