### ISSUE TITLE
User portal always in Spanish

### ISSUE THREAD

**Issue by afernandez2000** [irontec/ivozprovider#499]
Hi the user portal is always showing in spanish I have setup everything in English my browsers are in English too, company language, account Language all are in English and portal is still showing in Spanish.

**Comment by manfer** [comment]
At the top right on the portal there is a toolbar with icons. One of the icons is a flag. If you click that flag it opens a submenu with the two language options: english, spanish

**Comment by Kaian** [comment]
Multilanguage userportal will be available in 2.3. Login screen will be in the browser preferred language. Once logged in, the user language will be used to translate the portal.

Administration portals, like manfer mentioned, use the administator language and allows switching languages once logged in.

Regards!
