### ISSUE TITLE
Bleeding Brand Portal Menu Items error

### ISSUE THREAD

**Issue by flantel** [irontec/ivozprovider#507]
Hi,

Using the latest Bleeding. I have a Brand set up with no access to Billing, Invoices, Retail and Wholesale. 

In the main God portal, if I view this Brand, it looks fine:

![image](https://user-images.githubusercontent.com/3835944/40616448-fa6cc932-6282-11e8-8919-f5981544dde9.png)

However, if I log in as this Brand's admin, I am seeing menu items for disabled items such as Invoices, Billable Calls, Invoice Template, Rating Plans, ( and two items "e" and "h" which, if clicked on, go to Retail and Wholesale - I see this is fixed in PR #505) 

![image](https://user-images.githubusercontent.com/3835944/40616481-28c0306c-6283-11e8-9599-4d27f506fc4a.png)

**Comment by Kaian** [comment]
Verified, it's actually a bug.

Thanks for reporting!

**Comment by flantel** [comment]
Yes, Global admin menus are fine, it is the Brand portal's menu which shows wrong.

**Comment by Kaian** [comment]
Thanks for reporting, this should be fixed int the next release!
