### ISSUE TITLE
Add call cost concept for outgoing calls

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#528]
Currently there a unique monetary concept assigned to calls: price. Prices sets the amount of money that brand operator charges to their clients.

This issue aims to add another concept, call cost: the amount of money a service provider charges the brand operator for a call.

This issue will only add call cost for outgoing calls placed through carriers (peering contracts):

- Each carrier will have a rating profile with the cost of every prefix they provide.

- Once a call has ended, both call cost and call price is calculated and shown.

**Comment by Kaian** [comment]
Implemented in #598
