### ISSUE TITLE
Add support for multiple currencies

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#530]
All monetary concepts assume a unique currency (€).

This issue aims to add a section where the brand operator can add currencies and set their conversion rate.

A lot of evaluation has to be done:

- Carrier: each carrier must have a unique currency for all the monetary concepts (credit, rating profile for call cost).

- Client: each client should have a unique currency for billing its calls and for all its invoices.

- Multiple currency has a huge impact on LCR logic.

**Comment by Kaian** [comment]
Fixed in #834
