### ISSUE TITLE
When user is deleted assigned extension configuration is not updated

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#534]
When a user is removed its assigned screen extension gets into an inconsistent state. The route type of that extension is still User, but the user does not exist anymore.

It would be desirable that the extension gets route type unassigned before the user is deleted.

**Comment by mmadariaga** [comment]
Hi @manfer,

As You've mentioned, Extension.userId is updated to null value through a database constraint (ON DELETE SET NULL) and we are not managing routeType field value.

Have you detected any bug related to this behaviour in the application?

**Comment by manfer** [comment]
No. Just when you create a new user and you want to assign a screen extension you can not choose the one used by previous user because it is not in the list.

When you realize it is because the extension has its route type set to value 'User', you just need to reconfigure it and it is all ok.

It's just usability issue. I hadn't notice any other problem.

**Comment by mmadariaga** [comment]
Thanks for the reporting the issue @manfer :)
