### ISSUE TITLE
MWI subscription not working

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#536]
Not 100% sure but I think this was working in 1.6.

I'm now using 1.7 and I have tested on a tayler install too. The MWI subscription message is rejected by kamailio-users with reply '404 no voicemail service'.

User's terminal registers correctly and the voicemail works correctly too as I can leave a message on user's voicemail and I can access the voicemail dialing *93 from user's terminal.

**Comment by manfer** [comment]
Ok. After searching I see this issue is already knnow https://github.com/irontec/ivozprovider/issues/14

**Comment by cruzccl** [comment]
Hi @manfer,

Yes, there are a couple of issues related to MWI:

- Unsolicited MWI (#367)
- Subscribe/Notify MWI (#14)

Sadly, we are focusing in strengthening other parts of the solutions right now and those improvements are not even scheduled (both of them are in Future milestone).

We close this issue to avoid duplicates.

Regards,
