### ISSUE TITLE
Gearmand alternatives to handle async tasks (DBUS)

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#54]
Evaluate using systemd DBUS to handle asynchronous tasks (importing prices CSV, encoding audio files, etc.)

**Comment by Kaian** [comment]
Current Gearmand workers:

- [x] Generate Invoices
- [x] Import Prices
- [x] Encoding Locutions/Music on Hold
- [ ] Sending faxes (removed in 73778cc55b9da5b96bee44bdf271bff0d156cac4)
- [x] Tarificate calls
- [x] Reload proxies configuration

**Comment by Kaian** [comment]
What about https://php-enqueue.github.io/bundle/quick_tour/

**Comment by Kaian** [comment]
Fixed in #1586
