### ISSUE TITLE
10 installs from source not cd all the same errors

### ISSUE THREAD

**Issue by vobi2017** [irontec/ivozprovider#551]
Unfortunately Digital Ocean does not allow install from ISO. I have tried do different install across multiple dedicated hosted server all having public facing IP's. Follows the book by the cover and they all fail on the mysql. Every time. with or without adding a mysql pwd. debian 8.10. was hoping to get this introduction but hmm it seems the build is flaky, I may be wrong and if someone can help would be great. 

p.s it happens with all versions:

stable (oasis 1.7)
testing (artemis 2.3.0) |
experimental (bleeding 2.4.0)

Creating config file /etc/php5/mods-available/pdo_mysql.ini with new version
php5_invoke: Enable module pdo_mysql for cli SAPI
Setting up ivozprovider-scheme (1.7.0~20180620.1443~e59a245+oasis) ...
[ ok ] Starting mysql (via systemctl): mysql.service.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
/opt/irontec/ivozprovider/scheme /
Buildfile: /opt/irontec/ivozprovider/scheme/build_prod.xml
 [property] Loading /opt/irontec/ivozprovider/scheme/./build.properties.production

ivozprovider > init:

Execution of target "init" failed for the following reason: /opt/irontec/ivozprovider/scheme/build_prod.xml:15:13: Task exited with code 1

BUILD FAILED
/opt/irontec/ivozprovider/scheme/build_prod.xml:15:13: Task exited with code 1
Total time: 0.0691 seconds

/
Buildfile: /opt/irontec/ivozprovider/scheme/build_prod.xml
 [property] Loading /opt/irontec/ivozprovider/scheme/./build.properties.production

ivozprovider > first-pass-migrate:

 [dbdeploy] Getting applied changed numbers from DB: mysql:host=data.ivozprovider.local;dbname=ivozprovider
Execution of target "first-pass-migrate" failed for the following reason: /opt/irontec/ivozprovider/scheme/build_prod.xml:35:16:
#0 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#1 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#2 /usr/share/php/phing/Target.php(297): Task->perform()
#3 /usr/share/php/phing/Target.php(320): Target->main()
#4 /usr/share/php/phing/Project.php(824): Target->performTasks()
#5 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#6 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#7 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#8 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#9 /usr/share/php/phing.php(43): Phing::fire(Array)
#10 {main}

Previous exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php:175
Stack trace:
#0 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(175): PDO->__construct('mysql:host=data...', 'root', 'changeme')
#1 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(153): DbDeployTask->getAppliedChangeNumbers()
#2 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#3 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#4 /usr/share/php/phing/Target.php(297): Task->perform()
#5 /usr/share/php/phing/Target.php(320): Target->main()
#6 /usr/share/php/phing/Project.php(824): Target->performTasks()
#7 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#8 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#9 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#10 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#11 /usr/share/php/phing.php(43): Phing::fire(Array)
#12 {main}

BUILD FAILED
/opt/irontec/ivozprovider/scheme/build_prod.xml:35:16:
#0 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#1 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#2 /usr/share/php/phing/Target.php(297): Task->perform()
#3 /usr/share/php/phing/Target.php(320): Target->main()
#4 /usr/share/php/phing/Project.php(824): Target->performTasks()
#5 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#6 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#7 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#8 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#9 /usr/share/php/phing.php(43): Phing::fire(Array)
#10 {main}

Previous exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php:175
Stack trace:
#0 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(175): PDO->__construct('mysql:host=data...', 'root', 'changeme')
#1 /usr/share/php/phing/tasks/ext/dbdeploy/DbDeployTask.php(153): DbDeployTask->getAppliedChangeNumbers()
#2 /usr/share/php/phing/UnknownElement.php(96): DbDeployTask->main()
#3 /usr/share/php/phing/Task.php(260): UnknownElement->main()
#4 /usr/share/php/phing/Target.php(297): Task->perform()
#5 /usr/share/php/phing/Target.php(320): Target->main()
#6 /usr/share/php/phing/Project.php(824): Target->performTasks()
#7 /usr/share/php/phing/Project.php(797): Project->executeTarget('migrate')
#8 /usr/share/php/phing/Phing.php(590): Project->executeTargets(Array)
#9 /usr/share/php/phing/Phing.php(170): Phing->runBuild()
#10 /usr/share/php/phing/Phing.php(278): Phing::start(Array, NULL)
#11 /usr/share/php/phing.php(43): Phing::fire(Array)
#12 {main}
Total time: 0.0615 seconds

dpkg: error processing package ivozprovider-scheme (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up bind9utils (1:9.9.5.dfsg-9+deb8u15) ...
Setting up bind9 (1:9.9.5.dfsg-9+deb8u15) ...
Adding group `bind' (GID 115) ...
Done.
Adding system user `bind' (UID 109) ...
Adding new user `bind' (UID 109) with group `bind' ...
Not creating home directory `/var/cache/bind'.
wrote key file "/etc/bind/rndc.key"
#
Setting up libstring-crc32-perl (1.5-1+b1) ...
Setting up libgearman-client-perl (1.11-3) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 ivozprovider-scheme
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Kaian** [comment]
Check #471 issue

**Comment by vobi2017** [comment]
That's  no help to me mate. Can you tell me what I need to do to fix it, thats all I need to know.

**Comment by vobi2017** [comment]
dpkg: error processing package ivozprovider-scheme (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 ivozprovider-scheme

**Comment by Kaian** [comment]
Can you ping _data.ivozprovider.local_ ?

Can you provide the contents of `/etc/resolv.conf` and `/etc/bind/db.ivozprovider.local`?

Regards

**Comment by Kaian** [comment]
Does the command

echo get ivozprovider/mysql_password| debconf-communicate

match the same password you configured for your mysql?

Can you log in with 

mysql -h data.ivozprovider.local -p ivozprovider

Regards

**Comment by vobi2017** [comment]
domain ivozprovider.local
search ivozprovider.local
nameserver 127.0.0.1



and /etc/bind/db.ivozprovider.local

Does not exist

**Comment by vobi2017** [comment]
0 my_mysql_password

 

 

this is what is says and  that’s not my password.

 

Regards,

 

Matthew Reading

Director

 

eMail:  <mailto:mr@vobi.com.au> mr@vobi.com.au

Sales/Support: 08 6478 3636

Sales eMail:  <mailto:info@vobi.com.au> info@vobi.com.au

Support Mail:  <mailto:help@vobi.com.au> help@vobi.com.au

Web:  <https://vobi.com.au/> https://vobi.com.au

 



 <https://play.google.com/store/apps/details?id=com.vobi>  <https://itunes.apple.com/us/app/vobi-phone/id1363852663?mt=8>

**Comment by vobi2017** [comment]
PING data.ivozprovider.local (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.030 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.041 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.031 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.033 ms

yest can ping

**Comment by vobi2017** [comment]
Can you log in with

mysql -h data.ivozprovider.local -p ivozprovider


no with or without password.

**Comment by Kaian** [comment]
You can change that value with a command mentioned in #471

Then you could try finishing the installation with apt-get -f install 

Regards

**Comment by Kaian** [comment]
You are receiving access denied from mysql.

You must configure your password in debconf to match your root password. You seem to have copy pasted the commands from #471, but you must replace 'my_mysql_password' with your root mysql password in the command.

**Comment by vobi2017** [comment]
echo set ivozprovider/mysql_password my_mysql_password | debconf-communicate

anf get this

debconf-communicate
0 value set


ill try run that command

**Comment by Kaian** [comment]
Sorry mate, sad to hear that.

This software has been installed without problems without using the iso (there is also a video in the readme with the process from one of our users). 

We use this software on production environments, but use whatever you feel confortable.

If you want software to improve or need installation support don't hesitate to conctact our comercial team at comercial@irontec.com. I have wasted 20 minutes here. 

Best wishes.

**Comment by vobi2017** [comment]
But the help you giving (and I am following the docs) is a reference to a page that has a million conversations in it. Why dont you update yoru docs with the solution if its happend before. Saves you replying a million times to someone.

**Comment by vobi2017** [comment]
It would of been fixed.

there was no db created. whem the install was running it was all entered coreectly its a fresh debian copy to the specs. ive re deploed the os every timw it happens and then start from scratch and its the same thing. I mean its clear somewhere in the script its not right and expects something and does not get it. 

If you fix it and put the fix on the docs then people woukd not have the issue if the read the docs. 

I dont want to pay for help installing somethign that should work asentiond in the docs. Thats crap.

What humans do that.

**Comment by rallisf1** [comment]
Not meaning to re-open this, just a clarification to help other users that bumped into the same situation (migrations not being run during install).

Make sure that you set a mysql password on both install prompts. The first prompt configures the mysql server, the second prompt (ivozprovider config menu) configures the php app which creates the database. Leaving the password empty, skipping a step or using different password across the 2 prompts will result in a broken installation!

To reinstall ivozprovider without re-installing your OS simply:
```
apt-get remove ivozprovider
apt-get autoremove
reboot
apt-get install ivozprovider
```
