### ISSUE TITLE
bleeding tests feedback

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#554]
I had not been able to make tests for the last two or three weeks on bleeding nor artemis because I was always getting an error on internal and external calls (some error saying something about type null in one of the kamailios)

This weekend I have decided to reinstall bleeding standalone in my test vm from scratch. Took me a while to make it work because I found two problems.

cgr-engine was not being started not sure why. I don't know exactly how I solved it as I tried to stop/start serveral times cgrates.service and cgrates-loader.timer and I did a flushall on redis console too.

The other problem I found is that I had not audio at all until I edited AUDIO_SOCK in rtpengine configuration. Its value was 127.0.0.1 and I edited it to use my public IP instead. After doing that and restarting services I had correct audio in both ways. Besides it works no matter which of my public IPs I use as AUDIO_SOCK. Works with kamailio trunks IP and works with kamailio users IP too. And no matter which is the primary or which is the secondary IP either.

As I commented on other issue I had audio problems when using a secondary IP as audio socket in previous bleeding versions and in oasis version.

There is audio in both ways on forwarded calls too. Something that was not working for me in oasis tests nor in previous bleeding versions where I was experimenting one way audio even using primary IP as audio socket.

Don't know which of the commits solved all those audio problems but great job.

**Comment by Kaian** [comment]
Hi @manfer 

Thanks for the feedback! We're introducing lots of changes that may break things, so testing without expecting everything will work and reporting back is highly appreciated! 

I myself removed rtpproxy support a couple days ago, making rtpengine the unique and default media relay for everyone. I changed the default variables AUDIO_SOCK and CONTROL_SOCK (this one is new) but most probably forgot to update the postinstall scripts that updates the audio ip (the old variable name was IP).

I thought the audio problem with the secondary IP address was related with asterisk, but it could also be a strict behaviour in rtpproxy. Anyway we expect an update in asterisk version soon to the latest LTS, so I hope the audio flows will be clearer (Iirc newest version uses the same address for transport and audio,  which is localhost for standalone) 


That said, thanks a lot for the feedback. Keep the good work!!

Regards!

**Comment by Kaian** [comment]
I have fixed the AUDIO_SOCK substitution in https://github.com/irontec/ivozprovider/commit/aef2f94edba8441bbbcc2c6424dc46fb519416c5 so the user.ivozprovider.local address will be used also for media relay as we did it before :)

I think we don't leave nothing pending, so I'm closing this. Feel free to reopen or any other information!

Thanks for the feedback @manfer
