### ISSUE TITLE
dpkg-reconfigure ivozprovider is not working on ivozprovider-standalone 4.9.0-6-amd64

### ISSUE THREAD

**Issue by dsmaldone** [irontec/ivozprovider#556]
Hi guys,
on 
root@ivozprovider-standalone:# uname -a
Linux ivozprovider-standalone 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

seems the command dpkg-reconfigure is not working at all
![screenshot from 2018-06-25 14-12-31](https://user-images.githubusercontent.com/38856598/41849650-f269eb9c-7881-11e8-8f5a-983b716f0a78.png)
after done my mods (SIP proxy/trunk and mysql) when I confirm service reload
![screenshot from 2018-06-25 14-12-46](https://user-images.githubusercontent.com/38856598/41849670-0e594b0e-7882-11e8-8b95-a92cf910b5ec.png)
nothing is changing in the config and also in mysql

I didn't find any related log to post, but if you point me to some place where to look for, I will pos them

To fix proxy and trunk and rtpengine config, I had to edit bind (/etc/bind/db.ivozprovider.local) and rtpengine (/etc/default/rtpengine) config manually

**Comment by dsmaldone** [comment]
artemis 2.30 confirm!

**Comment by Kaian** [comment]
I confirm this is failing badly.

The postinstall script is expecting 'reconfigure' as argument but 'configure' is being passed by dpkg. Also the are some errors in some text replaces in configuration files and mysql password changer won't work (it's logging with the new password to change to the new password!). Quite buggy.

We didn't focus too much in standalone in the testing branch so thanks a lot for the testing and feedback :)

I'll try to fix this for 2.4.0

**Comment by Kaian** [comment]
I have fixed this in https://github.com/irontec/ivozprovider/commit/2e181bcaac5282ac9fd4f50b33e773254a3dca7f so It will work as expected in 2.4

As soon as the release has been published, you can upgrade your environment from 2.3.0 to 2.4.0 using the package repositories as documented [here](https://irontec.github.io/ivozprovider/en/bleeding/basics/installation/debian_install.html)

Thanks for reporting!!

**Comment by dsmaldone** [comment]
I'm looking forward to your new release!
Thanks!

**Comment by Kaian** [comment]
I'll mark this as fixed. If find any problem feel free to reopen!

Thanks!
