### ISSUE TITLE
Last provision date is wrong

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#56]
In Terminals you can see last provision date for each phone.

The information shown is not reliable.

**Comment by Kaian** [comment]
Last provision date is setted [here](https://github.com/irontec/ivozprovider/blob/b75f5e6ca09e84671eedfc2113ffcabf350c0f9f/portals/application/modules/provision/controllers/IndexController.php#L76) before rendering the page.

If template has somehow syntax errors and can not be served, the date is updated anyways.
I'm not sure if `render` method throws Exceptions or something. If so, then the date should be setted after ensuring the rendering has been correct (and assume the terminal has understand everything in the content).
