### ISSUE TITLE
route locks codes

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#564]
The default brand that comes preinstalled with ivozprovider has no route locks service codes defined which leads to confusing handling of route locks feature until you create those service codes on the brand.

New brands created later are assigned *70, *71 and *72 as predefined service codes to close, open, toggle lock state respectively

Tested in oasis but maybe same problem on bleeding.

**Comment by Kaian** [comment]
Hi @manfer 

Yep, this affect both releases.

DemoBrand and DemoCompany have no services for RouteLocks. We should add some migrations to add them taking into account that both default brand and company could have been deleted.

Thanks!

**Comment by Kaian** [comment]
This should fixed for new installations for oasis (5eda0e5) and artemis (b139ad8) releases.

Thanks for reporting!
