### ISSUE TITLE
oasis: typo on voicemail controller leads to wrong character encoding

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#565]
In /ivozprovider/asterisk/agi/application/controllers/VoicemailController.php the line:

```
$mail = new Zend_Mail('utf8');
```

should be:

```
$mail = new Zend_Mail('utf-8');
```

**Comment by mmadariaga** [comment]
It look like VoicemailController is not the only place with that problem: 

./asterisk/agi/library/Agi/Action/FaxCallAction.php => $mail = new \Zend_Mail('utf8');
./asterisk/agi/application/controllers/VoicemailController.php => $mail = new Zend_Mail('utf8');
./portals/application/workers/XmlrpcWorker.php => $mail = new \Zend_Mail();
./portals/application/workers/XmlrpcdelayedproxytrunksWorker.php => $mail = new \Zend_Mail();
./kamailio/recordings/application/controllers/RecordingsController.php => $mail = new Zend_Mail('utf8');

**Comment by mmadariaga** [comment]
Fixed in https://github.com/irontec/ivozprovider/pull/568
