### ISSUE TITLE
artemis: Italian Language Support

### ISSUE THREAD

**Issue by dsmaldone** [irontec/ivozprovider#567]
Hi...following https://github.com/irontec/ivozprovider/pull/566#issuecomment-400641155

"Hi guys, I would like to help you with publishing and maintaining the Italian translations starting from artemis2.3.0 which is the one who I'm dealing with"

**Comment by Kaian** [comment]
Hi @dsmaldone 

It would be nice to add a new language to the platform! I think the easiest approach would be starting with the administration portal, but it will require some changes in order to enable a new language. 

We're very close to 2.4.0 due date, so If you don't mind waiting to include the new language in 2.5.0, I can prepare the portal so you only have to translate the generated strings and generate a Pull request with the changes. Is this ok for you?

Thanks in advance!

**Comment by dsmaldone** [comment]
Hi @Kaian ok to me

Waiting for further instructions

**Comment by Kaian** [comment]
Hi @dsmaldone 

I have created a feature branch called [`web-admin-italian`](https://github.com/irontec/ivozprovider/tree/web-admin-italian) that has the required changes to enable italian translation of web administration portal. The translation files are located in the [languages](https://github.com/irontec/ivozprovider/tree/web-admin-italian/web/admin/application/languages) directory, and right now all the italian strings are empty.

You can use that branch as starting point for generating a Pull request with your changes.

Take into account this would only translate the portal to Italian. Enabling the language for companies and users would require much more work (multilang tables, locutions, and so on).

Regards!

**Comment by dsmaldone** [comment]
Hi Guys,
I'm sorry for the very long delay in answering here
Do you think we can still go ahead with this?
From where I should start? Which version?

Regards
Danilo
___________________

Danilo SMALDONE
Senior ICT Systems Manager

*Coordinatore AIP-ITCS Basilicata - *

*AIP 4229Albo dei Periti CCIAA Potenza N° 207*
*CCNA CSCO12263938*
*MTCNA 1605NA343*
*MTCRE 1606RE114*
*MTCWE 1607WE022+39 335 6769084*
<https://it.linkedin.com/in/danilo-smaldone-17178a51>
This e-mail and any attachment hereto is intended only for the person or
entity to which is addressed and may contain information that is
privileged, confidential or otherwise protected from disclosure.
Copying, dissemination or use of this e-mail or the information herein by
anyone other than the intended recipient is prohibited. If you have
received this e-mail by mistake, please notify me immediately by telephone.

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi
invito cortesemente a darmene notizia e a distruggere il messaggio. Vi
ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati
ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs.
196/03 (Codice della Privacy, in materia di protezione dei dati personali).


Il giorno mar 17 lug 2018 alle ore 11:36 Kaian <notifications@github.com>
ha scritto:

**Comment by Kaian** [comment]
Hi @dsmaldone 

I would start with administration portal translation files of latest release. You can get them here: https://github.com/irontec/ivozprovider/blob/bleeding/web/admin/application/languages/en_US/en_US.po

Thanks!!

**Comment by dsmaldone** [comment]
Hi guys,
Italian translations uploaded through git with tag bc28efb39d2ee6dcc07e76502999ea87c4fe12c7

Waiting for your feedback
Regards
Danilo
_____________________________

Danilo SMALDONE
Senior ICT Systems Manager

Albo dei Periti CCIAA Potenza N° 207
CCNA CSCO12263938
MTCNA1605NA343
MTCRE 1606RE114
​MTCWE 1607WE022
+39 335 6769084
 
This e-mail and any attachment hereto is intended only for the person or entity to which is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. 
Copying, dissemination or use of this e-mail or the information herein by anyone other than the intended recipient is prohibited. If you have received this e-mail by mistake, please notify me immediately by telephone. 

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi invito cortesemente a darmene notizia e a distruggere il messaggio. Vi ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs. 196/03 (Codice della Privacy, in materia di protezione dei dati personali).

**Comment by Kaian** [comment]
Hi Danilo,

The commit you mention has the file it_IT.po with all strings in english. Don't bother with the filename, just start translating other existing file (for example spanish) to italian. Then after all the strings has been translated, upload the file here or send us to the email.

In your environment, go to web/admin path
    
    cd /opt/irontec/ivozprovider/web/admin

Update the contents of application/language/es_ES/es_ES.po file with strings in italian, then run

    application/bin/translate.pl update

To show the translated strings in the portal (change the portal language to spanish, you can choose it in the top left corner of the portal).

Thanks!

**Comment by Kaian** [comment]
Oh my bad, now I see the translations, they are in the commit https://github.com/irontec/ivozprovider/pull/1069/commits/93892fb47de7b50ec56b45bb93c5400c04baca65

Thanks!

**Comment by dsmaldone** [comment]
Hi!
Very happy to help here!
Let me know what I can do to help you more here!

Regards
Danilo
___________________

Danilo SMALDONE
Senior ICT Systems Manager

*Coordinatore AIP-ITCS Basilicata - *

*AIP 4229Albo dei Periti CCIAA Potenza N° 207*
*CCNA CSCO12263938*
*MTCNA 1605NA343*
*MTCRE 1606RE114*
*MTCWE 1607WE022+39 335 6769084*
<https://it.linkedin.com/in/danilo-smaldone-17178a51>
This e-mail and any attachment hereto is intended only for the person or
entity to which is addressed and may contain information that is
privileged, confidential or otherwise protected from disclosure.
Copying, dissemination or use of this e-mail or the information herein by
anyone other than the intended recipient is prohibited. If you have
received this e-mail by mistake, please notify me immediately by telephone.

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi
invito cortesemente a darmene notizia e a distruggere il messaggio. Vi
ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati
ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs.
196/03 (Codice della Privacy, in materia di protezione dei dati personali).


Il giorno lun 15 lug 2019 alle ore 10:21 Kaian <notifications@github.com>
ha scritto:

**Comment by dsmaldone** [comment]
Hi All
After checking with the translate.pl update script, I found few issues which are preventing the system creating the "final product” es_ES.mo

I will publish fixes soon

Regards
Danilo
_____________________________

Danilo SMALDONE
Senior ICT Systems Manager

Albo dei Periti CCIAA Potenza N° 207
CCNA CSCO12263938
MTCNA1605NA343
MTCRE 1606RE114
​MTCWE 1607WE022
+39 335 6769084
 
This e-mail and any attachment hereto is intended only for the person or entity to which is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. 
Copying, dissemination or use of this e-mail or the information herein by anyone other than the intended recipient is prohibited. If you have received this e-mail by mistake, please notify me immediately by telephone. 

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi invito cortesemente a darmene notizia e a distruggere il messaggio. Vi ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs. 196/03 (Codice della Privacy, in materia di protezione dei dati personali).

**Comment by Kaian** [comment]
Hi Danilo,

translate.pl is working ok in our development environments and tests, before posting a fix, can you elaborate what the problem is?

Thanks

**Comment by dsmaldone** [comment]
That’s what I found



Now after fixing some missing “double quotes” and some typos it’s ok and correctly working



Regards
Danilo
_____________________________

Danilo SMALDONE
Senior ICT Systems Manager

Albo dei Periti CCIAA Potenza N° 207
CCNA CSCO12263938
MTCNA1605NA343
MTCRE 1606RE114
​MTCWE 1607WE022
+39 335 6769084
 
This e-mail and any attachment hereto is intended only for the person or entity to which is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. 
Copying, dissemination or use of this e-mail or the information herein by anyone other than the intended recipient is prohibited. If you have received this e-mail by mistake, please notify me immediately by telephone. 

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi invito cortesemente a darmene notizia e a distruggere il messaggio. Vi ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs. 196/03 (Codice della Privacy, in materia di protezione dei dati personali).

**Comment by dsmaldone** [comment]
Hi guys
Is there something more I can do for you here?

Danilo
_____________________________

Danilo SMALDONE
Senior ICT Systems Manager

Albo dei Periti CCIAA Potenza N° 207
CCNA CSCO12263938
MTCNA1605NA343
MTCRE 1606RE114
​MTCWE 1607WE022
+39 335 6769084
 
This e-mail and any attachment hereto is intended only for the person or entity to which is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. 
Copying, dissemination or use of this e-mail or the information herein by anyone other than the intended recipient is prohibited. If you have received this e-mail by mistake, please notify me immediately by telephone. 

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi invito cortesemente a darmene notizia e a distruggere il messaggio. Vi ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs. 196/03 (Codice della Privacy, in materia di protezione dei dati personali).

**Comment by Kaian** [comment]
Hi @dsmaldone 

We will do the rest of the modifications required to include the new language. Thanks for the translation.

You can also translate the user portal, strings are located [here](https://github.com/irontec/ivozprovider/blob/bleeding/web/user/app/languages/locale-en.json) 

Thanks!

**Comment by Kaian** [comment]
web/admin italian translations have been included in 2.12.0

Translations change often so we appreciate if you keep them updated!

Thanks a lot for your contribution!

**Comment by dsmaldone** [comment]
Happy to help!

I will!
_____________________________

Danilo SMALDONE
Senior ICT Systems Manager

Albo dei Periti CCIAA Potenza N° 207
CCNA CSCO12263938
MTCNA1605NA343
MTCRE 1606RE114
​MTCWE 1607WE022
+39 335 6769084
 
This e-mail and any attachment hereto is intended only for the person or entity to which is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. 
Copying, dissemination or use of this e-mail or the information herein by anyone other than the intended recipient is prohibited. If you have received this e-mail by mistake, please notify me immediately by telephone. 

Se aveste ricevuto questa e-mail per errore, mi scuso per l'accaduto e Vi invito cortesemente a darmene notizia e a distruggere il messaggio. Vi ricordo che la diffusione, l’utilizzo e/o la conservazione dei dati ricevuti per errore costituiscono violazioni alle disposizioni del D.Lgs. 196/03 (Codice della Privacy, in materia di protezione dei dati personali).
