### ISSUE TITLE
Fanvil phones problem

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#571]
Tested on oasis.

Maybe is a fanvil issue but just in case I comment here what is happening.

When you register a fanvil X5S (most probable any other model too) to ivozprovider almost everything works fine. But... when the phone makes calls to the outside and on call tries to hang up the call, the bye is rejected by kamailio users with a "404 not here" so kamailio trunks does not hang up the call which is a huge problem.

What I can see is that fanvil phone does not send contact header on the bye SIP message on a call it has started.

For same or similar reason when same fanvil phone starts a call to the outside and tries to set the call on hold it can't. So it can't place the call on hold, nor transfer the call.

When the call is an incoming call to the fanvil phone, it can correctly hang up the call, and put the call on hold. I see the bye SIP message includes the contact header in this case.

**Comment by cruzccl** [comment]
Hi @manfer,

We don't have any Fanvil phones here, so we would need a PCAP file here to determine what is happening. Kamailio's log messages would be helpful too.

Thanks for testing!

**Comment by manfer** [comment]
Can I send you the PCAP (oasis test) by mail?

My bleeding install does not allow outgoing calls just now while you are developing new retailclient and renaming previous one. As soon as it works again I will try with bleeding too.

**Comment by cruzccl** [comment]
Hi @manfer,

I think that it would be better if you attached the PCAP file here. This way it may be useful to other users.

Regards,

**Comment by Kaian** [comment]
> My bleeding install does not allow outgoing calls just now while you are developing new retailclient and renaming previous one. As soon as it works again I will try with bleeding too.

With no intention to hijack this issue, and just to let you know; newly created residential devices (the old retail accounts) should work in the last bleeding version. We recently fixed a problem with endpoint context in https://github.com/irontec/ivozprovider/commit/822bb3621edb555d2e293cecf9ea7b97f16583a3

Also, the migration has been updated to change existing accounts context in https://github.com/irontec/ivozprovider/commit/1124f9ff5269603496ad72581ee8e7833ec090f3

Regards!

**Comment by manfer** [comment]
> Hi @manfer,
> 
> I think that it would be better if you attached the PCAP file here. This way it may be useful to other users.
> 
> Regards,

The problem is a PCAP contains a lot of private info (IPs, phone numbers) and I don't know how to fully annonymize it. I have tried annonymize software some time ago and the result wasn't good enough in my opinion. Not sure if I had not been able to use the software properly.

At first glance it is not easy to fully annonymize a PCAP.

**Comment by manfer** [comment]
> With no intention to hijack this issue, and just to let you know; newly created residential devices (the old retail accounts) should work in the latest bleeding version (if not, please open an issue with further information!). We recently fixed a problem with endpoint context in 822bb36
> 
> Also, the migration has been updated to change existing accounts context in 1124f9f
> 
> Regards!

After upgrading the system with last versions on repositories I get this error when trying to access the web administration.

```
Warning: require(/opt/irontec/ivozprovider/web/rest/var/cache/prod/doctrine/orm/Proxies/__CG__IvozProviderDomainModelBrandBrand.php): failed to open stream: No such file or directory in /opt/irontec/ivozprovider/library/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

Fatal error: require(): Failed opening required '/opt/irontec/ivozprovider/web/rest/var/cache/prod/doctrine/orm/Proxies/__CG__IvozProviderDomainModelBrandBrand.php' (include_path='/opt/irontec/ivozprovider/web/admin/application/library:/opt/irontec/klear/library:/opt/irontec/ivozprovider/web/admin/application/library::/usr/share/php:/opt/irontec/ivozprovider/library:/opt/irontec/klear/library:/opt/irontec/ivozprovider/web/admin/library') in /opt/irontec/ivozprovider/library/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209
```

I will try to upgrade a little later just in case there is a newer version in repositories.

**Comment by Kaian** [comment]
Cache clear commands are not working like they should do.. I also have experienced that today :disappointed: As workaround, manually remove the cache, it will generate it again on first load.

```
rm -fr /opt/irontec/ivozprovider/web/rest/var/cache/prod
```

**Comment by manfer** [comment]
> Cache clear

Done and working again. I will test tomorrow if fanvil works the same or not with bleeding version. Thanks.

**Comment by manfer** [comment]
> I will test tomorrow if fanvil works the same or not with bleeding version

Still unable to make external calls with bleeding version. I'm testing with a User from a Virtual PBX.

First thing I have notice after last update the pbx sip domain had been reseted to default kamusers IP. I'm using the demo pbx but with parameters already edited.

But after correcting that problem I still can't make outgoing calls. 

Proxy users log
> [jun 29 10:05:35] [8a3621bf] MANAGE-FAILURE-AS: INVITE FAILED: '503 Service Unavailable' to '2 INVITE' from 'sip:fanvil1@sip.my.domain.es' (xxx.xxx.xxx.xxx:5060) [udp]
> [jun 29 10:05:35] [8a3621bf] RTPENGINE: NAT detected, do not trust SDP addresses
> [jun 29 10:05:35] [8a3621bf] RTPENGINE: rtpengine_manage [replace-session-connection replace-origin SIP-source-address ICE=remove RTP/AVP <null>]
> [jun 29 10:05:35] [8a3621bf] MANAGE-FAILURE-AS: No failover for '503 Service Unavailable', forward reply

Proxy Trunks log
> [jun 29 10:05:35] [b0844844] LOAD-GWS: No valid gateway for '+34XXXXXXXXX' for company '1'

**Comment by manfer** [comment]
> [jun 29 10:05:35] [b0844844] LOAD-GWS: No valid gateway for '+34XXXXXXXXX' for company '1'
> This usually means there is no outgoing routing for that company and destination with a Contract Peering with valid Peering Servers. Check your Peer Servers address and ensure they're reachable and are capable of answering OPTIONS. If you're using DNS for your PeerServers ensure it actually resolves to something.

Same peer used on oasis tests, no DNS, just a static IP.

The peer is contacted from same machine and same IP, different VM for oasis and bleeding. Only one of the VM running at a time.

It was possible to make outgoing calls recently on that bleeding machine. Peer configuration has not been modified.

I have tried and incoming call and works. I make an outgoing call just inmediatly after that incomming call and it works.

Wait some minutes try and outgoing call and it does not work.

I made an incomming call followed by an outgoing call and again it works.

I waited 5 minutes made and outgoing call -not making and incomming call first- and again it fails.

No clue what's the problem.

**Comment by manfer** [comment]
About the fanvil issue. Same behaviour. When the fanvil starts an outgoing call to the outside it can't hangup the call.

To be more specific. When the fanvil phone starts a call to the outside and before the other party answers the phone it can hangup the call correctly. But, once the other party answers the call if the fanvil tries to hangup the call, the bye sip message is rejected by kamailio users with the 404 not here error so the by message is not delivered to kamailio trunks.

**Comment by Kaian** [comment]
> I waited 5 minutes made and outgoing call -not making and incomming call first- and again it fails.

Wow, that erratic behavior that fixes with time worries me a lot. I have not experienced myself this kind of problems, not even during stress testing. Artemis is not yet production ready, but basic calls should work (we run telephony tests automatically after every merge). If I run into something similar I'll report here anything I discover.

Thanks for the testing @manfer !

**Comment by manfer** [comment]
> Wow, that erratic behavior that fixes with time worries me a lot. I have not experienced myself this kind of problem, not even during stress testing. Artemis is not yet production ready, but basic calls should work (we run telephony tests automatically after every merge). If I run into something similar I'll report here anything I discover.

I created another issue related to this. This was an issue with my trunk provider. They took a month to solve. Luckily this was just a testing install not in production.

As soon as possible I'm going to try to create a brief description of the pcaps of fanvil phone annonymizing it to show the fanvil phones behaviour.

**Comment by manfer** [comment]
New Fanvil firmware solves this issue.

The bye sip message from fanvil phone to kamailio proxy on old firmware versions is like this:

```
BYE sip:888888888@sip.example.com SIP/2.0
Via: SIP/2.0/UDP 192.168.xxx.xxx:5060;branch=z9hG4bK33011356645488357110;rport
Route: <sip:zzz.zzz.zzz.zzz;lr;ftag=4629259545;did=e2c.0431;nat=yes>
From: johndoe <sip:jonhdoe@sip.example.com>;tag=4629259545
To: <sip:888888888@sip.example.com>;tag=84c3536c-c3d9-4911-9117-69c392f2b21e
Call-ID: 587784804326048-2453968149909@yyy.yyy.yyy.yyy
CSeq: 3 BYE
Contact: <sip:johndoe@yyy.yyy.yyy.yyy:1644>
Max-Forwards: 70
User-Agent: Fanvil X5S 1.4.4.2
Mac: aa:aa:aa:aa:aa:aa
Content-Length: 0
```

where:

```
192.168.xxx.xxx		-> local IP of fanvil phone
yyy.yyy.yyy.yyy		-> public IP of fanvil phone gateway
zzz.zzz.zzz.zzz		-> IP of kamailio users
888888888		-> anonymized DDI
```

Kamailio replies to this bye message with a 404 not found.

On newer firmware the bye message reads like this:

```
BYE sip:127.0.0.1:6060 SIP/2.0
Via: SIP/2.0/UDP 192.168.xxx.xxx:5060;branch=z9hG4bK2950543731207254744;rport
Route: <sip:zzz.zzz.zzz.zzz;lr;ftag=6296227800;did=75b.7942;nat=yes>
From: johndoe <sip:johndoe@sip.example.com>;tag=6296227800
To: <sip:888888888@sip.example.com>;tag=cd694c4d-4c46-44ff-bb48-896f8e04c9ab
Call-ID: 34201447261386-309593182842608@yyy.yyy.yyy.yyy
CSeq: 3 BYE
Contact: <sip:johndoe@yyy.yyy.yyy.yyy:1644>
Max-Forwards: 70
User-Agent: Fanvil X5S 1.6.1 aaaaaaaaaaaa
Mac: aa:aa:aa:aa:aa:aa
Content-Length: 0
```

And it works properly.

**Comment by Kaian** [comment]
Good to know it was not our fault!

Is there anything pending or is this ready to be closed?

**Comment by manfer** [comment]
It can be closed thanks.

**Comment by Kaian** [comment]
You welcome!
