### ISSUE TITLE
close all tabs

### ISSUE THREAD

**Issue by miquelinv** [irontec/ivozprovider#580]
Hello

As a suggestion for improvements, a button that closes all the open tabs would be appreciated.

thanks and congratulations for the project

**Comment by mmadariaga** [comment]
Hi @miquelinv,

There are some keyboard shortcuts that you may find helpful:
```
Ctrl+Alt+AvPag: goes to next tab.
Ctrl+Alt+RePag: goes to previous tab.
Ctrl+Alt+E: toggles unselected tab names.
Ctrl+Alt+H: toggles header view.
Ctrl+Alt+I: toggles help dialog.
Ctrl+Alt+M: toggles menu view.
Ctrl+Alt+Q: close other tabs.
Ctrl+Alt+R: reloads current tab.
Ctrl+Alt+W: closes current tab.
Ctrl+Alt+X: toggles fullscreen view.
```

**Comment by Kaian** [comment]
Sadly, it's common to end up with lots of tabs, and some of them have long titles....

I usually press Ctrl + Alt, then Q followed with W to achieve this.
