### ISSUE TITLE
question: kamailio lcr ping

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#582]
My trunk provider is not replying to lcr ping unless I first make an incoming call to ivozprovider.

For this reason outgoing calls does not work because ivozprovider thinks the trunk is down. Outgoing calls only work inmediately after and incoming call. Not sure how long until the trunk is considered again down by ivozprovider.

I don't understand why my sip provider is replying to lcr ping correctly just after an incoming call but not after some minutes. Is my sip provider rejecting those pings incorrectly?

Just inmediately after an incoming call it looks like this
![pingaccepted](https://user-images.githubusercontent.com/458420/42341406-3ff79602-8093-11e8-8209-13a581def2d3.PNG)

But if there has not been an incoming call recently looks like this
![pingrejected](https://user-images.githubusercontent.com/458420/42341419-48c5acce-8093-11e8-91a2-cb5bd57e7c6a.PNG)

**Comment by Kaian** [comment]
Hi @manfer 

I'm assuming Oasis release for this.

OPTIONS should only be sent to peering servers if they don't respond to an initial request of a call. As soon as one of those options is answered, the server is marked as online again and no more OPTIONS are sent until it again doesn't not respond to an INVITE + re-transmissions.

Regards!

**Comment by manfer** [comment]
Hi @Kaian 

Indeed it is a test with oasis

Thanks for the clarification. Now it is clear when OPTIONS are send.

I don't understand why my sip provider doesn't reply back to those OPTIONS messages and why it does not reply to INVITES unless I make an incomming call first.

Seems a problem on my provider.

Thanks.

**Comment by Kaian** [comment]
No problem!

I'm closing this then. I think it would be good to document this somewhere, although is quite technical. We'll keep this issue as reference in case anyone ask how it works.

Regards!!
