### ISSUE TITLE
smtp server

### ISSUE THREAD

**Issue by miquelinv** [irontec/ivozprovider#583]
ivoz allows the sending by email of the messages of the voice mailbox and of the received faxes, but we do not see where to configure the smtp server

**Comment by Kaian** [comment]
Hi @miquelinv 

All emails are sent to the local MTA, so you can choose and configure your preferred software to do the task (postfix, exim, and so on).

Adding smtp options per brand has been requested in #162 but it's not in the 2.x roadmap.

Regards!

**Comment by miquelinv** [comment]
tested with exim 4. works fine
