### ISSUE TITLE
Default DID for Outgoing calls in Bussiness Level

### ISSUE THREAD

**Issue by jmedinagu** [irontec/ivozprovider#6]
To avoid in environments with many extensions in the same company, to have to go one by one specifying the outgoing DID, to be able to establish one by default at company level and to inherit it if one is not specified.

**Comment by cruzccl** [comment]
Hi Jorge,

Thank you very much for your feature request, we will keep it in mind as it seems to be interesting :)

We will give you feedback here, have a nice day!
