### ISSUE TITLE
ivozprovider rtpengine service

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#603]
On the rtpengine.service

https://github.com/irontec/rtpengine/blob/oasis/debian/ivozprovider-rtpengine.rtpengine.service

we can read

```
ExecStopPost=/sbin/iptables -D INPUT -p udp -j RTPENGINE --id 0
ExecStopPost=/bin/bash -c "/bin/echo del 0 > /proc/rtpengine/control"
```

If for some reason the iptables rule doesn't exist the second execstoppost command is not executed and the rtpengine service enters an inconsistent state.

You can just reproduce the bug by running

```
$ /sbin/iptables -D INPUT -p udp -j RTPENGINE --id 0
$ systemctl stop rtpengine
```

After that you can't start the service anymore until you run the second command.

```
$ /bin/bash -c "/bin/echo del 0 > /proc/rtpengine/control"
$ systemctl start rtpengine
```
 I'm not familiarized enough with service scripts to know a correct way to solve this

**Comment by cruzccl** [comment]
Hi @manfer,

Yes, that's quite annoying.

Reading about systemd, it seems that there is a way to consider all exit codes as success (read [Table 1, prefix "-"](https://www.freedesktop.org/software/systemd/man/systemd.service.html)):

```
If the executable path is prefixed with "-", an exit code of the command normally considered a failure (i.e. non-zero exit status or abnormal exit due to signal) is ignored and considered success.
```

Maybe changing the first ExecStopPost to

```
ExecStopPost=-/sbin/iptables -D INPUT -p udp -j RTPENGINE --id 0
```

could help?

Regards,

**Comment by manfer** [comment]
Hi cruzccl,

I tested your suggestion and works perfectly.

Would be great if that fix is implemented on ivozprovider-rtpengine package.

Thanks.

**Comment by cruzccl** [comment]
Done in bleeding https://github.com/irontec/rtpengine/commit/7e68bc85bf3f3611be69cad0a5846a4c71daa600

Thanks for testing!
