### ISSUE TITLE
oasis iso on system without DHCP

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#606]
When installing the oasis iso in a vm which network configuration must be done manually after install you get a working ivozprovider but with some problems.

I don't think this happens when the vm is able to automatically get a working network during iso install through DHCP. Probably it is not happening in that case. But not 100% sure now.

The problems I found so far:

------------------------------
Missing Repositories
------------------------------
There are no ivozprovider, no klear repositories configured on the system. And the ivozprovider public key is not installed.

Solved by running:

```
cd /etc/apt/sources.list.d
echo deb http://packages.irontec.com/debian oasis main extra > ivozprovider.list
echo deb http://packages.irontec.com/debian chloe main > klear.list
wget http://packages.irontec.com/public.key -q -O - | apt-key add -
```

------------------------------
RTPengine not Working
------------------------------
RTPengine does not work. There is no /proc/rtpengine directory. Trying to reinstall ivozprovider-rtpengine package leads to:

```
Your kernel headers for kernel xxxx cannot be found at
/lib/modules/xxxx/build or /lib/modules/xxxx/source
```

So to solve this issue I had to install linux kernel headers

`apt-get install linux-headers-$(uname -r)`

reinstall ivozprovider-rtpengine package

`apt-get install --reinstall ivozprovider-rtpengine`

and reboot.

I don't know if there is any other problem.

The oasis ISO I'm using is ivozprovider-1.7.0-oasis-amd64.iso downloaded on 25 May 2018.

**Comment by Kaian** [comment]
Hi @manfer 

These are actually not related to networking during installation:

### Missing Repositories

sources.list are not touched by ivozprovider packages in any way. It may be handy for ISO install but a bit rude for apt install. In case we want to do this, we can create a new optionalpackage _ivoprovider-apt-config_ that creates that configuration and imports the key and request the ISO to install two packages (ivozprovider and ivozprovider-apt-config). In the other hand, we can leave it as is and update ISO install documentation to point to sources.list configuration page as a final step.


### RTPengine not Working
Our rtpengine package  comes with sources for a kernel module that is compiled during package installation time. For the ISO installs, the kernel used whatever the ISO system runs and, in some cases, that kernel version doesn't match the one that will be installed. In that scenarios this problem arise.

Sadly, we can not choose which kernel the ISO will use (which is usually the lastest available in debian backports repository), but we can ensure the [rtpengine dependency](https://github.com/irontec/rtpengine/blob/oasis/debian/control#L22) matches the ISO kernel to avoid this problem (so both the kernel when the package is installed and the kernel after reboot are the same). 

Regards!

**Comment by manfer** [comment]
Hi @Kaian 

I think [linux-headers-amd64 meta-package](https://packages.debian.org/search?keywords=linux-headers-amd64) should be used as dependency to solve that issue

**Comment by Kaian** [comment]
Most probably, but I have to dig a bit of how to make the _amd64_ part dynamic during package buildtime bacause, although we're in 2018, we still ship ivozprovider for i386 😅  

Maybe there are substitution variables for architecture in debian control files

**Comment by Kaian** [comment]
I have give it a try to the ${Arch} package substitution variable and it doesn't fit our needs here.

ivozprovider-rtpengine package is currentyl builded for 3 architectures (amd64, i386 and armhf) and there is no virtual metapackage for all the linux-headers versions.

For example: _linux-headers-amd64_ exists but not _linux-headers-i386_. Even trying to use _linux-headers-i686_ (that is available for i386 architecture in debian repositories) doesn't seem to work while building the iso with _simple-cdd_ (the software we use to generate the isos with the repository packages). So this seems a dead end.

I will and upate oasis rtpengine dependencies based on the latest jessie kernel that the iso updates to at least fix this for ISO install, although I can still fail while installing using repository packages.

Regards

**Comment by Kaian** [comment]
> I will and upate oasis rtpengine dependencies based on the latest jessie kernel that the iso updates to at least fix this for ISO install, although I can still fail while installing using repository packages.

This should be fixed in latest oasis iso (1.7.1), both iso kernel and installed kernel are fixed to 3.16.0-6 so rtpengine should work out of the box after iso install

**Comment by Kaian** [comment]
I'm not sure if we reached some conclusions here, but in any case the issue title is misleading. 

rtpengine + kernel problem is something I check with every release iso until we drop i386 or find a way to determine target kernel.

The ivozprovider-apt-config could be done but is a feature request more than an issue.

Thoughts?

**Comment by manfer** [comment]
This can be closed. The ISO was already updated and everything explained.

**Comment by Kaian** [comment]
Cool! Closing then!

Thanks!
