### ISSUE TITLE
oasis: losing calls at night and morning (trunk keepalive?)

### ISSUE THREAD

**Issue by amvidalrc** [irontec/ivozprovider#608]
Hello Team!
I have a extrange problem, and I want to know if its a my provider problem or maybe it's a configuration issue. I will try to explain but later I will write in Spanish too:

I have a big volume of calls for the morning and afternoon, but I have only residual calls on the night. When, for example, I try to call at 00:00 the calls goes nowhere, is like the trunk is disconnected. When I make an incoming call and try to call again, the call goes perfect. 

I have some customers complaining because when they arrive the office, for example at 07:00 have the same problem, they can't call. 

Is there any way to keepalive the trunk??

thanks in advance!!

ES:

En resumen, creo que el troncal se cae cuando no hay actividad, o el IVP no está haciendole el keepalive correctamente y se cierra. En Asterisk puro tenía el Qualify cada poco y no tenía problemas. ¿Hay alguna forma de hacerlo en Oasis? ¿Alguna sugerencia?

Gracias!

**Comment by cruzccl** [comment]
Hi @amvidalrc,

Carriers / PeeringContracts handling is done via [LCR kamailio module](http://kamailio.org/docs/modules/4.4.x/modules/lcr.html).

This module activates SIP OPTIONS pinging only when a carrier is inactivated due to failures (see [inactivate_gw()](http://kamailio.org/docs/modules/4.4.x/modules/lcr.html#idp27385444) and ping_* modparams).

There is no way to send SIP OPTIONS when carriers are OK and I don't see why this should be necessary. It would generate a lot of unneeded SIP traffic.

You can send periodic REGISTERs though, that may work for you :thinking: 

Regards,

**Comment by amvidalrc** [comment]
How I can send that registers?? I'm good in Asterisk but don't have any experience with Kamailio.Thanks in advanceÁlvaro. -------- Mensaje original --------Asunto: Re: [irontec/ivozprovider] oasis: losing calls at night and morning (trunk keepalive?) (#608)De: Carlos Cruz Luengo Para: irontec/ivozprovider CC: EA8DAM ,Mention Hi @amvidalrc,
Carriers / PeeringContracts handling is done via LCR kamailio module.
This module activates SIP OPTIONS pinging only when a carrier is inactivated due to failures (see inactivate_gw() and ping_* modparams).
There is no way to send SIP OPTIONS when carriers are OK and I don't see why this should be necessary. It would generate a lot of unneeded SIP traffic.
You can send periodic REGISTERs though, that may work for you 🤔
Regards,

**Comment by cruzccl** [comment]
Hi @amvidalrc,

You can read it in the official documentation ([english](https://irontec.github.io/ivozprovider/en/artemis/brand/peering/ddi_provider_registrations.html), [spanish](https://irontec.github.io/ivozprovider/es/artemis/brand/peering/ddi_provider_registrations.html)).

Regards,

**Comment by amvidalrc** [comment]
Thanks so much! I will look there.

**Comment by amvidalrc** [comment]
I was looking there and I dont have any configuration. That is because my provider does not need registration... So, I'm blocked again. I'm going to open an incident to the carrier to see if they have any kind of timer.

**Comment by cruzccl** [comment]
Hi @amvidalrc,

Yes, you will have to ask your carrier. Needing a periodic keepalive is not common nor necessary, as both sides have static public IP so no connection needs to be refreshed anyhow.

Regards,
