### ISSUE TITLE
Change default currency globally

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#636]
Hello,

After installing from standalone install cd, default currency is "Euro".  I cannot find anywhere in the GUI to change default currency to "Dollar".  I am not referring to multi-currency, but global references to the Euro symbol and word.

I tried oasis and artemis distributions.

**Comment by Kaian** [comment]
Hi @powerpbx 

Currently there is no setting to change the default platform currency. All the euro symbols are hardcoded strings in the administration portal (afaik none of the database fields have unit), so you just update where that symbols are displayed.

A quick search using `git grep €` in the project:
```
library/Ivoz/Provider/Domain/Service/Invoice/EmailSender.php:            '${INVOICE_CURRENCY}' => '€'
web/admin/application/configs/klear/model/BalanceMovements.yaml:      sufix: "€"
web/admin/application/configs/klear/model/BalanceMovements.yaml:      sufix: "€"
web/admin/application/configs/klear/model/BalanceNotifications.yaml:      sufix: "€"
web/admin/application/configs/klear/model/DestinationRates.yaml:      sufix: "€"
web/admin/application/configs/klear/model/DestinationRates.yaml:      sufix: "€"
web/admin/application/configs/klear/model/FixedCosts.yaml:      sufix: "€"
web/admin/application/configs/klear/model/FixedCostsRelInvoiceSchedulers.yaml:            template: '%name% - %cost% €'
web/admin/application/configs/klear/model/FixedCostsRelInvoices.yaml:            template: '%name% - %cost% €'
web/admin/application/configs/klear/model/Invoices.yaml:      sufix: "€"
web/admin/application/configs/klear/model/Invoices.yaml:      sufix: "€"
web/admin/application/configs/klear/model/Invoices.yaml:              pattern: "%name% - %cost% €"
web/admin/application/controllers/KlearCustomIncrementBalanceController.php:            . ' €'
```

Take into account that this files may be overwritten during an upgrade as they are not handled as configuration files in debian packages!

Default Invoice Templates also uses Euro, but you can easily edit their contents after importing them in the Invoice Templates section.

There is an issue to support multicurrency in #530 but that task is not even scheduled, so I'm not sure whenever it will be done (or if it will be done at all).

Regards!!
