### ISSUE TITLE
Replace MySQL v5.7 with MariaDB v10

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#637]
Besides being Debian 9 default, MariaDB v10 has built in clustering.   I can probably change it manually without too much trouble but it would be nice if the project standardized on it.

**Comment by Kaian** [comment]
Hi @powerpbx 

During the initial analysis of 2.x branch we decided that migration from 1.x should be possible, so we've done data migrations and software choices keeping that in mind.

My initial intention during 2.0 was to use as many debian packages as possible but we found some problems integrating mariadb with the rest of the components (asterisk with odbc, kamalio, doctrine migrations). That was a year ago, so I can not recall exactly the encountered problems. 

Back then migrating from 5.5 to 5.7 could be done without much trouble, but a lot of things have changed and maybe now is also possible to use mariadb with little changes. 

Our plans right now is to keep mysql for 2.x and give it a try again to mariadb in a future 3.x release under buster, but feel free to give it a try. 

If anything works we could try to add support for both dbs.


Regards!

**Comment by scoobydoowru** [comment]
Thank you for the info.  Is clustering using existing features in MySQL v5.7 adequate for this application?

**Comment by powerpbx** [comment]
Thank you for the info. Since most installs that are not standalone would need to cluster the DB, what is the recommended way of doing that with MySQL v5.7?

**Comment by Kaian** [comment]
In most scenarios it's just enough with a master-master replication with a virtual balanced ip.

That's what we used in latest stress tests as we mentioned in #553. Read access are most of the time cache hits while write access is limited to CDRs (for both Kamailio and CGRateS)

Regards!

**Comment by powerpbx** [comment]
I could be wrong but I am not aware of any way to get datacenter redundancy with a virtual balanced IP.  AWS has elastic IP that is datacenter redundant but then you have to put it behind NAT which makes everything with SIP more complicated.  

I think even over LAN, standard MySQL master-master has a tendency to get split brain.  MySQL 10, on the other hand, can be done over WAN and avoids split brain as long as you use an odd number with 3 minimum.

Am also wondering about redis now that you are using cgrates.  In order to make cgrates redundant I believe I would need to make the redis db redundant.
