### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#638]
Is there any documentation for the API?   If not, can I determine features from the code somewhere?

**Comment by manfer** [comment]
On v1.x oasis check https://github.com/irontec/ivozprovider/issues/220

On v2.x artemis check https://github.com/irontec/ivozprovider/issues/468

**Comment by powerpbx** [comment]
That works for now.  Thanks.

**Comment by powerpbx** [comment]
Found it in /library/CoreBundle/Resources/config/parameters.yml
