### ISSUE TITLE
web/admin: change downloaded recording filename

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#659]
Currently their name is formed using the call-id, but it would be nice if some information could be deduced from the filename.

Proposal:

20180820111934_onDemand-109_202_109.mp3 (datetime_type-recorder_source_destination.mp3)

All this information is retrieved from Recordings table entry, no search is done on other tables.

**Comment by Kaian** [comment]
I think storing the Call-Id hashid in the ID3 mp3 comment field could be a good idea in order not to miss any information.

This could be easily done by adding an extra lame command line argument.

2cents
