### ISSUE TITLE
oasis irontec debian packages

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#674]
Ivozprovider includes several packages: ivozprovider-asterisk-agi, ivozprovider-asterisk-config, ivozprovider-data-library, ..., ivozprovider-kamailio-trunks, ...

Each time a change on code is made, if I'm perceiving it correctly, no matter how minimal it is, all packages become outdated even when the change is only for one of those packages. Couldn't this be enhanced?

As an example there has been today a change on kamailio trunks configuration file. Ideally that should just affect ivozprovider-kamailio-trunks package but if we upgrade the system all packages are downloaded and they are updated.

Not sure if bleeding works the same and I don't know how difficult it is to implement a different behaviour. If posible, it would be resources saving on target machines and bandwidth saving on your repository servers.

Or maybe you can just renew the packages on your public repository servers when you add a new tag instead of on each change.

**Comment by Kaian** [comment]
As far as I know, all packages defined in [debian/control](https://github.com/irontec/ivozprovider/blob/bleeding/debian/control) file are built when using dpkg build tools (pbuilder, cowbilder, dpkg-buildpackage, and so on). Splitting the control file into small parts and implementing a logic to detect what packages are involved in each commit doesn't seem like an easy task.

All packages and releases are built in the same way in our jenkins server using [jenkins-debian-glue](https://jenkins-debian-glue.org/).

The only change I have in mind is to split repositories so each release has a base repository (where tagged versions are published) and an updates repository (when every commit generates a package). This will allow upgrading between minor versions without receive each patch package.

Regards!

**Comment by manfer** [comment]
Hi @Kaian 

I supposed when not done were because it was not an easy task. Thanks for the explanation. Makes sense to me now.

Nice you consider having a separate repository.

Thanks.
