### ISSUE TITLE
ivr option on screen

### ISSUE THREAD

**Issue by miquelinv** [irontec/ivozprovider#717]
is it possible that when a client selects an option from an ivr, in the terminal the name of this ivr option appears as the caller in addition to the ddi?

it would be very useful if that extension is the destination of several ivr options, for example, an ivr that allows the language selection to the user would allow him to respond with that language since the ivr option of that language would appear on the screen.

**Comment by cruzccl** [comment]
Duplicate #187?

Regards,

**Comment by miquelinv** [comment]
ok, I had not searched it correctly.

I have been reviewing the post that you indicate, I understand that in DisplayName you have to introduce some regular expression, since it instead substitutes the ddi for the text.
