### ISSUE TITLE
Agi - Dial application g option duplicate on hunt groups

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#719]
On HuntGroupCallAction the g option is adeed
https://github.com/irontec/ivozprovider/blob/cfdac6e97a0c2330a3f75803eac7515739cc11a7/asterisk/agi/src/Agi/Action/HuntGroupCallAction.php#L60-L61

but the default dialplan already adds it
https://github.com/irontec/ivozprovider/blob/cfdac6e97a0c2330a3f75803eac7515739cc11a7/asterisk/config/dialplan/default.conf#L68

Most probable it is ignored by dial application but maybe would be better to remove the option in one place or the other.

**Comment by Kaian** [comment]
It seems the other dialplan lines include some forced options (ivr, world, etc),  so I think the easiest would be to remove it from the agi and leave it in the dialplan. 

Are you willing to PR this change?

Thanks @manfer!
