### ISSUE TITLE
PHP AGI ERRORS

### ISSUE THREAD

**Issue by TayyabTalha** [irontec/ivozprovider#725]
Hi I am running debin iso and I got following error when I set agi set debug on. I'm trying to call 101 demo extension from bob.

> <PJSIP/b1c1t2_bob-00000009>AGI
>  Rx << PHP Notice:  Undefined index: PATH in /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi.php on line 1646
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP Stack trace:
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP   1. {main}() /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi-fastagi.php:0
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP   2. AGI->AGI() /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi-fastagi.php:33
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP   3. AGI->which() /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi.php:159
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP Notice:  Undefined index: PATH in /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi.php on line 1646
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP Stack trace:
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP   1. {main}() /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi-fastagi.php:0
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP   2. AGI->AGI() /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi-fastagi.php:33
> <PJSIP/b1c1t2_bob-00000009>AGI Tx >> 510 Invalid or unknown command
> <PJSIP/b1c1t2_bob-00000009>AGI Rx << PHP   3. AGI->which() /opt/irontec/ivozprovider/asterisk/agi/application/bin/lib/phpagi/phpagi.php:162
> AGI Rx << temp buffer Command Line Only! - errno Resource temporarily unavailable
> No \n received, checking again.
> AGI Rx << temp buffer Command Line Only! - errno Resource temporarily unavailable
> No \n received, checking again.
> AGI Rx << temp buffer Command Line Only! - errno Resource temporarily unavailable
> No \n received, checking again.
> AGI Rx << temp buffer Command Line Only! - errno Resource temporarily unavailable
> No \n received, checking again.
> AGI Rx << temp buffer Command Line Only! - errno Resource temporarily unavailable
>

**Comment by Kaian** [comment]
Hi @TayyabTalha 

What version did you installed? From the error it looks like php variables_order is not configured and crashes while accessing environment PATH variable.

That setting should be automatically configured in postinstall script https://github.com/irontec/ivozprovider/blob/oasis/debian/ivozprovider-asterisk-agi.postinst or https://github.com/irontec/ivozprovider/blob/artemis/debian/ivozprovider-asterisk-agi.postinst 


Regards!

**Comment by TayyabTalha** [comment]
@Kaian I was using stable (oasis 1.7) iso. Cli PHP was php 7.2 I also try to set php 5.6 but now I installed testing (artemis 2.7.1) and it is working.
Thank you for your reply.
Regards.

**Comment by TayyabTalha** [comment]
Yep I update add debian repo and then run update it by running apt update.

**Comment by Kaian** [comment]
As far as  I know that php version is not available under debian jessie (oasis) or debian strertch (artemis). Our software releases will only work with their tested debian releases. If you choose to update, be sure you are using the appropiate debian repository release (ie, don't use buster or sid), otherwise everything may be broken.

I'm closing this as the problem  doesn't seem to be related to the iso or our debian packages.

Thank you for the testing!
Regards
