### ISSUE TITLE
web/admin: show Invoices at client level

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#732]
Read-only section, only adds visibility to already generated invoices and enables downloading PDF file.

Subtasks:
- [x] Create new section at client level under Calls subgroup.
- [x] New Company fields: can see Invoices (Yes/No)
- [x] Show new Invoices section only if previous toggle is 'Yes'.
- [ ] Update documentation accordingly.

**Comment by manfer** [comment]
It would be great to have a checkbox unchecked by default as a configurable option for invoices. If that checkbox is checked the invoices would be available at client level and if it is unchecked it will not.

This will allow to show some invoices to clients and not just show all -invoicing enabled- or show none -invoicing disabled-. If I understood it correctly.

I'm thinking about having the chance to generate an invoice and review it before showing it to the client.

**Comment by cruzccl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [web/admin: show Invoices at client level #732](https://trello.com/c/9Fy5BsB3/6-web-admin-show-invoices-at-client-level-732)
