### ISSUE TITLE
What happened with v2.6?

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#746]
We were using v2.6 artemis but it appears artemis is now v2.7.  Would it not make more sense if you had created a new branch and name for that?  We were doing some development with v2.6 and this version number change is making it a little more difficult for us for various reasons.

**Comment by Kaian** [comment]
Hi @powerpbx 

In our development flow each branch represents a major release. For instance, oasis represent 1.x versions while artemis represents 2.x versions. Bleeding is where we test each feature before adding it to artemis.

For us, a minor or patch release is just a Milestone in or branch. The branch will continue its life until the major release ends its life and only receives security fixes.

Every time we reach one of those milestone we decide the next one for the branch (maybe 2.6.1 or 2.7) and we start working on that in bleeding. 

You have each milestone marked with a tag, so you can still developing when artemis reached 2.6.0 but you will be missing the latest changes and features.

Regards!

**Comment by powerpbx** [comment]
Maybe there is a better way for us to do it but it kind of messed us up. We need to create our own repository for various reasons.  We also need to pull from the ivoz repository for dependencies.  We created a version number of 2.6 so that it would always be seen as the latest for those packages.  Then whey you guys switched to version 2.7 that was the version the server was trying to update to instead of our custom v2.6.
