### ISSUE TITLE
debian packaging rules file

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#747]
https://github.com/irontec/ivozprovider/blob/4e319bcfd35827aa1184db859264d75b690b4282/debian/rules#L63-L64

Is the second line correct or is it a typo?

```
	dh_systemd_enable -p ivozprovider-cdrs       --name=ivozprovider-cdrs               --no-enable
```

If it is a typo, then same in here:

https://github.com/irontec/ivozprovider/blob/4e319bcfd35827aa1184db859264d75b690b4282/debian/rules#L72-L73

**Comment by Kaian** [comment]
Hi @manfer 

Nope, that configuration is correct.

What is specified in those lines is that those two unit files (ivozprovider-scheduler.service and ivozprovider-cdrs.service) must be in a package called ivozprovider-scheduler. Package names are described in debian/control file.

Although not too common, in this case our package have multiple systemd services and timers :)

Thanks for reporting!

**Comment by manfer** [comment]
Hi @kaian,

Thanks for clarifying.

I'm trying to find why on bleeding packages update and if I run dpkg-reconfigure too I'm getting this error:
```
ERROR 1062 (23000) at line 1: Duplicate entry 'xxx.xxx.xxx.xxx' for key 'domain_unique'
```
where xxx.xxx.xxx.xxx is the IP where ivozprovider is installed. One IP standalone installation.

But I don't know debian packaging too much and it is being hard to find.

And when I look into database scheme -at least the initial scheme- domain_unique is a unique key of Companies table and there is no duplicate entry, no even any entry with xxx.xxx.xxx.xxx value in domain_users column. So I'm lost.

**Comment by Kaian** [comment]
Mos probably here:

https://github.com/irontec/ivozprovider/blob/bleeding/debian/ivozprovider.postinst#L75

This assumes you only have one company with a "domain IP trick" (see docs for info), and that IP is the Users proxy address.

Theorically that queries should not match any line or one if you are doing "the trick".

**Comment by manfer** [comment]
I have run into mysql console the query on this line,


https://github.com/irontec/ivozprovider/blob/4e319bcfd35827aa1184db859264d75b690b4282/debian/ivozprovider.postinst#L91


And is the one that generates the error. I would say that like is not correct because it does not just match an IP but any domain with three or more dots, like:

a.b.example.com
a.b.c.example.com
...

I would say the correct implementation is,

```
    # Update DemoCompany domain to USERS_ADDRESS
    /usr/bin/mysql --user=root ivozprovider -e "UPDATE Companies SET domain_users = '$USERS_ADDRESS' WHERE id = 1 AND domain_users REGEXP '^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$'";
```
the regular expression on the next line doesn't look correct either.
