### ISSUE TITLE
kamctlrc database name

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#758]
Not sure what is this file for. But shouldn't these lines

https://github.com/irontec/ivozprovider/blob/4554ad8a2685f21da546b07f1e584d474656fe5f/kamailio/trunks/config/kamctlrc#L25-L26

be

```
## database name (for ORACLE this is TNS name)
DBNAME=ivozprovider
```

**Comment by manfer** [comment]
I suppose this can be totally ignored as kamctl is disabled in favor of systemctl

https://github.com/irontec/ivozprovider/blob/4554ad8a2685f21da546b07f1e584d474656fe5f/profiles/proxy/root/.bashrc.d/500-proxy-system#L14-L15

**Comment by Kaian** [comment]
That's what I was also thinking,  but I leave it to @cruzccl

If the file ia not used and not required, it should be deleted IMO

**Comment by cruzccl** [comment]
Yes, it is not used and could be deleted.

kamctl is not used as kamcmd is used (systemctl to start/stop service).

Regards,
