### ISSUE TITLE
Database connection error show database root password publicly

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#766]
This happens when MySQL is not running for whatever reason.   You can reproduce by stopping MySQL `systemctl stop mysql`

The problem is that the error shown publicly on a web browser, when trying to access the GUI, shows the database root password.

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /opt/irontec/ivozprovider/library/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43 Stack trace: #0 /opt/irontec/ivozprovider/library/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=data...', 'root', 'secretpassword', Array) #1 /opt/irontec/ivozprovider/library/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(44): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=data...', 'root', 'secretpassword', Array) #2 /opt/irontec/ivozprovider/library/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'secretpassword', Array) #3 /opt/irontec/ivozprovider/library/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /opt/irontec/ivozprovider/library/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery(' in /opt/irontec/ivozprovider/library/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103`

**Comment by manfer** [comment]
Hi @powerpbx ,

Bleeding version is not production ready. If you put your mouse over the tab in your browser to see the full title of the webpage when you visit the ivozprovider web configuration console

> [Global Administration portal] :: 2018 :: ENV: development

you can see it is running in development environtment.

And you can see on development environtment display errors are turned on.
https://github.com/irontec/ivozprovider/blob/e5c437fcd2e4d440e6280ac4924b3a2ed68533f9/web/admin/application/configs/application.ini#L63-L66

I suppose when this version is production ready the environtment would be turned to production and then all those will be turned off
https://github.com/irontec/ivozprovider/blob/e5c437fcd2e4d440e6280ac4924b3a2ed68533f9/web/admin/application/configs/application.ini#L5-L6
https://github.com/irontec/ivozprovider/blob/e5c437fcd2e4d440e6280ac4924b3a2ed68533f9/web/admin/application/configs/application.ini#L18

Not sure if it is the exact correct way to do it but you will turn to production by editing
https://github.com/irontec/ivozprovider/blob/e5c437fcd2e4d440e6280ac4924b3a2ed68533f9/web/admin/public/zf.php#L23-L24
changing development to production.

I suppose the correct way is to define APPLICATION_ENV somewhere else.

Anyway. Take in mind that even if you change that value to stop errors from being displayed ivozprovider bleeding version is a development branch not production ready.

**Comment by powerpbx** [comment]
Thanks for clearing that up.  We are aware that it's not production ready.

**Comment by manfer** [comment]
> I suppose when this version is production ready the environtment would be turned to production by default and then all those will be turned off

Just for completion. I haven't explained it correctly.

Bleeding is going to be always a development branch. When current 2.x version features are ready, they are merged into artemis branch.

**Comment by powerpbx** [comment]
We are using artemis repository.  Installed as per artemis/v2.7 install guide.

https://irontec.github.io/ivozprovider/en/artemis/basic_concepts/installation/debian_install.html

**Comment by manfer** [comment]
Hi @powerpbx ,

Artemis is marked as testing. It is not production ready either. Eventually, in the future, it will be marked as stable and production ready.

Only oasis version is production ready. Here is the code in oasis branch,
https://github.com/irontec/ivozprovider/blob/9e047a6f53b8a214d5e2a5f9f8a44af1fd317a25/portals/public/index.php#L6-L8

Someone from irontec can probably clarify it better.

**Comment by Kaian** [comment]
Hi all!

As @manfer mentions this behaviour is ruled by APPLICATION_ENV variable.

Now that we have moved everything to symfony in artemis, we use SYNFONY_ENV that changes the behaviour of how applications work. We will keep APPLICATION_ENV because klear (our portal framework) is still a Zend Application, but the variable will be set to producion by default instead of development.

We usually define this variables in /etc/systemd/system.conf file, but can also be defined in apache site or even in .htaccess

Anyway this will be set to production in 2.8.0 as we now have different URLs for each profile.

Thanks for reporting!
