### ISSUE TITLE
artemis, Fatal error: Illegal or unknown default time zone in MySQL

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#772]
This is after a fresh install of standalone artemis on top of minimal install and updated Debian. That has previously worked so it must have been a recent change.

Following this guide corrected it. 

https://www.brucedev.com/posts/fatal-error-illegal-or-unknown-default-time-zone-in-mysql

The `default-time-zone = ` line causing the problem is in `/etc/mysql/conf.d/ivozprovider.cnf`

**Comment by powerpbx** [comment]
Scheme (schema) is not installed at all.  Probably because mysql is not running.

**Comment by Kaian** [comment]
Could you please attach the apt logs located in `/var/log/apt/term.log` and `/var/log/apt/history.log` ?

Thanks!

**Comment by powerpbx** [comment]
We figured it out.  We weren't entering a root password on the ivoz config screen `dpkg-reconfigure ivozprovider`, which is apparently mandatory.
