### ISSUE TITLE
Artemis, cannot configure ivozprovider-profile-proxy

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#774]
When doing `apt-get install ivozprovider-profile-proxy`, we cannot get past the configuration menu.  After we try enter `Configure Media Relay private address >> Finish configuration` data it keeps taking the install back to the menu instead of exiting the configuration menu and continuing on with the install.  

I am guessing it is a syntax error on that menu page where `Finish configuration` is not on it's own line like the other profiles have.

**Comment by Kaian** [comment]
Fixed in #781
