### ISSUE TITLE
Cannot start rtpengine

### ISSUE THREAD

**Issue by everywan-dev** [irontec/ivozprovider#775]
After IP change, rtpengine won't start (I don't know if start before, I need to change IP before test).

I need to replace manually IP on table kam_rtpengine, but don't start.

root@sip01.voip.everywan.net:~# /usr/sbin/rtpengine --table=0 --interface=${AUDIO_SOCK} --listen-ng=${CONTROL_SOCK} --listen-cli=127.0.0.1:9900 --xmlrpc-format=1 --b2b-url=http://users.ivozprovider.local:8000/RPC2 --tos=184 --pidfile=/var/run/rtpengine.pid --no-fallback --sip-source --recording-dir=${RECORDINGS_SPOOL} --recording-method=proc $EXTRA_OPTS
[1542321326.404808] ERR: FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
[1542321326.404841] CRIT: Userspace fallback disallowed - exiting

I executed dpkg-reconfigure  ivozprovider-rtpengine but I got an error because kernel-headers werent installed, I installed but no success,..

I see that installed a kernel moduled, but this don't appair on lsmod,

root@sip01.voip.everywan.net:~# lsmod|grep xt_RTPENGINE

Have any similar case?

**Comment by everywan-dev** [comment]
reboot after dpkg-reconfigure solves the problem. 

Must to execute this query too:
UPDATE kam_rtpengine SET url='udp:127.0.0.1:22223';

Now seems to be ok.

**Comment by Kaian** [comment]
You can update that table from the Media Relays section un the portal. 

About the ip change, not sure where the problem is. The dpkg-reconfigure should update /etc/default/rtpengine with the new address 

Regards!!
