### ISSUE TITLE
Artemis, Kamailio not enabled and started on distributed install proxy profile

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#778]
For standalone install `apt-get install ivozprovider` , kamailio users and trunks are enabled and started.  

This appears to be inconsistent with distributed install `apt-get install ivozprovider-profile-proxy`, where kamailio users and trunks are not enabled and started. 

The relevant lines on standalone install start [in standalone postinstall enable services](https://github.com/irontec/ivozprovider/blob/2d30fb6ca103641f693bec42f1e3e034cee3753e/debian/ivozprovider.postinst#L153) and [in standalone postinstall start services](https://github.com/irontec/ivozprovider/blob/2d30fb6ca103641f693bec42f1e3e034cee3753e/debian/ivozprovider.postinst#L137)

Would it make sense to add the relevant parts   [into proxy profile postinstall](https://github.com/irontec/ivozprovider/blob/artemis/debian/ivozprovider-profile-proxy.postinst) to make it more consistent with standalone install?  Unless this is by design so it is just a media proxy by default.

**Comment by Kaian** [comment]
Hi @powerpbx 

This is the intended behaviour. Distributed setup assume there are some clustering software between the nodes so each service and systemd timer is active just once. The same applies to virtual ips for services and so on.

All these process are not trivial at all and will documented in #271 whenever we have time or someone is interested in priorize that issue in our schedule.

Thanks and regards!!
