### ISSUE TITLE
agi question

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#796]
I'm reading the code and I came into something that I don't understand. I see how it works but I don't understand it.

In some of the agi php files when setting variables value, the variable name is prepended by one or even two underscores,

```
$this->agi->setVariable("_FOO", "thevalue");
```

but later when retrieving the value the variable name is used without underscores. I have even made a test with a variable and the getter does not work if I use the variable with the underscore.

```
$this->agi->getVariable("FOO"); // works
$this->agi->getVariable("_FOO"); // not working
```

What I'm missing?

**Comment by Kaian** [comment]
The underscores prefix of the variable it's not used to determine its name, buts its inheritance level.
The variable is called FOO and should be retrieved with that name.

See https://wiki.asterisk.org/wiki/display/AST/Variable+Inheritance for further details.
