### ISSUE TITLE
installer depandancy bug on debian 9.6 (standalone)

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#809]
When installing on debian 9.6 (default in GCE and AWS) the installer has mysql-server as a depandancy, but this installs mariadb 10. 

either the installer needs to call mysql_secure_server to set up authentication and various other mysql>mariadb porting issues, or the installer needs to check debian version and install mysql-community-server instead.

**Comment by Kaian** [comment]
Unable to reproduce.

Feel free to reopen with requested configuration.

Regards!
