### ISSUE TITLE
Instalacion artemis 2.8.0

### ISSUE THREAD

**Issue by didacfernandez** [irontec/ivozprovider#813]
Buenos días, 
Tras hablar con vuestros compañero Jon hemos instalado artemis 2.8.0 en una mv y tengo los siguientes errores:

1. Al acceder vía web, (admin/changeme) la pantalla se queda bloqueada y no hace nada. Se ha hecho un reboot pero ocurre lo mismo.

root@ivozprovider-standalone:~# cat /var/log/apache2/error.log
[Mon Dec 03 13:38:04.892400 2018] [ssl:warn] [pid 706] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Mon Dec 03 13:38:04.970694 2018] [ssl:warn] [pid 729] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Mon Dec 03 13:38:04.970798 2018] [http2:warn] [pid 729] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Mon Dec 03 13:38:07.857592 2018] [mpm_prefork:notice] [pid 729] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Dec 03 13:38:07.874612 2018] [core:notice] [pid 729] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 03 13:45:09.038338 2018] [core:notice] [pid 729] AH00052: child pid 817 exit signal Segmentation fault (11)
[Mon Dec 03 13:45:12.421415 2018] [core:notice] [pid 729] AH00052: child pid 818 exit signal Segmentation fault (11)
[Mon Dec 03 13:45:12.421461 2018] [core:notice] [pid 729] AH00052: child pid 819 exit signal Segmentation fault (11)
[Mon Dec 03 13:45:12.421490 2018] [core:notice] [pid 729] AH00052: child pid 820 exit signal Segmentation fault (11)
[Mon Dec 03 13:45:12.421604 2018] [mpm_prefork:notice] [pid 729] AH00169: caught SIGTERM, shutting down
[Mon Dec 03 13:45:41.652615 2018] [ssl:warn] [pid 664] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Mon Dec 03 13:45:41.679316 2018] [ssl:warn] [pid 720] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Mon Dec 03 13:45:41.679410 2018] [http2:warn] [pid 720] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Mon Dec 03 13:45:44.699089 2018] [mpm_prefork:notice] [pid 720] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Dec 03 13:45:44.699158 2018] [core:notice] [pid 720] AH00094: Command line: '/usr/sbin/apache2'

2. Por otro lado Jon nos comentó que el sistema era plug and play y no hacía falta configurar nada en los ficheros de kamailio para que funcionara:

root@ivozprovider-standalone:~# kamailio
ERROR: bad config file (47 errors)

root@ivozprovider-standalone:~# kamtail-proxyusers
-- Logs begin at Mon 2018-12-03 13:45:36 CET. --
[dic 03 13:45:53] <core> [core/cfg/cfg_ctx.c:595]: cfg_set_now(): tls.low_mem_threshold1 has been changed to 16252928
[dic 03 13:45:53] <core> [core/cfg/cfg_ctx.c:595]: cfg_set_now(): tls.low_mem_threshold2 has been changed to 8126464
[dic 03 13:45:53] <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
[dic 03 13:45:53] <core> [core/udp_server.c:205]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
[dic 03 13:45:53] <core> [core/udp_server.c:395]: udp_init(): bind(b, 0x7f066fb7dc2c, 16) on 54.37.187.114: Cannot assign requested address
[dic 03 13:45:53] <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
dic 03 13:45:53 systemd[1]: kamailio@users.service: Control process exited, code=exited status=255
dic 03 13:45:53 systemd[1]: Failed to start Kamailio - the Open Source SIP Server.
dic 03 13:45:53 systemd[1]: kamailio@users.service: Unit entered failed state.
dic 03 13:45:53 systemd[1]: kamailio@users.service: Failed with result 'exit-code'.

Anteriormente se instaló la versión estable y tambien tuvimos problemas con Kamailio, tras hablar ocn Jon nos recomendó esta versión que está mas depurada.

¿Podeis ayudarnos?

Gracias

**Comment by Kaian** [comment]
Hi @didacfernandez 

The standard language in github issues is english. This way the response can be helpful to most people. If you have trouble reading or writting english, feel free to use a translator, or in last stance, to use our native language (spanish).

Regarding your questions:

1.- I don't see anything strange in those logs. Try logging in while running _journalctl -f_ from a shell. It could be related with JWT tokens.

2.- kamailio binaries can only be starting by using systemd units (pe. _systemctl start kamailio@users_). According to the logs you have configured _user.ivozprovider.local_ address to some ip not present in any interface so kamailio can not bind to it (_Cannot assign requested address_)

You have mentioned the stable version. If you mean Ivozprovider oasis 1.X release, it is far more stable than 2.X which still is under testing and development although lacks lots of features available in newest versions. 

Regards

**Comment by Kaian** [comment]
Hi @didacfernandez 

The error displayed in that logs (CGRateS <93e3a90> [20208]: error: dial tcp 127.0.0.1:8448: getsockopt: connection refused!) is most probably caused because your *kamailio@trunks* service is stopped. CGRateS connects to *kamailio@trunks* on startup.

Ensure kamailio@trunks is running (_systemctl status kamailio@trunks_). Take into account we use two different kamailio process, one for users and one for trunks. As mentioned in the previous note, your kamailio@users bind address was not properly configured, so maybe your trunks.ivozprovider.local address has the same problem.

Regards!

**Comment by didacfernandez** [comment]
Hello @Kaian, 
Can you confirm what are the files to change please?
Regards

**Comment by Kaian** [comment]
HI @didacfernandez 

For a standalone installation, all configuration can be done from installation menu:

```
dpkg-reconfigure ivozprovider
```
This will setup all required files with entered data (addresses, passwords and so on).

For the problem with Kamailios described in second point: Are you using public IP address for users and trunks proxies? Is that address configured in any of your network interfaces?

Regards

**Comment by didacfernandez** [comment]
Hi @Kaian,

I have configured the private ip addrees in Kamailio, now users is running but trunk I have the same problem.
By other side, I can't access via web, the web is frozzen when I press Login. User and password are ok.

```
root@ivozprovider-standalone:~# cat /var/log/apache2/error.log
[Thu Dec 13 06:25:03.199824 2018] [ssl:warn] [pid 720] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Thu Dec 13 06:25:03.200805 2018] [http2:warn] [pid 720] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Thu Dec 13 06:25:03.255514 2018] [mpm_prefork:notice] [pid 720] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Thu Dec 13 06:25:03.255537 2018] [core:notice] [pid 720] AH00094: Command line: '/usr/sbin/apache2'
[Thu Dec 13 08:41:04.672407 2018] [mpm_prefork:notice] [pid 720] AH00169: caught SIGTERM, shutting down
[Thu Dec 13 08:41:32.230058 2018] [ssl:warn] [pid 670] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Thu Dec 13 08:41:32.699192 2018] [ssl:warn] [pid 823] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
[Thu Dec 13 08:41:32.705467 2018] [http2:warn] [pid 823] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Thu Dec 13 08:41:34.861771 2018] [mpm_prefork:notice] [pid 823] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Thu Dec 13 08:41:34.861844 2018] [core:notice] [pid 823] AH00094: Command line: '/usr/sbin/apache2'
```
Regards

**Comment by Kaian** [comment]
Hi @didacfernandez 

Ivozprovider proxies require public IP addresses for proxies in order to work properly. You can however use the same IP for both proxies. The address must be also configured in one of your interfaces as we mentioned before. Check docs  about minimum requirements for more info. 

For the portals issue: Does the login popup disappear after you enter credentials or it  keeps on screen with all fields locked?

Regards

**Comment by didacfernandez** [comment]
Hi @Kaian.

The popup is blocked in grey.

![popup](https://user-images.githubusercontent.com/45563255/50151528-72d4c080-02c1-11e9-8d4d-e4271d294116.jpg)

Regards

**Comment by Kaian** [comment]
That seems a problem retrieving internal API token.

When you login, the portal access the API using the same URL you entered in your browser. Is able the ivozprovider machine to resolve or access the portal url? You can check from the shell using curl or wget.

Regards!

**Comment by didacfernandez** [comment]
Hello @Kaian ,

The URL is the public ip.

```

> root@ivozprovider-standalone:~# wget 54.37.187.114
> --2018-12-20 15:14:32--  http://54.37.187.114/
> Conectando con 54.37.187.114:80... conectado.
> Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
> Localización: https://54.37.187.114/ [siguiendo]
> --2018-12-20 15:14:32--  https://54.37.187.114/
> Conectando con 54.37.187.114:443... conectado.
> ERROR: El certificado de “54.37.187.114” no es confiable.
> ERROR: El certificado de “54.37.187.114” no tiene un emisor conocido.
> El propietario del certificado no se ajusta al nombre de equipo “54.37.187.114”

```

I have used the Console of Firefox and show this:

```

> message: "Error Indefinido"
> ​
> raw: "<h2>Internal Server Error</h2><p>Please contact the server administrator.</p><p>More information about this error may be availabe in the server syslog.</p>"

```

```

> cat /var/log/apache2/error.log
> [Thu Dec 20 06:25:03.214571 2018] [ssl:warn] [pid 715] AH01909: 172.26.77.100:443:0 server certificate does NOT include an ID which matches the server name
> [Thu Dec 20 06:25:03.214659 2018] [http2:warn] [pid 715] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
> [Thu Dec 20 06:25:03.244564 2018] [mpm_prefork:notice] [pid 715] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
> [Thu Dec 20 06:25:03.244589 2018] [core:notice] [pid 715] AH00094: Command line: '/usr/sbin/apache2'

```
Regards

**Comment by Kaian** [comment]
Hi @didacfernandez 

Can you check if 54.37.187.114 is in the output of ```ip addr show``` command?

Regards

**Comment by Kaian** [comment]
Hi @didacfernandez 

Could you provide the requested info? We would like to confirm if this problem is environment dependent or a software bug.

Regards.
