### ISSUE TITLE
outbound prefix

### ISSUE THREAD

**Issue by cyberprosconsulting** [irontec/ivozprovider#832]
i'm trying to configure anveodirect in artemis. oasis used to have an outbound prefix area i do not see it anymore in artemis so i'm not able to route calls through to anveodirect as it needs a dialing prefix. please advise.

i tried using destination prefix in outgoing routing but that does not work.

**Comment by Kaian** [comment]
Hi @cyberprosconsulting 

You could try creating a [Numeric transformation](https://irontec.github.io/ivozprovider/es/artemis/administration_portal/brand/settings/numeric_transformations.html) for the country you're using filling the trunk prefix with the outgoing prefix. Then assign the new transformation to the users (or companies) you want to use that prefix.

Trunk prefix are some extra digits used in non-internacional calls, and are stripped before adding the country code to standarize to E.164

Regards!

**Comment by cyberprosconsulting** [comment]
yes that could work problem would be i'd have to do that for every account as the prefix will be different for each

**Comment by Kaian** [comment]
If account means retail account, you can use [Routing tags](https://irontec.github.io/ivozprovider/en/artemis/administration_portal/brand/routing/routing_tags.html) to create multiple prefix and assign them to Retail clients. They are also stripped from the number before standarization

Regards

**Comment by cyberprosconsulting** [comment]
tried numeric transformation and still it's trying to dial witout the prefix. i told the pbx client to use the new expression even told the user to use the new expression and still no difference

**Comment by cyberprosconsulting** [comment]
watching asterisk cli and i'm not even seeing where it has the 6 prefix numbers it's still only showing +1 anywhere the dialed phone number is showing

**Comment by Kaian** [comment]
Dialed numbers are changed to E.164 standard in both proxies, so now asterisk use a single format for all incoming and outgoing numbers in all SIP headers.

**Comment by cyberprosconsulting** [comment]
ok well i'm still not about to make an outbound call. i'm at a loss on what to do

**Comment by Kaian** [comment]
Can you provide some more detailed information like:

- Dialed number by the user (including the prefix)
- Received number in Users proxy (user -> kamailio)
- Received number in Application Server (kamailio -> asterisk)
- Sent number by Trunks proxy (kamailio -> carrier)

Regards!

**Comment by cyberprosconsulting** [comment]
how would i get that information for you? i only know how to bring up the asterisk cli

**Comment by Kaian** [comment]
Use a network capture tool like  tcpdump, ngrep or sngrep and check the SIP uri of invite request sent between the services. 

Outbound prefix is gone, but you should be able to replace its functionalities with the above features. 

Regards

**Comment by Kaian** [comment]
Hi @cyberprosconsulting 

If all this time you're referring to Carriers outbound-prefix instead of Users outbound-prefix, then I have misunderstood it from the beginning.

According to my teammates, like the users one, Carriers outbound-prefix has been replaced with Numeric transformations as I mentioned in the first note, so you can either use trunk prefix or create your own transformation regexp.

Regards!

**Comment by powerpbx** [comment]
> how would i get that information for you? i only know how to bring up the asterisk cli

sngrep is the tool you want.  
https://github.com/irontec/sngrep

**Comment by Kaian** [comment]
To sum up: Outbound Prefix logic (for both Users and Carriers) has been removed in favor of Transformation rule sets.

If you require more information, feel free to reopen the issue.

Regards!!
