### ISSUE TITLE
MOH folders not created

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#836]
It appears that we need to manually create the two MOH folders before we can successfully upload MOH files.
```
/opt/irontec/ivozprovider/storage/ivozprovider_model_musiconhold.encodedfile
/opt/irontec/ivozprovider/storage/ivozprovider_model_musiconhold.originalfile
```

**Comment by Kaian** [comment]
This have been closed by mistake or did you find where the problem was?

Storage path resolvers code should create the full directory tree in storage before saving files. 

Regards

**Comment by Kaian** [comment]
Distributed should use a shared storage mounted under /opt/irontec/ivozprovider/storage 
You can use glusterfs or any other distributed filesystem, be sure to chmod 777 the directory after mounting.

Regards!

**Comment by powerpbx** [comment]
I think it is because the `/script` folder was missing on a distributed install.  Need to determine why.
