### ISSUE TITLE
February 1st: Mailing Lists shutdown

### ISSUE THREAD

**Issue by Kaian** [irontec/ivozprovider#854]
Starting on February 1st, ivozprovider mailing lists will be disabled.
This will affect all members subscribed to following lists:

 * dev@lists-ivozprovider.irontec.com
 * users@list-ivozprovider.irontec.com

We consider GitHub issues a better way to share information and report bugs,
with support for templates, text formatting, topic tags, and so on.

https://github.com/irontec/ivozprovider/issues

After shutdown, no archive or mailing info will be kept from the list. If you
want to unsubscribe before, use following links:

http://lists-ivozprovider.irontec.com/cgi-bin/mailman/options/users
http://lists-ivozprovider.irontec.com/cgi-bin/mailman/options/dev

Thanks in advance to everyone who subcribed to the list. We hope to see you
around GitHub!

Regards

IvozProvider Team

**Comment by powerpbx** [comment]
A google groups forum would be nice.

**Comment by Kaian** [comment]
Currently there is little traffic, so questions and feedback can still be posted in github.
If there is a lot those issues in the future, we'll consider using a forum or another community interaction method.

For now, we think it's better to focus our attention to a single place.
