### ISSUE TITLE
friends: Allow different outgoing DDIs

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#86]
Friends were designed in order to allow:

- Making calls from IvozProvider to users of an external PBX.

- Making calls from that external PBX to IvozProvider users.

But we also provided another implicit feature: **allow external PBX users to make external calls using IvozProvider**. That's why they have:

- Outgoing DDI.
- Call ACLs.

As behind an external PBX they might be multiple users, it would be nice to allow them call with different outgoing DDIs.

Proposal:

- Convert Outgoing DDI to "Default Outgoing DDI".
- Add a new selector: "Respect presented CLID" enable/disable.

If the presented CLID matches one of the Companies DDI, IvozProvider will respect this CLID. If not, IvozProvider will use the Default Outgoing DDI.

**Note:** adding DDIs to a Company in order to use them as a valid Outgoing DDI (for a friend or a user) will lead to malfunction. **IvozProvider DDIs MUST enter IvozProvider**, there no "Outgoing DDIs" section.

**Comment by Kaian** [comment]
> Proposal:
>
> Convert Outgoing DDI to "Default Outgoing DDI".
> Add a new selector: "Respect presented CLID" enable/disable.

What about changing the label a "Fallback Outgoing DDI" adding a help text that explains: "This DDI will be used if friend presented DDI doesn't match any of the company DDIs".

Do we want to allow presenting a DDI that doesn't belong to the company (if the select is enabled)?
