### ISSUE TITLE
Remove references to multiple proxies in documentation

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#864]
The documentation implies multiple proxies are possible.  For example, the images in the README on the front page of the github repo.  It would have saved us a lot of time if it didn't

![horizontalscaling](https://user-images.githubusercontent.com/16518476/51396879-dc303500-1af4-11e9-9b5e-a026b5b86b24.png)

Showing more than 2 data blocks is also somewhat misleading.  That cannot be done out of the box.

**Comment by cruzccl** [comment]
Hi @powerpbx,

The image you refer is accompanied by a sentence that explains that _"there can be multiple machines of each profile"_. This does not imply that all these machines' software is running concurrently nor that all of them are capable of horizontal scaling. This idea is also explained in the [official documentation](https://irontec.github.io/ivozprovider/en/artemis/basic_concepts/installation/install_types.html#distributed-install).

In fact, we do have production environments with 6 proxy machines distributed over several datacenters managed by a cluster software that guarantees that all the services provided by the profile are running somewhere. If a datacenter goes down, the cluster will migrate services to remaining available machines.

Sorry but we cannot agree with this issue's goal and we are going to close it to focus on really active ones.

Thank you and regards,

**Comment by cruzccl** [comment]
Sorry but such distributed environments depend on cluster software out of the scope of IvozProvider project itself. You can contact comercial@irontec.com to get professional support about these topics.

Regards,

**Comment by powerpbx** [comment]
We are asking how you do it within the contraints of the software.  For example, you have no way of adding muliple proxies in the GUI.   Also, how would a SIP UAC failover from Proxy A with one IP and Proxy B with another IP.  Unless you are using Anycast.

**Comment by cruzccl** [comment]
Hi @powerpbx,

Talking about Kamailio, we only have one running process at a time (one for KamUsers, one for KamTrunks, I mean) listening to a virtual IP address managed by a clustering software that guarantees that the process is started in the same machine that the virtual IP address is configured.

This way we only configure one proxy in UACs and in carriers.

This is the way we currently do it, not the better way nor the way it should be done, it's just ours.

Regards,
