### ISSUE TITLE
DID billing

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#870]
What are your plans for inbound (DID) billing?  Looks like maybe there was something at one time and then it was taken out.

**Comment by powerpbx** [comment]
bump

**Comment by cruzccl** [comment]
Hi @powerpbx,

Inbound DDI billing was developed in Oasis only for externally rater module, that is not included in IvozProvider as it doesn't use internal billing engine.

We don't know if we will develop inbound DDI billing with CGRateS internal billing engine in Artemis as no client has shown any interest to have this developed.

As always, if it is important for you and you want to sponsor the development, you can contact comercial@irontec.com and we will be glad to evolve IvozProvider with this feature.

Regards,

**Comment by powerpbx** [comment]
How do you guys plan to deal with inbound calling without billing for it?  Can customers just point their DID's at the platform from other providers?

**Comment by powerpbx** [comment]
bump

**Comment by cruzccl** [comment]
Hi @powerpbx,

As told in the previous note, inbound call billing was developed as an external module for Oasis. This external module was not part of IvozProvider and was never published.

We have no plans for adding inbound call billing for Artemis, unless one of our clients or you yourself want to sponsor its development.

As always, you can contact comercial@irontec.com if you have real interest in evolving IvozProvider with this or any other feature you miss.

Regards,

**Comment by clecny** [comment]
This  is necessary feature  when inbound number is Toll free number.

**Comment by Kaian** [comment]
Please, read (FAQ)[https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md] regarding missing or necessary features.
