### ISSUE TITLE
Asterisk features.conf (Attended xfer)

### ISSUE THREAD

**Issue by amvidalrc** [irontec/ivozprovider#877]
Hello.

I want to know how to enable asterisk function "attended xfer". I have enabled it on features.conf but I think it's not working.

I have some customers using old phones and we need this feature available.

Thanks in advance!!

**Comment by amvidalrc** [comment]
I have got it working but I can't place the call:

       > [b1][3596c21f] Executing [102@users:1] NoOp("Local/102@users-000001c6;2", "Outgoing call from user "Alvaro" <100> to 102") in new stack
       > [b1][3596c21f] Executing [102@users:2] AGI("Local/102@users-000001c6;2", "agi://127.0.0.1:4573/cli.php?model=default/calls/users") in new stack
    -- Channel PJSIP/b1c2t4_alvaro-00020be8 left 'simple_bridge' basic-bridge <c7328aa4-9021-44f7-b5dd-4eb60c0bdb2c>
    -- Channel PJSIP/b1c2t4_alvaro-00020be8 joined 'simple_bridge' basic-bridge <438a42f0-e4b2-4da1-9a56-74339d8f09f1>
[Jan 31 13:48:59] WARNING[6275][C-00010604]: func_channel.c:465 func_channel_read: Unknown or unavailable item requested: 'endpoint'
       > [b1][3596c21f] [CallsController.php:131  ] AGI Error ("**Local/102@users-000001c6;2", "Call without valid endpointName. Dropping.**")
    -- <Local/102@users-000001c6;2>AGI Script agi://127.0.0.1:4573/cli.php?model=default/calls/users completed, returning 0

**Comment by powerpbx** [comment]
This is how we added echo test.  Adding some other feature code would probably be similar.

https://github.com/powerpbx/ivozprovider/commit/bc9531cb8c504570ee947e53863746a71fa272ac

**Comment by amvidalrc** [comment]
This is a feature that need to be called on a running and active call. I get it working, changing the Queue Call Args (Adding "tT") and enabling the Attended xfer feature on asterisk features.conf but its not working because the pasted error:


> [b1][3596c21f] Executing [102@users:1] NoOp("Local/102@users-000001c6;2", "Outgoing call from user "Alvaro" <100> to 102") in new stack
      > [b1][3596c21f] Executing [102@users:2] AGI("Local/102@users-000001c6;2", "agi://127.0.0.1:4573/cli.php?model=default/calls/users") in new stack
   -- Channel PJSIP/b1c2t4_alvaro-00020be8 left 'simple_bridge' basic-bridge <c7328aa4-9021-44f7-b5dd-4eb60c0bdb2c>
   -- Channel PJSIP/b1c2t4_alvaro-00020be8 joined 'simple_bridge' basic-bridge <438a42f0-e4b2-4da1-9a56-74339d8f09f1>
[Jan 31 13:48:59] WARNING[6275][C-00010604]: func_channel.c:465 func_channel_read: Unknown or unavailable item requested: 'endpoint'
      > [b1][3596c21f] [CallsController.php:131  ] AGI Error ("**Local/102@users-000001c6;2", "Call without valid endpointName. Dropping.**")
   -- <Local/102@users-000001c6;2>AGI Script agi://127.0.0.1:4573/cli.php?model=default/calls/users completed, returning 0

So I need any way to get the correct endpoint here...

**Comment by Kaian** [comment]
What version are you using 1.x (oasis) or 2.x (artemis)?

The dialplan pasted doesn't look like a queue calling to a user. Queues use _Local/{userid}@queues_ to call the user. Also I think the _tT_ options must be added to the Dial application in this case, rather than the Queue application, because queue uses Local channels, but I'm not sure without testing.

**Comment by amvidalrc** [comment]
Hi Kaian. Im using oasis stable.
I have modified the agi adding the tT option and I get the function work, I press *2 and the call goes on hold and i can dial, when I dial Asterisk send the call to a Local context: [b1][3596c21f] Executing [102@users:1] NoOp("Local/102@users-000001c6;2 and your AGI doest not recognize it, because I think its not a PJSIP call with the endpoint, I think... So the call to the next party is never executed.

**Comment by Kaian** [comment]
> your AGI doest not recognize it, because I think its not a PJSIP call with the endpoint, I think... So the call to the next party is never executed.

Yep, that context is used for incoming calls from users' terminals, so we expect a PJSIP channel and an endpoint name there, _unless_ it's a redirected call (p.e. 302 Moved from a terminal).

https://github.com/irontec/ivozprovider/blob/oasis/asterisk/agi/application/controllers/CallsController.php#L113-L117

The _if_ that is checking if the user is found is a bit below, in line 130. You can add that lines inside the if to try to find the endpointName from DIAL_ENDPOINT channel variable.

Not sure if that would work. Also beware that these changes will be not supported by the project and may be lost if you upgrade some day! We're trying to avoid as much as possible asterisk builtin features (hopefully one day we can remove on demand record DTMFs in asterisk)

Regards!
