### ISSUE TITLE
Little typo in kam trunk config file

### ISSUE THREAD

**Issue by glacroix** [irontec/ivozprovider#914]
Hello,

There is a little typo in : 
ivozprovider/kamailio/trunks/config/kamailio.cfg

Line 1024 is : 
append_hf("Remote-Party-ID: $var(newfromuri);privacy=off;screen=no\r\n");

And should be (the < and > are missing) : 
append_hf("Remote-Party-ID: <$var(newfromuri)>;privacy=off;screen=no\r\n");

Bye,
Guillaume

**Comment by cruzccl** [comment]
Fixed in 87bdb65.

Thanks @glacroix!
