### ISSUE TITLE
Adding queue end to voicemail on pbx : I see voicemails from other PBX clients

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#931]
Wile configuring a time out router end of QUEUE to Voicemal on  PBX I can see all of other voicemails from other clients.
Letting to make a mistake

ivpozprovider package 2.9~2.9.3~20190318.1934~33c273a+artemis  all

**Comment by Kaian** [comment]
Hi @gil-obradors 

Current portal framework (klear) does not use Rest API to access data, so this kind of filtering must be done for each field and, like in this case, a small typo may lead to serious cross data issues. This won't happen in future portals, using API Rest to restrict what administrators can see, although they won't be ready anytime soon, so we appreciate bugs reports like this one.

I'll port  this to artemis, so this should be fixed if you upgrade your packages now.

Thanks for reporting!

**Comment by gil-obradors** [comment]
it is a pleasure to collaborate!
