### ISSUE TITLE
Queue timeout to user-voicemail : not listening default locution, directly to recording

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#938]
PBX client with some users and extensions.
DDI-IN routed to queue Y
Queue Y configured with timeout redirection to voicemail -> userX

Calling to DDI, 15seconds of queue, not listening voicemail message, directly to record

DD-IN direct to user Y
user Y with CFinconditional or 10segons no response, to voicemail
Voicemail default message listening ok.

**Comment by Kaian** [comment]
Hi @gil-obradors 

This is the intended behaviour.

The general rule: if the route has a locution available, the voicemail banner is skipped. 

This also applies to external call filters (holiday or out of schedule) and any other routes with specific locutions fields.

Regards!

**Comment by gil-obradors** [comment]
Ah oky, I understand.
On routes  -->Locution : unassigned equal to no locution
On user config ---> Locution: unassigned equal to default voicemail locution

Thank you :)

**Comment by Kaian** [comment]
Yes.

The reason behind that decission is that, originally, the voicemail banner said the user extension, and the feedback while listening to _'User at extension 101 is not available'_ after a queue timeout was a bit weird.

You can still configure a locution in the route like _All our agents are busy right now_ and then send the call to voicemail (silently, without banner).

Then, we added Voicemail Locution in user configuration to override the default banner, although, as mentioned previously, it's only played when User configures a Callforward Setting. As bonus, users can also configure their own locution using Voicemail menu.

Regards!!
