### ISSUE TITLE
Saving prepaid balance

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#950]
It looks like prepaid balance only resides on Cgrates Redis DB.  So if I flush the Redis DB, I lose it forever.  Would it make sense to save the current prepaid balance value on MySQL every minute, along with the billable calls, using the `ivozprovider-cdrs.timer` systemd timer?   So it will only be updated when there is a Billable Call added.  It could just be another column in the BillableCalls table.

I think that is the only thing on the Redis DB that is not archived on the MySQL DB.

**Comment by Kaian** [comment]
Hi @powerpbx 

Company and Carriers tables have a balance field that is synced with its redis value by [balances microservice](https://github.com/irontec/ivozprovider/tree/bleeding/microservices/balances). This fields are not used at all afaik but serve as a non-volatile backup in case of redis disaster.

Balance micorservice runs [every 3 minutes](https://github.com/irontec/ivozprovider/blob/bleeding/debian/systemd/ivozprovider-balances.timer), but you can change it to whatever fits your environment.

Regards!

**Comment by powerpbx** [comment]
Thanks for the info on the balances timer. It is apparently disabled by default on distributed install so I had it disabled.

One problem with that is that there is no history saved.  Only the current value.  So if the Redis DB is flushed or is lost, the next time that timer runs it goes to 0.  If it was also saved in the BillableCalls table, along with each new billable call, there would be a history.   If it went to 0 because of a Redis DB flush, the previous value would still be there.
