### ISSUE TITLE
Incoming external calls in CDRs

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#956]
This issue aims to:

- Convert "Billable Calls" sections into "External Calls", showing both external outgoing and external incoming calls (new field: Direction).

- Billing related fields will be empty for external incoming calls.

- CSV scheduling will allow choosing between incoming/outgoing/both.

- Invoices will ignore incoming external calls.

**Comment by powerpbx** [comment]
It's disappointing that there is not going to be any incoming billing, regardless of the reasons.  It seems like Ivoz will be incomplete without it.  Not sure if it will work for us without it unless we can add it in ourselves.

**Comment by Kaian** [comment]
Let's try not to mix topics here.

We discussed incoming billing in #870, and we concluded that feature could be implemented (see last note).
