### ISSUE TITLE
residential users:  send voicemails by email

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#960]
I was searching where to put the email of a Residential user, but I can't find.
I can redirect calls to voicemail.
I understand that Voicemail services for Residentials is only available by phone, is true?

Is possible to activate ( as PBX) send voicemails by email?

Regards

**Comment by cruzccl** [comment]
Hi @gil-obradors,

You are right, the only way to access to voicemail messages for residential clients is calling to brand's voicemail service code.

This is the usual way to listen messages in this kind of environment and currently there is no plan to implement voicemails via email.

However, if you need this feature and you want to sponsor it, don't hesitate to contact comercial@irontec.com

Regards,

**Comment by gil-obradors** [comment]
Thanks for the information cruzccl!
