### ISSUE TITLE
canceled call

### ISSUE THREAD

**Issue by miquelinv** [irontec/ivozprovider#964]
Hi,

we have configured a new provider trunk, we can receive calls but when making an outgoing call it is canceled.
We have been testing different configuration options with this provider but without satisfactory results.
This is the trace of a call:
![image](https://user-images.githubusercontent.com/29575462/56243861-e2a25e80-609b-11e9-9713-4b859bc40a74.png)

**Comment by cruzccl** [comment]
Hi,

This problem seems to be related to your specific installation or carrier, as we have dozens of working installations with lots of carriers.

If you want to get technical support, please contact comercial@irontec.com

Regards,
