### ISSUE TITLE
Abnormal registered calltime to one call in CDRs

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#983]
This happened only with one register.
Incoming call to a PBX client
Only having one provider, no clustered ivoz provider, 

Ivozprovider, on brand and client says 10800 seconds call
![image](https://user-images.githubusercontent.com/6016929/57529785-0de43a80-7336-11e9-8516-ae43feae9389.png)

My provider CDR says 306 seconds
![image](https://user-images.githubusercontent.com/6016929/57529950-6adff080-7336-11e9-8ec3-eab0d81b72bb.png)

If I can contribute with more information, more logs .... Here I'm
Or if it repeats another time in future, what can I do to help?

Thank you!

**Comment by Kaian** [comment]
Hi @gil-obradors 

That list display the contents of BillableCalls. That table is populated by a microservice called cdrmixer, that takes the information from kam_trunks_cdrs and cgrates to generate each row. You should start by checking kam_trunks_cdrs table and look for the corresponding row. If duration is the same, we can discard a problem in the cdrmixer.

Next you should try to find the SIP signaling information. If you don't have a capture platform (like Homer or something like that), try looking in the journal for the call.

```
journalctl -u kamailio@trunks --since xxxx | grep your-call-id
```

All messages for that dialog should share a 8 character hash so you can also grep for that hash. Look for the initial INVITE and the final BYE and check the dates. That will provide a bit more light of what happened to that call.

Regards!

**Comment by gil-obradors** [comment]
kam_trunks_cdrs says 10799.667, that's 10800.

I haven't got capture platform and too much days have passed for journalctl.
I have no more info.

Thank you for your time, I will be more prepared if it is repeated.

**Comment by Kaian** [comment]
We haven't experienced this problem ourselves.

Due to the lack of information, I will close this. If it happens again and we have a clear proof of error don't hesitate to reopen it!

Regards!

**Comment by Kaian** [comment]
Wait a second...

https://github.com/irontec/ivozprovider/blob/d63d56a98fd92b40fb54c9bdca06b29e6bffab9e/kamailio/trunks/config/kamailio.cfg#L35

Max dialog timeout is 10800 seconds, that means your carrier sent a BYE but ivozprovider didn't received it so the call was kept alive.

We don't have rtp teardown (drop call when no rtp is detected) so this will explain the problem

**Comment by gil-obradors** [comment]
ack!
Thank you for your time!!
